### ISSUE TITLE
tailwindcss error

### ISSUE THREAD

**Issue by Tindome** [esm-dev/esm.sh#10]
Hello,

Another try (using deno and postcss)
when trying to use it with tailwindcss

```
import tailwindcss from 'https://esm.sh/tailwindcss'
...
```

i get the following error

error: Uncaught TypeError: k_.Parser.extend(...).extend is not a function
    at https://cdn.esm.sh/v14/tailwindcss@2.0.2/esnext/tailwindcss.js:25:17298
    at https://cdn.esm.sh/v14/tailwindcss@2.0.2/esnext/tailwindcss.js:2:1074
    at https://cdn.esm.sh/v14/tailwindcss@2.0.2/esnext/tailwindcss.js:25:26185
    at https://cdn.esm.sh/v14/tailwindcss@2.0.2/esnext/tailwindcss.js:2:1074
    at https://cdn.esm.sh/v14/tailwindcss@2.0.2/esnext/tailwindcss.js:25:27714
    at https://cdn.esm.sh/v14/tailwindcss@2.0.2/esnext/tailwindcss.js:2:1074
    at https://cdn.esm.sh/v14/tailwindcss@2.0.2/esnext/tailwindcss.js:89:35993
    at https://cdn.esm.sh/v14/tailwindcss@2.0.2/esnext/tailwindcss.js:2:1074
    at https://cdn.esm.sh/v14/tailwindcss@2.0.2/esnext/tailwindcss.js:89:37184

thanks for helping/idea

**Comment by aadamsx** [comment]
Please add Deno support to Tailwind, I'm using Deno/Alephjs (React) and would really like to use Tailwind as I do in my Node/Nextjs (React) projects: https://github.com/alephjs/aleph.js/issues/42#issuecomment-806056884

**Comment by talentlessguy** [comment]
still fails because of #157 

```
Download https://esm.sh/tailwindcss
Download https://cdn.esm.sh/v53/fsevents@2.3.2/deno/fsevents.js
error: Import 'https://cdn.esm.sh/v53/fsevents@2.3.2/deno/fsevents.js' failed: 500 Internal Server Error
    at https://cdn.esm.sh/v53/chokidar@3.5.2/deno/chokidar.js:2:414
```

**Comment by ije** [comment]
i think this has been fixed
