### ISSUE TITLE
Aliasing dependencies doesn't affect typescript declaration

### ISSUE THREAD

**Issue by takker99** [esm-dev/esm.sh#102]
In some packages, aliasing dependencies doesn't affect typescript declaration.

For example, https://esm.sh/use-resize-observer@7.0.1?alias=react:preact&deps=preact@10.5.14 is expected to use https://cdn.esm.sh/v45/deps=preact@10.5.14/preact@10.5.14/src/index.d.ts, but actually uses https://cdn.esm.sh/v45/deps=preact@10.5.14/@types/react@17.0.19/index.d.ts

**Comment by ije** [comment]
@takker99 thanks I will fix this later！

**Comment by lucacasonato** [comment]
@ije Can I sponsor (Patreon, Paypal, GH Sponsors, or similar) you in any way to get this fixed?

**Comment by ije** [comment]
@lucacasonato i will fix it very soon, no sponsor needed, thanks for your kind!

**Comment by sachinraja** [comment]
@ije still seeing this so I'm also wondering if there's any way we can sponsor you for this now.

**Comment by sachinraja** [comment]
Thanks for fixing this so quickly!
