### ISSUE TITLE
Count of Served Packages and Requests

### ISSUE THREAD

**Issue by shadowtime2000** [esm-dev/esm.sh#11]
Would be nice to see some stats like served packages and number of requests per month.

**Comment by ije** [comment]
yes! i will create a new website in the future that can show the network statistics with clouldflare api.

**Comment by renhiyama** [comment]
This feature is available for a while (Total count of requests). Shouldn't this issue be closed? @ije @shadowtime2000

**Comment by mootari** [comment]
Is this information still exposed somewhere?

Edit: Nvm, found it after scrolling down on esm.sh (I usually search or use the links).
