### ISSUE TITLE
Why not 302 to CDN address?

### ISSUE THREAD

**Issue by jimisaacs** [esm-dev/esm.sh#128]
I wondered this, and then I saw how esm.run does it (i.e. https://esm.run/d3). They actually 301, and I understand you are making room for rebuilds, which is why I mentioned 302. Why not?

**Comment by jimisaacs** [comment]
I think I answered my own question. It needs to add the typescript types for deno 🤔.

**Comment by ije** [comment]
1. resolve module version
2. split traffic (there is a different CDN `x-statio.io` that is hosted in china mainland
3. yes, add types header for deno
