### ISSUE TITLE
Something is wrong with the npm version resolution

### ISSUE THREAD

**Issue by jimisaacs** [esm-dev/esm.sh#138]
I'm seeing packages that depend on things like `^1.3.3` resolve to beta versions such as `1.3.3-beta.2`. This is not good. As the `^` constraint, means any compatible version of major minor. Though in NPM, no "pre-release" versions, i.e. any version like `{major}.{minor}.{patch}-{extra}`, the `-{extra}` ALWAYS means it will not resolve as compatible.

This is likely breaking many package installs.

**Comment by jimisaacs** [comment]
Unfortunately I do not have a repro with public packages at the moment, as I've been paying closest attention to private packages.

**Comment by ije** [comment]
@jimisaacs this can be fixed in https://github.com/alephjs/esm.sh/blob/7d6534aa334c1276589d73bf79f23c795025b3be/server/nodejs.go#L328

**Comment by jimisaacs** [comment]
Thanks for looking, I'm still debugging it, thinking it *might* be related to peer dependencies, I also thought I ruled out a package problem, but won't be sure until I spend quite sifting through where that version is coming from.

**Comment by jimisaacs** [comment]
I know you are using yarn, which I didn't think installed peer dependencies, so I'm wondering how you are handling that now.

**Comment by jimisaacs** [comment]
I've looked all I can right now, but I still can't figure out where the `-beta.{n}` is coming from. It's a standard peerDependency of `^1.2.3`, but it's still getting `1.2.3-beta` for only two of them. Will continue to look, and I guess just keep a watch on something like this in the public registry space.

**Comment by ije** [comment]
> I know you are using yarn, which I didn't think installed peer dependencies, so I'm wondering how you are handling that now.

no need to install the peer deps not all, since we get the peer deps version info from npm registry directly

**Comment by ije** [comment]
> I've looked all I can right now, but I still can't figure out where the `-beta.{n}` is coming from. It's a standard peerDependency of `^1.2.3`, but it's still getting `1.2.3-beta` for only two of them. Will continue to look, and I guess just keep a watch for something like this in the public registry space.

what is the url?

**Comment by jimisaacs** [comment]
Sorry, it's a private package. So if you want to look at it, to see data you won't find it. If you just want to see the URL, I can share the shape of it with the name changed for privacy

**Comment by ije** [comment]
ref #168
