### ISSUE TITLE
Failed to import - @mdx-js/mdx

### ISSUE THREAD

**Issue by talentlessguy** [esm-dev/esm.sh#142]
## Failing module

- **GitHub**: https://github.com/mdx-js/mdx/
- **npm**:https://www.npmjs.com/package/@mdx-js/mdx

```js
import * as mod from 'https://esm.sh/@mdx-js/mdx'
```

## Error message

After running `deno run` I get this:

```
error: TS2502 [ERROR]: 'thisArg' is referenced directly or indirectly in its own type annotation.
    bind<T>(this: T, thisArg: ThisParameterType<T>): OmitThisParameter<T>;
                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    at asset:///lib.es5.d.ts:350:22

TS2577 [ERROR]: Return type annotation circularly references itself.
    bind<T>(this: T, thisArg: ThisParameterType<T>): OmitThisParameter<T>;
                                                     ~~~~~~~~~~~~~~~~~~~~
    at asset:///lib.es5.d.ts:350:54

Found 2 errors.
```

## Additional info

- **esm.sh version**: v50
- **Deno version**: 1.13.2

## Analysis

After analyzing the issue I found out it is because `helper-function-name.js` starts with [this import](https://github.com/babel/babel/blob/main/packages/babel-helper-function-name/src/index.ts#L2):

```ts
import template from "@babel/template";
// below at line 21...
const buildPropertyMethodAssignmentWrapper = template(`... `)
```

Which is [transpiled](https://cdn.esm.sh/v53/@babel/helper-function-name@7.15.4/deno/helper-function-name.js) as

```js
import ___babel_template$ from '/v53/@babel/template@7.15.4/deno/template.js';
// ...
var N = ___babel_template$;
// ...
j = (0, N.default)(`...`)
```

So you can see we're importing the default export but then again we try to access it's default property for some reason.

**Comment by talentlessguy** [comment]
from @amatiasq:

```
➜ deno eval 'import * as mod from \'https://esm.sh/@mdx-js/mdx\''
error: Uncaught TypeError: (0 , N.default) is not a function
    at https://cdn.esm.sh/v53/@babel/helper-function-name@7.15.4/deno/helper-function-name.js:2:1429
    at https://cdn.esm.sh/v53/@babel/helper-function-name@7.15.4/deno/helper-function-name.js:2:640
    at https://cdn.esm.sh/v53/@babel/helper-function-name@7.15.4/deno/helper-function-name.js:26:1406
```

**Comment by amatiasq** [comment]
@talentlessguy Isn't this a different issue? I know they refer to the same module bit the errors que got are different so solving one doesn't necessarily mean the other will be fixed too.

Analysis copied from #167:

---

After analyzing the issue I found out it is because `helper-function-name.js` starts with [this import](https://github.com/babel/babel/blob/main/packages/babel-helper-function-name/src/index.ts#L2):

```ts
import template from "@babel/template";
// below at line 21...
const buildPropertyMethodAssignmentWrapper = template(`... `)
```

Which is [transpiled](https://cdn.esm.sh/v53/@babel/helper-function-name@7.15.4/deno/helper-function-name.js) as

```js
import ___babel_template$ from '/v53/@babel/template@7.15.4/deno/template.js';
// ...
var N = ___babel_template$;
// ...
j = (0, N.default)(`...`)
```

So you can see we're importing the default export but then again we try to access it's default property for some reason.

**Comment by talentlessguy** [comment]
@amatiasq done, thx

**Comment by talentlessguy** [comment]
still getting on v57:

```
➜ deno eval --unstable "import * as mod from 'https://esm.sh/@mdx-js/mdx?pin=v57'"
Download https://esm.sh/@mdx-js/mdx?pin=v57
error: Uncaught TypeError: (0 , N.default) is not a function
    at https://cdn.esm.sh/v57/@babel/helper-function-name@7.16.0/deno/helper-function-name.js:2:1595
    at https://cdn.esm.sh/v57/@babel/helper-function-name@7.16.0/deno/helper-function-name.js:2:806
    at https://cdn.esm.sh/v57/@babel/helper-function-name@7.16.0/deno/helper-function-name.js:26:1406
```

**Comment by talentlessguy** [comment]
it works now on v78
