### ISSUE TITLE
Cache is not invalidated after esm.sh updates

### ISSUE THREAD

**Issue by lucacasonato** [esm-dev/esm.sh#150]
After esm.sh updates, I sometimes get into the state where one import request results in a v46 release, and another results in a v47 (for example). This then causes dependencies to get duplicated in the dependency graph. Could you maybe force flush the cache after each update?

**Comment by ije** [comment]
@lucacasonato thanks for the suggestion! i will do it after each update manually for now. and i will create an automatic script for this later.

**Comment by sjmueller** [comment]
This happened to me with `v54` mixed in shortly after the `v55` release

**Comment by lucacasonato** [comment]
And same thing happening now for v55 and v56 update. Are you purging the Cloudflare cache after each release?

**Comment by lucacasonato** [comment]
Importing `https://esm.sh/he@1.2.0` still returns `https://esm.sh/he@1.2.0` still returns `https://cdn.esm.sh/v55/he@1.2.0/deno/he.js` for me. This is a rather serious issue. Is there any way I can help @ije?

**Comment by ije** [comment]
@lucacasonato i just purged the cloudfleare cache, it works for me. In addition, I added the `pin` mode to lock the build version:
```
https://esm.sh/he?pin=v57
```

**Comment by lucacasonato** [comment]
That is great, thanks.

**Comment by ije** [comment]
i am going to close this since long time passed
