### ISSUE TITLE
Specify external dependencies of dependencies

### ISSUE THREAD

**Issue by philippkuehn** [esm-dev/esm.sh#165]
It would be nice if the `deps` parameter would also work for dependencies of dependencies. 

For example I want to specify a version of `@tiptap/core`. Within `@tiptap/starter-kit` some other packages are loaded, e.g. `@tiptap/extension-blockquote`. `@tiptap/extension-blockquote` also depends on `@tiptap/core` but esm.sh loads a different version of it (2.0.0-beta.99). Setting `deps` on `@tiptap/starter-kit` doesn’t help unfortunately.

Can be tested with this html file.

```html
<!doctype html>
<head>
  <meta charset="utf-8">
</head>
<body>
  <div class="element"></div>
  <script type="module">
    import { Editor } from 'https://esm.sh/@tiptap/core@2.0.0-beta.109'
    import StarterKit from 'https://esm.sh/@tiptap/starter-kit?deps=@tiptap/core@2.0.0-beta.109'
    
    const editor = new Editor({
      element: document.querySelector('.element'),
      extensions: [
        StarterKit,
      ],
      content: '<p>Your content.</p>',
    })
  </script>
</body>
</html>
```

**Comment by ije** [comment]
@philippkuehn i think this is a bug, i will fix this, thanks 🙏

**Comment by its-me-ilia** [comment]
Any update?

**Comment by ysulyma** [comment]
Encountering this for packages that rely on React (I'm trying to force everything to use `react@17.0.2`).

**Comment by ysulyma** [comment]
@ije this makes esm.sh unusable for packages that transitively depend on React or THREE, which have to be globally unique. For example `@react-three/fiber` imports `react-use-measure` which imports `react@18.0.0` (the latest version is `18.1.0`).

**Comment by igorbrasileiro** [comment]
Some news here? I'm facing this "issue", do we have a workaround? In my case i can't use importmap 😞

**Comment by ije** [comment]
i just added a patch for this, needs v136 deployment for working, will deploy later
