### ISSUE TITLE
import npm package with multiple entry points

### ISSUE THREAD

**Issue by c0per** [esm-dev/esm.sh#203]
When an npm package has multiple entry points (e.g. both `main` and `browser` entry in `package.json`), how am I supposed to specified witch entry point do I need.

Currently I'm trying to import `superagent`, wich has both `main` and `browser` in its `package.json`. I think esm.sh is building the `browser` version of the package even when I use `target=deno`.

Is there any way I can specified the "environmental varible" not to "browser"? Thanks.

**Comment by ije** [comment]
`target=deno` uses `main`, `target=es[version]` uses `browser` if it exits
