### ISSUE TITLE
Unable to override `target=deno` when using Deno

### ISSUE THREAD

**Issue by nnmrts** [esm-dev/esm.sh#209]
After reading the "Specify ESM target" section on https://esm.sh/, I assumed
> By default, esm.sh will check the User-Agent header to get the build target automatically.

means that I can override that beahaviour by using `?target`.

But it seems like that's not the case. See for example this import, the second and every url after it has `deno` instead of `esnext` in it:

![Bildschirmfoto 2021-11-06 um 10 10 12](https://user-images.githubusercontent.com/20396367/140604500-48ac5f59-7499-46cd-b16f-5fd98fc5e188.png)

I've tested this with a lot of different packages, this is a general issue, not just with this package.

Maybe my assumption was wrong and this is working as intended, but I still think there should be a way to override this behaviour.

**Comment by ije** [comment]
now you can override the `target` in **v65** when using deno

**Comment by nnmrts** [comment]
Awesome, thanks!
