### ISSUE TITLE
Where is the best place to report an outage?

### ISSUE THREAD

**Issue by clo4** [esm-dev/esm.sh#210]
[This failed CI run is the first time I noticed.](https://github.com/SeparateRecords/deno_jamf_school/runs/4132975768?check_suite_focus=true)

Where is the best place to report if there's an outage? GH Issues, Discussions, or somewhere less formal?

*(Edit: esm.sh was down before, changed title to reflect the question now that it's up again now)*

**Comment by ralyodio** [comment]
i noticed this too.
