### ISSUE TITLE
Failed to import - lit

### ISSUE THREAD

**Issue by kiuma** [esm-dev/esm.sh#227]
## Failing module

- **GitHub**: 
- **npm**:

```js
import {html, css, LitElement} from 'https://esm.sh/lit';
```

## Error message

After running `deno run` I get this:

```
Download https://cdn.esm.sh/v58/lit-element@3.0.2/lit-element.js~.d.ts
error: Import 'https://cdn.esm.sh/v58/lit-element@3.0.2/lit-element.js~.d.ts' failed: 500 Internal Server Error
```

## Additional info

- **esm.sh version**: v58
- **Deno version**: 1.16.4

**Comment by lilnasy** [comment]
I ran into the same issue today. I was hoping it just affects v58 but it goes back quite a bit.

**Comment by Tentacola** [comment]
So the problem is that deno tries to load the types from the wrong url
Not sure if this is a problem with deno or that esm.sh provides the wrong url.
All of them put the wrong extension at the end `.js~.d.ts` instead of `.d.ts`

However a workaround can be to override the types manually with the correct type file.
Here are some examples how to do that:
```
// @deno-types="https://cdn.esm.sh/v58/lit-element@3.0.2/lit-element.d.ts"
import { html, LitElement } from "https://cdn.esm.sh/v58/lit@2.0.2";

// @deno-types="https://cdn.esm.sh/v58/@lit/reactive-element@1.0.2/decorators/property.d.ts"
import { property } from "https://cdn.esm.sh/v58/@lit/reactive-element@1.0.2/decorators/property.js";

// @deno-types="https://cdn.esm.sh/v58/@lit/reactive-element@1.0.2/decorators/custom-element.d.ts"
import { customElement } from "https://cdn.esm.sh/v58/@lit/reactive-element@1.0.2/decorators/custom-element.js";
```

**Comment by talentlessguy** [comment]
it now fails bc of this:

```
> import {html, css, LitElement} from 'https://esm.sh/lit?pin=v61'

Uncaught ReferenceError: HTMLElement is not defined
    at https://cdn.esm.sh/v61/@lit/reactive-element@1.1.1/deno/css-tag.js:2:1717

```

**Comment by Tentacola** [comment]
Nice that is progress :)
I think that error is probably because you are not using the "dom" library in typescript settings.
See [here](https://deno.land/manual@v1.17.2/typescript/configuration#targeting-deno-and-the-browser)

**Comment by ije** [comment]
@talentlessguy you can specify the "dom" types in the `deno.json`(tsconfig)
```jsonc
// deno.json
{
  "compilerOptions": {
    "lib": [
      "dom",
      "deno.ns" 
    ]
  }
}
```

**Comment by tdillon** [comment]
@JasperVanEsveld, @lilnasy, @talentlessguy have any of you been able to get this to work?

```typscript
import { html, css, LitElement } from "https://esm.sh/lit@2.2.3?target=deno"
// ERROR: TS2305 [ERROR]: Module '"https://cdn.esm.sh/v78/lit@2.2.3/index.d.ts"' has no exported member html, css, LitElement.
```
