### ISSUE TITLE
Deno babel helpers import fails

### ISSUE THREAD

**Issue by abetaev** [esm-dev/esm.sh#229]
Something wrong is going on with the server
`GET https://cdn.esm.sh/v58/@babel/runtime@7.16.5/deno/helpers/esm/extends.js`
results in
`500 Internal Server Error`
and the following body:
```
/* esm.sh - error */
throw new Error("[esm.sh] " + "parseCJSModuleExports: Can't resolve '@babel/runtime/helpers/esm/extends' in '/tmp/esm-build-c7210890451e520cc3e3082a95465dc682656511-0e7bcf98'");
export default null;
```

My build works just fine with local cache, but my CI fails with this error. Trying to add other dependencies locally causes this error during local build. Seems that something's affected the way esm.sh bundles libraries.

`deno bundle` prints the following line and exits
```
error: Import 'https://cdn.esm.sh/v58/@babel/runtime@7.16.5/deno/helpers/esm/extends.js' failed: 500 Internal Server Erro
```

## Additional info

- **esm.sh version**: v58
- **Deno version**: 1.16.4

**Comment by ayoreis** [comment]
I also have this error when trying to import react-router-dom! Hopefully, it get fixed soon.

**Comment by KyleJune** [comment]
The latest working version is https://cdn.esm.sh/v58/@babel/runtime@7.16.3/deno/helpers/esm/extends.js. I encountered this issue when trying to use react-router-dom. I resolved it for my project by manually overriding the history@5.2.0 which used the broken babel runtime dependency with history@5.1.0 which used the latest working babel runtime.

https://github.com/alephjs/esm.sh/issues/235

**Comment by ayoreis** [comment]
@KyleJune I am having the same issue! So how do I import `react-router-dom`? I didn't understand.

**Comment by KyleJune** [comment]
You can copy my deps folder that has the fixed versions of react, react-dom, react-router-dom, and react-router then import from them instead of importing from esm.sh. I just took the esm.sh files and modified them to get them working. In the below deps.ts file, you can see it imports from my local deps directory instead of from the esm.sh urls. I plan on switching back to esm once issues are resolved.

https://github.com/KyleJune/deno-tailwind-ui-react-example/blob/406f553efad8f9f2d48920bef987e9d71c4aab7a/components/deps.ts

For a complete example of using react with deno deploy, check out that example repository I made.

https://github.com/KyleJune/deno-tailwind-ui-react-example/

**Comment by abetaev** [comment]
guys, the issue seems to be related to infrastructure, not to the code of esm.sh. i have setup esm.sh locally on my dev machine and directed deno to look at it using import maps. i can import everything without a problem now and it works much faster than through hosted service.

i can suggest the following:
1. run docker container
    ```bash
    git clone https://github.com/alephjs/esm.sh.git
    cd esm.sh
    docker build . -t esm
    docker run -d \
               -v esm:/esm.sh/.esmd \
               -p 8080:8080 \
               esm esm --port 8080 --cdn-domain localhost:8080
    ```
2. and `--import-config imports.json`, where `imports.json` contains:
    ```json
    {
      "imports": {
        "/esm/": "http://localhost:8080/"
      }
    }
    ```
3. then in your code you can point to dependencies like
    ```typescript
    import React from '/esm/react'
    ```
this might require some enhancement for CI build if you have it, but basically you'll need to spawn esm container and provide imports with `/esm/` entry pointing to that container.
if you use docker to build your apps, consider adding `--network host` to allow docker access esm container.

**Comment by KyleJune** [comment]
> guys, the issue seems to be related to infrastructure, not to the code of esm.sh. i have setup esm.sh locally on my dev machine and directed deno to look at it using import maps. i can import everything without a problem now and it works much faster than through hosted service.

It's still an issue that esm.sh can end up in a bad state like this that it doesn't recover from on its own. I don't think most people would host their own instance of esm.

**Comment by ije** [comment]
This should be fixed in the latest update
