### ISSUE TITLE
Child dependencies ignore dependency overrides on parent module

### ISSUE THREAD

**Issue by KyleJune** [esm-dev/esm.sh#235]
## Issue

react-router-dom has a dependency that has an issue, history@5.2.0 fails, so I tried overriding it with history@5.1.0. It works but only for react-router-dom. react-router-dom depends on react-router. the react-router dependency is ignoring the history override resulting in react-router-dom still trying to load history@5.1.0.

https://esm.sh/react-router-dom@6.2.1?deps=react@17.0.2,history@5.1.0

To work around this issue, I had to make local copies of react-router-dom and react-router so that I could make sure they are both using history@5.1.0.

## Additional info

- **esm.sh version**: v58

**Comment by KyleJune** [comment]
I found a way to resolve the issue using the following import map.

```
{
  "imports": {
    "https://cdn.esm.sh/v58/history@5.2.0/deno/history.js": "https://cdn.esm.sh/v58/history@5.1.0/deno/history.js",
    "https://cdn.esm.sh/v58/history@5.2.0/index.d.ts": "https://cdn.esm.sh/v58/history@5.1.0/index.d.ts",
    "https://cdn.esm.sh/v58/@types/react@17.0.37/index.d.ts": "https://cdn.esm.sh/v58/@types/react@17.0.35/index.d.ts",
    "https://cdn.esm.sh/v58/@types/react-dom@17.0.11/index.d.ts": "https://cdn.esm.sh/v58/@types/react-dom@17.0.2/index.d.ts"
  }
}
```

**Comment by KyleJune** [comment]
Looks like I will need to make copies and manually fix the imports to be able to use these modules with deno deploy since deploy does not support import maps yet.

**Comment by KyleJune** [comment]
Here are the changes I made to get these modules to work on deno deploy without import maps.

https://github.com/KyleJune/deno-tailwind-ui-react-example/tree/main/deps

For react I'm just overriding the react@17.0.35 x-typescript-types header with react@17.0.37 types. the reason why is that other modules like react-dom use those types for their react@17.0.2 dependency.

For react-dom I'm just overriding the react-dom@17.0.11 x-typescript-types header with react-dom@17.0.2 types.

For react-dom/server, the types header was completely missing but I found the correct types file.

For react-router and react-dom-router, I just replace the history@5.2.0 dependency with history@5.1.0 because history@5.2.0 has a broken dependency import and if I override the dependency with. ?deps=history@5.1.0, that only applies to react-router-dom. It's child dependency react-router still tries to use history@5.2.0.

**Comment by quaos** [comment]
> I found a way to resolve the issue using the following import map.
> 
> ```
> {
>   "imports": {
>     "https://cdn.esm.sh/v58/history@5.2.0/deno/history.js": "https://cdn.esm.sh/v58/history@5.1.0/deno/history.js",
>     "https://cdn.esm.sh/v58/history@5.2.0/index.d.ts": "https://cdn.esm.sh/v58/history@5.1.0/index.d.ts",
>     "https://cdn.esm.sh/v58/@types/react@17.0.35/index.d.ts": "https://cdn.esm.sh/v58/@types/react@17.0.37/index.d.ts",
>     "https://cdn.esm.sh/v58/@types/react-dom@17.0.11/index.d.ts": "https://cdn.esm.sh/v58/@types/react-dom@17.0.2/index.d.ts"
>   }
> }
> ```

I tried this way, but it seemed not working with `deno bundle`

**Comment by KyleJune** [comment]
> > I found a way to resolve the issue using the following import map.
> > 
> > ```
> > {
> >   "imports": {
> >     "https://cdn.esm.sh/v58/history@5.2.0/deno/history.js": "https://cdn.esm.sh/v58/history@5.1.0/deno/history.js",
> >     "https://cdn.esm.sh/v58/history@5.2.0/index.d.ts": "https://cdn.esm.sh/v58/history@5.1.0/index.d.ts",
> >     "https://cdn.esm.sh/v58/@types/react@17.0.35/index.d.ts": "https://cdn.esm.sh/v58/@types/react@17.0.37/index.d.ts",
> >     "https://cdn.esm.sh/v58/@types/react-dom@17.0.11/index.d.ts": "https://cdn.esm.sh/v58/@types/react-dom@17.0.2/index.d.ts"
> >   }
> > }
> > ```
> 
> I tried this way, but it seemed not working with `deno bundle`

What is the error you are getting? What version of deno are you using? It worked for me on the latest version of deno. As mentioned in my last comment, I switched to not using an import map but it was working locally when I used that import map before.

https://github.com/KyleJune/deno-tailwind-ui-react-example
