### ISSUE TITLE
Failed to import - React-helmet-async and invariant

### ISSUE THREAD

**Issue by KyleJune** [esm-dev/esm.sh#249]
## Failing module

- **npm**: https://www.npmjs.com/package/react-helmet-async
- **npm**: https://www.npmjs.com/package/invariant

```js
import {
  Helmet,
  HelmetProvider,
} from "https://esm.sh/react-helmet-async@1.2.2?target=deno&pin=v62";
```

## Error message

After running `deno run` I get this:

```
error: Import 'https://cdn.esm.sh/v62/invariant@2.2.4/deno/invariant.js' failed: 500 Internal Server Error
    at https://cdn.esm.sh/v62/react-helmet-async@1.2.2/deno/react-helmet-async.js:2:207
```

If I go to the invariant link, I get the following response body.

```
/* esm.sh - error */
throw new Error("[esm.sh] " + "parseCJSModuleExports: timeout");
export default null;
```

This error doesn't happen if I switch to using pin=v61.

## Additional info

- **esm.sh version**: v62
- **Deno version**: 1.17.3

**Comment by ije** [comment]
it works for me, can you please try again?

**Comment by KyleJune** [comment]
Looks like I tmight be a cloudflare issue. I just tried it again and checked response headers. I'm getting the same body response as shown in my original post. If the region I'm in is relevant to the cdn issue, I'm in Chicago, Illinois, US.

![image](https://user-images.githubusercontent.com/3241653/149634241-c4d2f7d4-73e3-4891-ae2d-92c7706a735e.png)

Here is a copy of the report-to JSON from the screenshot.

```json
{"endpoints":[{"url":"https:\/\/a.nel.cloudflare.com\/report\/v3?s=0ZzJwqzVYc4YcWklTV361MeyZ13LiPBfxW34S8R4c0NiEEVmtcZ5uHRDrksONLSf2yb46Gfj2ZIfitKeReo9o0CkF3uWdjYgUzx4CMbj4gUcjErTeG6VrfI%3D"}],"group":"cf-nel","max_age":604800}
```

When I go to the link I get a 405 error.

**Comment by KyleJune** [comment]
I tried turning on my VPN and got same results with California, New York, and United Kingdom.

**Comment by ije** [comment]
<img width="1151" alt="Screen Shot 2022-01-16 at 03 15 53" src="https://user-images.githubusercontent.com/2883484/149634965-f9417abd-73f3-4c6c-97b5-ae1d09d3710d.png">

**Comment by KyleJune** [comment]
I just tried again and it is working now.

**Comment by ije** [comment]
thanks, i am checking the logs to find what happened

**Comment by ije** [comment]
let's keep this issue open, thanks

**Comment by ije** [comment]
i found the node service process exited unexpectedly, i just added a logic to restart the node service when request timeout
