### ISSUE TITLE
Deno + esbuild: ReferenceError: require is not defined

### ISSUE THREAD

**Issue by yw662** [esm-dev/esm.sh#25]
error: Uncaught ReferenceError: require is not defined
    at https://cdn.esm.sh/v15/esbuild@0.8.55/esnext/esbuild.js:8:1378
    at https://cdn.esm.sh/v15/esbuild@0.8.55/esnext/esbuild.js:1:754
    at https://cdn.esm.sh/v15/esbuild@0.8.55/esnext/esbuild.js:8:4069

I can find a `require("child_process")` in [esbuild.js](https://cdn.esm.sh/v15/esbuild@0.8.55/esnext/esbuild.js), which I think is what causes the issue.

**Comment by shadowtime2000** [comment]
esbuild seems like one of those projects that are too big/complex to be able to just use through a CDN for Deno support

**Comment by shadowtime2000** [comment]
> I can find a require("child_process") in esbuild.js, which I think is what causes the issue.

Well kind of. esm.sh at the start of each file adds imports to all depenendcies and then creates a `require` function which takes the name of a package and just returns the result of that import. It seems `require` is being used but a `require` function at the top isn't being generated.
