### ISSUE TITLE
Failed to import - h3-js

### ISSUE THREAD

**Issue by YousefED** [esm-dev/esm.sh#250]
## Failing module

- **npm**: h3-js

h3-js fails to import from a browser environment. You can see that the official esm build (https://unpkg.com/h3-js@3.7.2/dist/h3-js.es.js) optionally imports the `fs` module, but only when in a node-based environment. My guess is that the esm.sh version always imports the `fs` module, and therefore breaks.

```js
import * as h3 from 'https://esm.sh/h3-js'
```

## Error message

`Error: 500  https://cdn.esm.sh/error.js?type=unsupported-nodejs-builtin-module&name=fs&importer=h3-js
    at http://127.0.0.1:3000/static/js/15.chunk.js:457:28`

## Additional info

- **esm.sh version**: v62

**Comment by ije** [comment]
@YousefED thanks, now it works

**Comment by YousefED** [comment]
> @YousefED thanks, now it works

Wow awesome, thanks for the quick response!

Trying to understand the issue and inner workings of esm.sh, can you explain why in esm.sh the `fs` library is imported at all? While in https://unpkg.com/h3-js@3.7.2/dist/h3-js.es.js the `fs` library is optionally imported? I assume this is because `esbuild` compiles the library with different settings than the original module?

Does esm.sh reuse ESM compatible outputs from the module (i.e.: h3-js.es.js), or does it always recompile the entire source?

**Comment by ije** [comment]
it transpiles code follow the js file defined by `main` and `module` in the package.js
