### ISSUE TITLE
Failed to import - rollup-plugin-cleanup requires `--allow-env` since v59

### ISSUE THREAD

**Issue by jespertheend** [esm-dev/esm.sh#254]
## Failing module

- **GitHub**: https://github.com/aMarCruz/rollup-plugin-cleanup
- **npm**: https://www.npmjs.com/package/rollup-plugin-cleanup

```js
import cleanup from "https://esm.sh/rollup-plugin-cleanup@3.2.1?pin=v59";
```

## Error message

After running `deno run --unstable` I got this:

```
error: Uncaught PermissionDenied: Requires env access to "NODE_ENV", run again with the --allow-env flag
    Deno.env.set(String(prop), String(value));
             ^
    at Object.opSync (deno:core/01_core.js:149:12)
    at Object.setEnv [as set] (deno:runtime/js/30_os.js:59:10)
    at Object.set (https://deno.land/std@0.122.0/node/_process/process.ts:57:14)
    at https://cdn.esm.sh/v59/rollup-pluginutils@2.8.2/deno/rollup-pluginutils.js:2:95
```
When importing with `?pin=v58` it works fine.

## Additional info

- **esm.sh version**: v59 and later
- **Deno version**: 1.17.0

**Comment by jespertheend** [comment]
To be clear, running with `--allow-env` is not an issue for me. I'm just wondering if something broke unintentionally.

**Comment by ije** [comment]
i just switched the node(process) polyfill to `https://deno.land/std/node/process.ts` instead of browsers in latest update, so you need the `--allow-env` flag as deno secure protocol when you access to "NODE_ENV"
