### ISSUE TITLE
Failed to import - tailwindcss

### ISSUE THREAD

**Issue by PeterlitsZo** [esm-dev/esm.sh#255]
## Failing module

- **GitHub**: https://github.com/tailwindlabs/tailwindcss

```js
import 'https://esm.sh/tailwindcss/dist/tailwind.min.css'
```

## Error message

After running `deno run` I got this:

```
Download https://esm.sh/tailwindcss/dist/tailwind.min.css
Download https://cdn.esm.sh/tailwindcss@3.0.15/dist/tailwind.min.css
error: Module not found "https://esm.sh/tailwindcss/dist/tailwind.min.css".
    at file:///tmp/xb.ts:1:8
```

## Additional info

- **esm.sh version**: v64
- **Deno version**:1.17.1

**Comment by PeterlitsZo** [comment]
By the way. The import statement is what I find in esm.sh's homepage.

**Comment by ije** [comment]
you should import css with `<link rel="stylesheet" href="https://...">`

**Comment by ije** [comment]
> By the way. The import statement is what I find in esm.sh's homepage.

this only works in alephjs

**Comment by Xeevis** [comment]
Not quite sure what you are trying to accomplish, but that link truly doesn't exist. Latest TailwindCSS 3.x is a library for generating stylesheets and thus doesn't provide any out of the box. You can get stylesheet for 2.x with
```
https://esm.sh/tailwindcss@2/dist/tailwind.min.css
```

**Comment by ije** [comment]
> Not quite sure what you are trying to accomplish, but that link truly doesn't exist. Latest TailwindCSS 3.x is a library for generating stylesheets and thus doesn't provide any out of the box. You can get stylesheet for 2.x with
> 
> ```
> https://esm.sh/tailwindcss@2/dist/tailwind.min.css
> ```

i didn't know this, but this make sense, the `tailwind.min.css` is so huge without `tree-shaking`! i will update the README

**Comment by ije** [comment]
@PeterlitsZo try https://tailwindcss.com/docs/installation/play-cdn instead

**Comment by PeterlitsZo** [comment]
> > By the way. The import statement is what I find in esm.sh's homepage.
> 
> this only works in alephjs

But... I am using alephjs...

**Comment by PeterlitsZo** [comment]
> https://esm.sh/tailwindcss@2/dist/tailwind.min.css

Thanks this can work. but deno looks like do not really good to develop with tailwind...

> @PeterlitsZo try https://tailwindcss.com/docs/installation/play-cdn instead

I try but not work... Thank you for your kindly help...

Maybe I should use node.js and try deno one year later...

**Comment by ije** [comment]
@PeterlitsZo did you try https://deno.land/x/aleph_plugin_windicss ？

**Comment by Xeevis** [comment]
> Thanks this can work. but deno looks like do not really good to develop with tailwind... It can only work for version 2 but not 3... can it?
(...)
> Maybe I should use node.js and try deno one year later...

You can use TailwindCSS 3.x with Deno it's just a bit more work. Last month TailwindCSS [introduced Standalone CLI](https://tailwindcss.com/blog/standalone-cli) which is a self-contained binary. It's still based on Node, but you don't need it installed. Hopefully in the future we'll have [rust-based CLI](https://twitter.com/malfaitrobin/status/1446905317825069063) as well.

1. Download latest binary for your OS https://github.com/tailwindlabs/tailwindcss/releases (and add it to your path or use it bundled).
2. Run it in CLI, you can use stdin/stdout or provide `--input` & `--output` paths
```ps
PS> echo "body { @apply bg-red-500/50; }" | tailwindcss -i - > app.css
```
3. Or for advanced functionality create build.ts file for Deno to run, you can then write the entire workflow like pipe through PostCSS > TailwindCSS CLI > esbuild, example from my build file for inspiration on Windows
```ts
// Standard packages
import { expandGlob } from "https://deno.land/std@0.122.0/fs/mod.ts";

// 3rd  party packages
import * as esbuild from "https://deno.land/x/esbuild@v0.14.13/mod.js";
import * as postcss from "https://deno.land/x/postcss@8.4.5/mod.js";
import type { AcceptedPlugin } from "https://deno.land/x/postcss@8.4.5/lib/postcss.d.ts";
import * as postcss_import from "https://deno.land/x/postcss_import@0.1.4/mod.js";

// Node.js packages
import * as postcss_nesting from "https://esm.sh/postcss-nesting@10.1.2";

async function transformPostCSS() {
  const result = await postcss
    .default([
      postcss_import.default({
        async resolve(id: string, base: string) {
          const files: Array<string> = [];
          for await (const file of expandGlob(join(base, id))) {
            files.push(file.path);
          }
          return files;
        },
      }) as AcceptedPlugin,
      postcss_nesting.default as AcceptedPlugin,
    ])
    .process(await Deno.readTextFile("../assets/css/app.pcss"), {
      from: "../assets/css/app.pcss",
      map: !production,
    });

  await transformTailwindCSS(result.css);
}

async function transformTailwindCSS(postcssInput: string) {
  const cmdArgs = ["cmd", "/C", "tailwindcss", "-i", "-", "-c", "../tailwind.config.cjs"];

  if (!production) {
    cmdArgs.push("-o", "../wwwroot/css/app.css");
    cmdArgs.push("--no-autoprefixer");

    if (minifycssnano) {
      console.log("Minifying with cssnano ...");
      cmdArgs.push("--minify");
    }
  }

  const twprocess = Deno.run({
    cmd: cmdArgs,
    stdin: "piped",
    stdout: "piped",
  });

  await twprocess.stdin.write(new TextEncoder().encode(postcssInput));
  twprocess.stdin.close();

  const [_status, stdout] = await Promise.all([twprocess.status(), twprocess.output()]);
  twprocess.close();

  if (minify) {
    await minifyCss(new TextDecoder().decode(stdout));
  }
}

async function minifyCss(css: string) {
  console.log("Minifying with esbuild ...");
  await esbuild.build({
    stdin: { contents: css, loader: "css" },
    minify: true,
    outfile: "../wwwroot/css/app.css",
  });
  esbuild.stop();
}
```

**Comment by PeterlitsZo** [comment]
Thanks. I am going to close this issue.
