### ISSUE TITLE
Failed to import - domhandler

### ISSUE THREAD

**Issue by jeiea** [esm-dev/esm.sh#258]
## Failing module

- **GitHub**: https://github.com/cheeriojs/cheerio, https://github.com/fb55/domhandler
- **npm**: https://www.npmjs.com/package/cheerio, https://www.npmjs.com/package/domhandler

```js
import juice from "https://cdn.esm.sh/v64/juice@8.0.0/es2021/juice.js";
juice.inlineContent("", "");
```

## Error message

After execution I got this:

```
cheerio.js:2 Uncaught TypeError: Br.Document is not a constructor
    at Object.Ht [as default] (cheerio.js:2:5249)
    at Object.ot [as load] (cheerio.js:4:1748)
    at cheerio.js:4:2287
    at cheerio.js:2:1161
    at cheerio.js:4:2416
```

## Additional info

In my thought above `Br.Document` should be resolved, but for some reason `Br` became default exported class member, other exported member was lost.

- **esm.sh version**: 64
- **Browser version**: Windows Google Chrome 97.0.4692.99 (Official Build) (64-bit)

**Comment by ije** [comment]
thanks, i will look into it

**Comment by ije** [comment]
fixed in **v65**
