### ISSUE TITLE
Failed to import - @tinyhttp/app

### ISSUE THREAD

**Issue by v1rtl** [esm-dev/esm.sh#259]
We should use std/node/http.ts instead of stream-http for Deno environment. `stream-http` is no longer needed. See https://deno.land/std/node/http.ts

## Failing module

- **GitHub**: https://github.com/tinyhttp/tinyhttp

```js
import { App } from 'https://esm.sh/@tinyhttp/app?pin=v64'

```

## Error message

After running `deno run` I got this:

```
Download https://esm.sh/@tinyhttp/app?pin=v64
Uncaught SyntaxError: The requested module '/v64/stream-http@3.2.0/deno/stream-http.bundle.js' does not provide an export named 'IncomingMessage'
    at async <anonymous>:2:18
```

## Additional info

- **esm.sh version**: 64
- **Deno version**: 1.18

**Comment by ije** [comment]
**v66** still not works:

<img width="901" alt="Screenshot 2022-02-08 at 08 52 14" src="https://user-images.githubusercontent.com/2883484/152897213-8a29de1a-c3dd-4cdd-b0de-fb81b641327a.png">

**Comment by ije** [comment]
just tried to move to `deno.land/std/node/http.ts` but failed:

```
error: Uncaught SyntaxError: The requested module 'https://deno.land/std@0.125.0/node/http.ts' does not provide an export named 'IncomingMessage'
```

**Comment by talentlessguy** [comment]
ah yeah it has two separate interfaces for IncomingMessage

**Comment by talentlessguy** [comment]
I guess then until it gets merged

**Comment by talentlessguy** [comment]
It works fine now
