### ISSUE TITLE
Failed to import - sucrase@3.20.3

### ISSUE THREAD

**Issue by elisee** [esm-dev/esm.sh#265]
## Failing module

- **GitHub**: https://github.com/alangpierce/sucrase
- **npm**: https://www.npmjs.com/package/sucrase

```js
import { transform } from "https://esm.sh/sucrase@3.20.3";

// This throws (esm.sh v59-v66)
transform("test();", { transforms: [] });
```

This used to work. I tried pinning a bunch of older versions and finally got it working with `v58`:

```ts
import { transform } from "https://esm.sh/sucrase@3.20.3?pin=v58";

// This works (esm.sh v58)
transform("test();", { transforms: [] });
```

## Error message

After running `deno run` I got this:

```
error: Uncaught TypeError: Ki.default is not a constructor
    at Ui (https://cdn.esm.sh/v66/sucrase@3.20.3/deno/sucrase.js:133:4807)
    at vk (https://cdn.esm.sh/v66/sucrase@3.20.3/deno/sucrase.js:133:4138)
    at .../test.ts:3:1
```

## Additional info

- **esm.sh version**: v66
- **Deno version**: 1.18.2 (release, x86_64-pc-windows-msvc)

**Comment by nihgwu** [comment]
I think it's the same issue as https://github.com/vitejs/vite/issues/7112, probably caused by `esbuild`

**Comment by renhiyama** [comment]
@elisee @nihgwu could you retry with the newer versions of both sucrase & esm.sh?
