### ISSUE TITLE
Failed to import - lodash-es

### ISSUE THREAD

**Issue by jeiea** [esm-dev/esm.sh#267]
## Failing module

- **GitHub**: https://github.com/lodash/lodash
- **npm**: https://www.npmjs.com/package/lodash-es

```js
import { debounce } from "https://esm.sh/lodash-es@4.17.21";
```

## Error message

After running `deno run` I got this:

https://gist.github.com/jeiea/f0d2e176536ee64ce14af4b687e18af5

## Additional info

- **esm.sh version**: v66
- **Deno version**: 1.19.0

**Comment by ije** [comment]
seems it is types problem, try `https://esm.sh/lodash-es@4.17.21?no-check`

**Comment by jeiea** [comment]
Close because I cannot reproduce now with latest deno.
