### ISSUE TITLE
Failed to import - https://esm.sh/@react-three/drei?bundle

### ISSUE THREAD

**Issue by mashaal** [esm-dev/esm.sh#271]
## Failing module

- **GitHub**: [@react-three/drei](https://github.com/pmndrs/drei)
- **npm**: [@react-three/drei](https://www.npmjs.com/package/@react-three/drei)

When using the `bundle` option, it cannot find `react-three/fiber`

https://esm.sh/@react-three/drei?bundle

## Error message

```
/* esm.sh - error */
throw new Error("[esm.sh] " + "esbuild: Could not resolve \"@react-three/fiber\"");
export default null;
```

**Comment by nihgwu** [comment]
Same here but different error, I tried to make [those examples](https://docs.pmnd.rs/react-three-fiber/getting-started/examples) work [here](http://localhost:3000/#JYWwDg9gTgLgBAJQKYEMDGMA0cDecCuAzksgGbZFIDKMKMScAvnKVBCHAORSoacBQoSLFxwAwigB2ANxSEKxAGJQUIBs1bsuAAR7oYAWhgALHkgD0pYACMkUAf1L5JGYBElwAQhAAeACjA2MEIASlx+ODhzczgAFWNgQjgeUjskFwYAd2AAGxy4AHNgaQYiOAATYB4MOHQ0JEIkmAg4EwY1QmMIuDR3QngO4zgAXgJiMj8Q7ui4KiR4fDA4froGUmhW4wZjCBKectrJA-1ihhX6bt7JfrgAbR29pHLsYhgACV27AF0Rsepaeh+UgoHLEKaRK43W4nEoveYAQVcJR+o0oNFWQJBYOmMSo+GshDQUBsDBMiR67EgknS8GamwYPCOdgMOQgEDA2DYANJWzggzgSD2AE8WCo1N1KMpVEg-H5zkhsOUkDlaGFhgA+OB+QYAOjQ+CgjJgOq5dDckh1PjgAGpRgAGHV2gCMIXBURiyBgBo80mASEy2DaxFqPGSSAK+ByKCgmzMOoAVkllUg1JIYEmfIEGsQDsAPAApKgADW6PC9UA8fm6kQAPINq5FcDrm4F2YRGA3IilhjhBh3G43CSCkD2YQwAPxwJ06gCscAAXFP+wO4O4xDlgGgANY9vyCmlqzWvREwU5+ACEY5Cy4H7gAChA8-QoAB5Pa7-dpw-LeYfPZ+GAoHwJBr07VdJAfJ87BffAYA-EovxGI9f0+KBMVBEDGHVMCa2sXwAHEkHYeYoBFaMCkIHtbidbAaKnL5mHMbCVzgOsGmMdEjmjcoAFlVmJEEKVZKAeweNIDknTgdhgMA8y3TgFy4aApAKJBOEY5jGxrcxBk0qYO34RklTQ7oawkGQ5E02tVGsP00wAGWAApjHgJiGxrSAn0c5z4EgQhgFPdwqKdO1aNCqc7QYqIrNY7wrT8gLzSogxpwAJmwcLIo09y4rgBLAskYKdXSuBMqitza3MczZEIbCQiAA), but got `SyntaxError: The requested module '/v67/mmd-parser@1.0.4/es2021/mmd-parser.js' does not provide an export named 'CharsetEncoder'` [error](http://localhost:3000/#JYWwDg9gTgLgBAKjgMyhEcDkABKBTAQwGMYBaGAC3zwHoATfYTIA)

**Comment by ije** [comment]
this happened because drei defines the `@react-three/fiber` in `peerDespendencies`, i will fixed this

**Comment by nihgwu** [comment]
@ije so that's not the same issue as I have? Should I create a new ticket for that, I just updated the links(linked to local env previously)

**Comment by ije** [comment]
@nihgwu yes please
