### ISSUE TITLE
Failed to import - io-ts

### ISSUE THREAD

**Issue by MichaelHirn** [esm-dev/esm.sh#274]
## Failing module

- **GitHub**: https://github.com/gcanti/io-ts
- **npm**: https://www.npmjs.com/package/io-ts

```ts
import { something } from 'https://esm.sh/io-ts@v2.2.16?target=deno'
```

and

```ts
import { something } from 'https://esm.sh/io-ts@v2.2.16?target=deno&deps=fp-ts@2.11.8'
```

## Error message

After running `deno run` I got this:

```
TS2344 [ERROR]: Type 'string' does not satisfy the constraint 'never'.
    at https://cdn.esm.sh/v68/fp-ts@2.2.0/lib/Either~.d.ts:305:155

Found 33 errors.
```

The important part is, that it tries to load `fp-ts` with version `2.2.0`, even though `io-ts` species in `peerDependencies` that at least `fp-ts@2.5.0` should be used. I have no idea where `2.2.0` is coming from (even when `deps=fp-ts@2.11.8` is specified)  and this is probably causing all the TS2344 errors.

## Additional info

Also interesting to note is that, if I try to run with `no-check` flag:

```ts
export type { Branded } from 'https://esm.sh/io-ts@v2.2.16?target=deno&no-check'
```

the errors disappear but the exported types seem to disappear as well and I get this when running `deno run`:

```
error: TS2724 [ERROR]: '"https://esm.sh/io-ts@v2.2.16?target=deno&no-check"' has no exported member named 'Branded'. Did you mean 'brand'?
export type { Branded } from 'https://esm.sh/io-ts@v2.2.16?target=deno&no-check';
```

- **esm.sh version**: 68
- **Deno version**: 1.19.1

Potentially related issues: #168 #273

**Comment by ije** [comment]
when you pass the `no-check` option you can not use `import type` since there is no dts

**Comment by MichaelHirn** [comment]
Thanks for your reply, that makes sense with the `no-check` flag

**Comment by MichaelHirn** [comment]
any ideas where the `fp-ts@2.2.0` is coming from and if I can force it to load a different `fp-ts` version?

**Comment by ije** [comment]
i will look into it, not sure what happened yet

**Comment by ije** [comment]
fixed in v71, i also added the testing here: https://github.com/esm-dev/esm.sh/blob/master/test/deno/io-ts/io-ts.test.ts

**Comment by MichaelHirn** [comment]
Many thanks @ije. This did fix the problem, however `io-ts` remains practically unusable for most, due to another error that pops up. I created a [repo to reproduce](https://github.com/MichaelHirn/esm-issue-274) and will open a separate issue
