### ISSUE TITLE
Issues with V69

### ISSUE THREAD

**Issue by nihgwu** [esm-dev/esm.sh#277]
Sorry I didn't follow the template, as I think it's not an issue for an specific package
After V69, a lot of packages are failed to import, like `@emotion/styled` `react-select` `@mui/material/xxx` `@bytemd/react` and I believe there are more, you can try to reproduce it [here](https://play-react.vercel.app/#JYWwDg9gTgLgBAbzgVwM4FMDKMCGN0A0KGAogGZnoDG8AvnGVBCHAORTo42sBQoksOKhgBPADboAJgyYtWAAXQgIMYBAB2AemHipvHqLDo4ASXwsAvIh5w4wSQC4465CABG6KDbiqYEp8JQwOoA5t6QwTCoAPxOLu6ecAA+zshiYt5onrFCMEGhyanp3qog6HGuHl62pegA+jghEAF5wWG2VMxl6lF1ncg9FQnVPiJGLfntKFBiOYFt3pLMOMFzraE8tDw8nerCcCHoMGZKqHBWABRgjeWpwwCUTgAKssAYADwnIADaALoAfOd-t5KDAqAALC4AA3BMBgYFQDk0mhwYGAADpweowAB3HDozogTQANwADJp1OgcahNAASBDXQ60dEAK1QGih928tnRMHB6HUFwuHFQkD26HuQLgIrFGFZ7MF9y5th5VDwEIuXJ2Gn2ABlggBrc65XSSdE4KHeTpiaAtdDoMRuMTIdAAbhK6AAHjAALSSajQPBqdRxDRuniW7V7eAAWSOOGNOgkZtFOHUlo6EBtUCcISgOBE7tsZA0vtQwAAXrdUCAcOl3d4AGRwADUcEbDgcHhLHGsKrgu3wgzYSVYRZVtagIWCTgAHGBPeOtpHdvsvsaLkhgOY4LQnFvzE517RJRZARdvO8xMBgf33vr1EbwRwyBYENulOjkDN6Lgp0cLAAIjqJ00wNQDpQdID1AgCAjEpKBnGgdBKCgDgoEA29+0QD8QF5bcJC2O9NAfA0sNsd5JGAYlyJVd441wf533MdEIh6VB6DYqJ3k0BicFoii+IElU3BEHCWKyKB6GYz9agaJoiOwnihO5OihJkvDCW6Xp+h6egtIFbjePjWieKomjL00a9gS1Vd4AAVTERNRGTL8xAzOBr2EH0k1uGDKXHSdpxDOBSXHa5JCo0InDCxY3jAMQC1zIJJHHEJUTnBd3RXHV4H1fZLiQRljD3RA4GKoYql3U9AQQK1crgb5cNQIgMGOcxUF+Y0smwPB0E+cw-kKFx0n+C4RrELVbCychKBoIUar7FVDna04rhue5eX5QU2q+VBlV3IhvmK34prsMg4AuABCZrJQ4GBv3UOB6JMm0cCikJ0S+5STO8e7Hsu1T3kc4SNNQdFazAIVcMWi9sLo9cDXQEQ31w9F7HoXDUfMehNGEpVFIozQQe8LktijfYAGFSxWBDnNNdFzI8iKPqcABGAA2LLvFrT0fRxew+ScDmABZSW52wgpnOAcGQGAIGy7Y7LgAAJTh-UQqxfLNfl3s8Dz+WAEJYScEX50XcIIHLVQNBaYAqANQsSjgmLxzcLgDTzCABkcOx1H5IIYHHKjRUSkQnDICQLdsOsjfUH1mqcKhDM8ccWTQVQyBEH1B0MgJrmTn0PBgHF7XUN2PckJgwB9MhgDEfAczgJ1vwuABWBd7kCnAp2l0k4B9TmJfK97WdCuAh4tnLozgAAhOX5aerWXKkdE3AXjlvHdh2vZ90MAq36ANf38NIy9AR4H9MhZYbhgBhoYM4AAQTAKHJTqzMZ+Om5WqOJ4bi6lYHquB8AXDZmdf6UAnpwzotTHotNPDCXeGrPWUBhIUXBAAJn+CrD2iQAByVJUA8Sweg565kyEUXnnCDQcAQ44CdFIN8xVzgWCsGzegGhKbXgdm+TUUo2r-0OOtQ4A8J73FoJQlUYAODElUvDHi1DF5SJeoxRAxVcYT37j9Ri8ilJKNofQxhkhmE3DgP8dhpJOHqG4fbA0fDFqCJuCI4wbZwGSL0fDSk3pPF0U0AY9QZCzLUSQZoFBGskH5XgMVUxTI4B4yBpoOBuBgiINJpsHgQA) I'll have to pin to V68 as a workaround

**Comment by ije** [comment]
thanks, i will rollback then look into it

**Comment by nihgwu** [comment]
https://github.com/nihgwu/react-runner/pull/103 I checked pinning to v68 fixed the issue

**Comment by nihgwu** [comment]
BTW your testing page looks great, sadly it missed all the falling cases 😢

**Comment by ije** [comment]
now it works -> [https://play-react.vercel.app](https://play-react.vercel.app/#JYWwDg9gTgLgBAbzgVwM4FMDKMCGN0A0KGAogGZnoDG8AvnGVBCHAORTo42sBQoksOKhgBPADboAJgyYtWAAXQgIMYBAB2AemHipvHqLDo4ASXwsAvIh5w4wSQC4465CABG6KDbiqYEp8JQwOoA5t6QwTCoAPxOLu6ecAA+zshiYt5onrFCMEGhyanp3qog6HGuHl62pegA+jghEAF5wWG2VMxl6lF1ncg9FQnVPiJGLfntKFBiOYFt3pLMOMFzraE8tDw8nerCcCHoMGZKqHBWABRgjeWpwwCUTgAKssAYADwnIADaALoAfOd-t5KDAqAALC4AA3BMBgYFQDk0mhwYGAADpweowAB3HDozogTQANwADJp1OgcahNAASBDXQ60dEAK1QGih928tnRMHB6HUFwuHFQkD26HuQLgIrFGFZ7MF9y5th5VDwEIuXJ2Gn2ABlggBrc65XSSdE4KHeTpiaAtdDoMRuMTIdAAbhK6AAHjAALSSajQPBqdRxDRuniW7V7eAAWSOOGNOgkZtFOHUlo6EBtUCcISgOBE7tsZA0vtQwAAXrdUCAcOl3d4AGRwADUcEbDgcHhLHGsKrgu3wgzYSVYRZVtagIWCTgAHGBPeOtpHdvsvsaLkhgOY4LQnFvzE517RJRZARdvO8xMBgf33vr1EbwRwyBYENulOjkDN6Lgp0cLAAIjqJ00wNQDpQdID1AgCAjEpKBnGgdBKCgDgoEA29+0QD8QF5bcJC2O9NAfA0sNsd5JGAYlyJVd441wf533MdEIh6VB6DYqJ3k0BicFoii+IElU3BEHCWKyKB6GYz9agaJoiOwnihO5OihJkvDCW6Xp+h6egtIFbjePjWieKomjL00a9gS1Vd4AAVTERNRGTL8xAzOBr2EH0k1uGDKXHSdpxDOBSXHa5JCo0InDCxY3jAMQC1zIJJHHEJUTnBd3RXHV4H1fZLiQRljD3RA4GKoYql3U9AQQK1crgb5cNQIgMGOcxUF+Y0smwPB0E+cw-kKFx0n+C4RrELVbCychKBoIUar7FVDna04rhue5eX5QU2q+VBlV3IhvmK34prsMg4AuABCZrJQ4GBv3UOB6JMm0cCikJ0S+5STO8e7Hsu1T3kc4SNNQdFazAIVcMWi9sLo9cDXQEQ31w9F7HoXDUfMehNGEpVFIozQQe8LktijfYAGFSxWBDnNNdFzI8iKPqcABGAA2LLvFrT0fRxew+ScDmABZSW52wgpnOAcGQGAIGy7Y7LgAAJTh-UQqxfLNfl3s8Dz+WAEJYScEX50XcIIHLVQNBaYAqANQsSjgmLxzcLgDTzCABkcOx1H5IIYHHKjRUSkQnDICQLdsOsjfUH1mqcKhDM8ccWTQVQyBEH1B0MgJrmTn0PBgHF7XUN2PckJgwB9MhgDEfAczgJ1vwuABWBd7kCnAp2l0k4B9TmJfK97WdCuAh4tnLozgAAhOX5aerWXKkdE3AXjlvHdh2vZ90MAq36ANf38NIy9AR4H9MhZYbhgBhoYM4AAQTAKHJTqzMZ+Om5WqOJ4bi6lYHquB8AXDZmdf6UAnpwzotTHotNPDCXeGrPWUBhIUXBAAJn+CrD2iQAByVJUA8Sweg565kyEUXnnCDQcAQ44CdFIN8xVzgWCsGzegGhKbXgdm+TUUo2r-0OOtQ4A8J73FoJQlUYAODElUvDHi1DF5SJeoxRAxVcYT37j9Ri8ilJKNofQxhkhmE3DgP8dhpJOHqG4fbA0fDFqCJuCI4wbZwGSL0fDSk3pPF0U0AY9QZCzLUSQZoFBGskH5XgMVUxTI4B4yBpoOBuBgiINJpsHgQA)
