### ISSUE TITLE
Failed to import - rxjs

### ISSUE THREAD

**Issue by marcushultman** [esm-dev/esm.sh#278]
## Failing module

- **GitHub**: https://github.com/ReactiveX/rxjs
- **npm**: https://www.npmjs.com/package/rxjs

```js
import 'https://esm.sh/rxjs@7.5.5'
```

## Error message

After running `deno run` I got this:

```
error: Uncaught SyntaxError: Detected cycle while resolving name 'ConnectableObservable' in '/v69/rxjs@7.5.5/deno/internal/*.js'
    at <anonymous> (https://cdn.esm.sh/v69/rxjs@7.5.5/deno/internal/observable/ConnectableObservable.js:4:6449)
```

## Additional info

- **esm.sh version**: 69
- **Deno version**: 1.19.0

Also fails in browser

**Comment by ggoodman** [comment]
Looks like it might be a short-coming of the logic here that seems to assume that remapped wildcard submodule prefixes will match: https://github.com/esm-dev/esm.sh/blob/5ae08198958ce8cba57c9da433ead4b2b79addfc/server/module.go#L105-L131

If you look at the `packge.json` for `rxjs@7.5.5`, starting on line 60, I think it explains why the linked code might not be working as expected: https://unpkg.com/browse/rxjs@7.5.5/package.json

**Comment by ije** [comment]
@ggoodman thanks for the details, i am working on it

**Comment by ije** [comment]
fixed in https://github.com/esm-dev/esm.sh/commit/1dabda78e47ade5b19498cd81a16ce32785cac91, will release later

**Comment by ije** [comment]
i also added the rxjs testing, seem works fine in browser: https://esm.sh/?test

**Comment by marcushultman** [comment]
@ije Thank you - it works in Deno too.
