### ISSUE TITLE
Failed to import - @angular/common@11/http

### ISSUE THREAD

**Issue by ggoodman** [esm-dev/esm.sh#280]
## Failing module

- **GitHub**: https://github.com/angular/angular/tree/master/packages/common
- **npm**: npm.im/@angular/common

```js
import { HttpEventType } from 'https://esm.sh/@angular/common@11/http'
```

## Error message

After `onload` I got this:

```
Detected cycle while resolving name 'Observable' in '/v69/rxjs@7.5.5/es2021/internal/*.js'
```

## Additional info

- **esm.sh version**: Public esm.sh
- **Browser version**: Chrome 99

**Comment by ije** [comment]
same as #278 , i will look into it

**Comment by ggoodman** [comment]
@ije good catch. Would you like to close this one?

**Comment by ije** [comment]
please try **v70**, should be fixed

**Comment by ggoodman** [comment]
❤️  ty.
