### ISSUE TITLE
Proposal: pin react and react-dom

### ISSUE THREAD

**Issue by nihgwu** [esm-dev/esm.sh#283]
esm.sh updates frequently and every time it will break [my app](https://play-react.vercel.app/) and got [this error](https://reactjs.org/docs/error-decoder.html?invariant=321), because of cache, some packages will resolve to old build, which will lead to multi versions of React, and that will break the rule of React Hooks, so to solve this problem I have to pin the version from my side, but I think the build for react is already super stable, can we just solve it to `export * from "https://cdn.esm.sh/stable/react@17.0.2/es2021/react.js";` instead of `export * from "https://cdn.esm.sh/v71/react@17.0.2/es2021/react.js";`

Or we always point latest version as `https://cdn.esm.sh/edge/module` for all packages, if someone want to pin to a previous version, they will get `https://cdn.esm.sh/vXX/module`

**Comment by nihgwu** [comment]
A problem with pinning version is that I got this error `Uncaught SyntaxError: The requested module 'https://esm.sh/react?pin=v71/jsx-runtime' does not provide an export named 'jsx'` https://github.com/nihgwu/react-runner/pull/105

**Comment by ije** [comment]
yes, this makes a lot of sense, but need to be very careful, how to ensure the 'stable' is actual stable

**Comment by ije** [comment]
> A problem with pinning version is that I got this error `Uncaught SyntaxError: The requested module 'https://esm.sh/react?pin=v71/jsx-runtime' does not provide an export named 'jsx'` [nihgwu/react-runner#105](https://github.com/nihgwu/react-runner/pull/105), OK to be fair, it will only happen if I alias `react` to remote version, I'll switch to classic runtime

i will improve it

**Comment by ije** [comment]
https://github.com/esm-dev/esm.sh/commit/f2cfe998dd01fbf743a0b16925398e7b8b10f31f now support `jsx-runtime` with query:

<img width="596" alt="Screen Shot 2022-03-21 at 12 00 59" src="https://user-images.githubusercontent.com/2883484/159203696-87d2e01f-dce7-4080-a39e-c5b1ab014477.png">

**Comment by nihgwu** [comment]
> yes, this makes a lot of sense, but need to be very careful, how to ensure the 'stable' is actual stable

So in the later example I changed to `edge`, so we always point to latest build

**Comment by nihgwu** [comment]
@ije I have new problem even I locked react version to 17.0.2, [here is the demo](https://play-react.vercel.app/#JYWwDg9gTgLgBAJQKYEMDG8BmUIjgcilQ3wG4AoUSWOAbzgGcYBPAGyQBMAaOAayWbYUIJAzgBfONlwEAAk2Aw0AC1EB6IuhhlK4aPHoA3YBHYweAI1bpeAQR4gUAV0NIJUnHnyyoKDsAAPAFonYDU0U2gGHSp9OjgAYVVDHAA7ABEIAHdUgEkI1PdpLx8-QJCwzQwg4ALoiliaACo4FDFbNAiofwhUgAUoUEVgVw8Zb19-YNCNYhgg9C6e1J1yOvgGVmAOJEycuABePgEhEQYAClpyODGQAC541WAAc2UYB4AGCS5ruBgIB70J6vd4EQwoKDnIJBSblRbQZZBAowJCpebAt4ASnw33I4kxFDWvSYjC2OwAqmBDsdBL4zpdfsVAXAMaD8ODIdDYcF4d0TKkkb0UWigqzsbibv9mazPrj8YT1nAAMosdgcDpLfnUphsTjnDUI-kDIYwEZIAB0CAgEHMdF+FgRSCgCDKTgYDwAbD8blltjBlA8AMwfD7euAWGzPHBOVIcBKRKAPRwuC3J1xe+0QAJK5R+bIPAAGXwATGAAnAAIwfMtwAAktCsNls5sbaDsABZxAWfvLyETUiSVbqOLkUXgjjq1frOobesaQMNXObR0gQDwrjcIK4oJhWPmCMptjsVmHHFBnsBUgAVCBgB4Vn6-fAAMjumGAUCYSMPrA4+EBvw3GeF7XrenxhjcDrdE6N5gAAMkgmAwC6-hug87YQeGjpQLBCAvG8KHAGhcAYb84iPjcL53NYX4qMAv7-naNyQdhABCNr-CACFIYRxGkcxWHQVA7EwJxeEgrx7okWG5F9pRr6YBAaBukEvr+pejEbsxkAMMMvQPIQSDWKarj4JhABeuSxkgAT3phDrZrmHD7kWcBfCWNb1mmqbOK4FbFl2Mk9gSfaKkOaoABKoDsUDaqqeoGnyc6DAuJkWlFfhOuuvwoKwrAGTGDBINoYb+AwYDWMwBm7jZZl4iF-aDvFHBXoMzzPE6cXDtOmrJSaZrmq1LwdVA2U3Ll+UEIVxV1TcilogAYsI9FVQQl6qIMJX2pG0axvGe6JgQMC+AOYAQqiW03GdHD+KkzwGSW1YBLNLJIPhoLtgArGGNW2ZWpXAOVlXVewz1hrlLx5GOUn4GgF1Oi9ABWbqmpgzDxmiF0GeV6BIEEFjFVkSCoi980wEqwDmUg97fb8WypEgUXvXZvwRAdDzGKYxXmpzZgVg+maOXmWSFl8FY1l8Xm+T5KYeoFT7PgA2hwKAwCgQRMKrSAHAARGge5FRwOsALqaeGO0QDGcYJgZWSHiiOKyfJyuq+rmsorrt6oibZsRm2UaW3tNsEHbihII7YZUcoW4I8yfu8AHVv7dASbS+a3nFnKDVhc1GPCvAE7NT1s79Cli4WnnF1jXAMc7nuIsHkeJM-UKFNUzTYZsyncDeen0v82G8eJ0H7M92nGcUQQSsq2rGtqx7Ote6kPsAQJKCpKAqv8oW9abNsuzZKkkjBh8IBiMpFi1PjSDmcATrnB85oABwAOw8KGbnmhWgY8BWmJSNALIEIOAMG7GRSO09XZzy1rrfWEBDYryYsxdem9TT6TgAWXeZIkCUmPiGM+cAL5XwJrfe+j9X7v3fl-H+lZ-6KSgEA7ooCgr1QVMSeA4VOCVzRFeGyBdGBF3wP4QwZkkHXVuvdAgFZPo1mLE9OqvZGocNzskNIXUpxJCQCkXoew8gFGrl3Q6vNubGJgFWMMx1166TQakAyliBz0LwCfAhRC0DX1IZCchb83JUO-r-bEkcXaz3dtrJexs4DPjNvYhgjiDI4Hnkgc4FYn4fB2M8cUslFFqDUHAAAogEagMAGDkBsoUwh7C4CJWWNSTh6oZxJVSBQUpcRFRVP5CuccypmodKaQUlpFS2m9CGu1TqRxkBaHNPQxhHBkCYHOJcQhP4OBEFSDwc06ywA4DAGIciACGHAM4LM-+BwAB8cBzi-AADy1IyjFE5gE4DXOasMkadB1nmk2beBgkgiCYAOLQKZByZmIXEPcgSNxaB0V-Cs8QDybhPOHJo7RhQITAHVoeG6qI4BqDBcxS5ahakvKdLi-FNzorEvIJiEKzSaCtPqcsbh-DxkYEmYA4Bsz5n0Chcs1EayNlbJ2TwQF0FgWYGOWci58LamMrefyr5PzEL-OFTsUVoKHkIrVIy3hAQYAnMhUsmFpLc5Cgutq3VVyCXGsxmie5VLCTZLgAATUtrFFAYAwDvJKX02lAz6X8nSKuCA1JzjivOVcwZhQWBgG1jrXSd12A6zgDsTAzhWAwAAGq5ScDGsOIAggVkTWzaw2zgBWCQLi+FEaOlwHBKwbNutc35p1hWvFEaiVQBObkMQihWidFELpMtAB+fFba2ojRbZWv1vRGUnMdaIc0cBRytA4BtUQfwg3+jcAAdVsLkIItgEC7qTaISGcAzqiSdKkc0I6p2pBneqtQVaxz3PVU+1cNas05rHEEYsza4WPNHcNYlXa4A9sKs1Ydj7b3tonQB2997wXMTnQwBdo58BiHA8OcMzBj0pqcGmngF5jB3TgMwS2HhibOTwLXP4qg4B7ggLwVosYpDE1YOaf9N7ep3pNTah9b6QAvoEpcgTH661ftXEEQMf7EMieg2O4lCR16gfgATZjqDOCQcAyMjtnGI0IcQ060QABCJ15G0DKZQY4FEtG3ARrgGpZQiQlRKhrrFAAUigcESo0CDDADADjsmoPcYM-C4LJcOkkvCw021hIaXwGTam+AEaA0gAgBQIAA)

I guess it's some deep dependency is referring to a wild version, the [321 error](https://reactjs.org/docs/error-decoder.html?invariant=321) is driving me crazy, I'm going to use servicer worker to proxy it to local version instead

**Comment by ije** [comment]
since react upgrade to 18, i guess some libraries was built with the latest react version, you need add `deps=react@17.0.2` when import those library

**Comment by nihgwu** [comment]
@ije that's what I did, you can check the outgoing requests, all appended with `deps=react@17.0.2`, so that's why I suspect the wild version is from a deep dependency

**Comment by ije** [comment]
i will look into it！

**Comment by nihgwu** [comment]
@ije Now I've locked the react version via Service Worker, but now I got a new issue, esm.sh version mismatch, I've locked to v74, but seems internal packages got resolved to latest version
<img width="700" alt="image" src="https://user-images.githubusercontent.com/2595058/162314468-a8495543-fb79-4326-a452-4083f77bb322.png">

**Comment by ije** [comment]
i believe this has been done
