### ISSUE TITLE
Failed to import - ipfs-core-types

### ISSUE THREAD

**Issue by talentlessguy** [esm-dev/esm.sh#284]
## Failing module

- **GitHub**: https://github.com/ipfs/js-ipfs/tree/master/packages/ipfs-core-types
- **npm**: https://www.npmjs.com/package/ipfs-core-types

```js
import type { IPFS } from 'https://esm.sh/ipfs-core-types'
```

## Error message

After `onload` I got this:

```
/* esm.sh - error */
throw new Error("[esm.sh] " + "parseCJSModuleExports: Can't resolve 'ipfs-core-types' in '/tmp/esm-build-3db5978441a668bf6d7f69f5749679b8bd35af84-18193627'");
export default null;
```

## Additional info

- **esm.sh version**: 71
- **Browser version**:  Waterfox G4 (Firefox 91)

**Comment by ije** [comment]
seems it only provides the types in package JSON, I will fix it
