### ISSUE TITLE
Failed to import - @react-three/fiber

### ISSUE THREAD

**Issue by Starcounter-Jack** [esm-dev/esm.sh#295]
Esm.sh resolves the incorrect version. If there is a semver in a ```dependencies``` or ```peerDependencies``` entry they should triumph over any developer dependencies in ```devDependencies```. 

https://github.com/pmndrs/react-three-fiber/issues/2171

**Comment by ije** [comment]
https://esm.sh/zustand?deps=react@18
https://esm.sh/@react-three/fiber?deps=react@18

you need to specify the react dep by `?deps` query

**Comment by Starcounter-Jack** [comment]
That will not work. The problem appears when importing ```https://esm.sh/@react-three-fiber```. It will resolve React to version 18 and then refer to ```Zustand```. Zustand allows for semver ```>=16.8```` so there should not be a problem. However, esm.sh will respect the ```devDependency``` which is incorrect.

This results in both React 17 and React 18 being loaded which is not the behaviour of other bundlers. I believe the problem is that ```devDependencies``` has a say when it should not.

**Comment by Starcounter-Jack** [comment]
@lje

Zustand is imported by @react-three/fiber. When setting ```?deps``` for the root module, it is not carried down to its subdependencies. This causes @react-three/fiber to import two versions of React.

Follow https://esm.sh/@react-three/fiber?deps=react@18 and you will find that it will try to mix imports of both React 17 and React 18 causing runtime bugs.

**Comment by Starcounter-Jack** [comment]
@lje

I tried to make the author accept a pull request aligning the devDependencies and dependencies but this is their conclusion:

> I have no problem resolving this here but this is pretty clearly an issue with esm.sh (from IMO a poor design decision). I would prefer to resolve this over there rather than go through the entire ecosystem.
