### ISSUE TITLE
Failed to import - react-earthstar

### ISSUE THREAD

**Issue by mashaal** [esm-dev/esm.sh#308]
## Failing module

- **GitHub**: https://github.com/earthstar-project/react-earthstar
- **npm**: https://www.npmjs.com/package/react-earthstar

```js
import { Peer } from "https://esm.sh/react-earthstar";
```

## Error message

After running `deno run` I got this:

```
error: Uncaught SyntaxError: The requested module '/v69/concurrency-friends@5.2.0/deno/concurrency-friends.js' does not provide an export named 'Lock'
    at <anonymous> (https://cdn.esm.sh/v69/earthstar@8.2.4/deno/earthstar.js:2:6968)
```

## Additional info

- **esm.sh version**: 77
- **Deno version**: 1.21.0

**Comment by mashaal** [comment]
`earthstar@8.2.4` is a peer dependency of this library https://github.com/earthstar-project/react-earthstar/blob/master/package.json#L45

**Comment by ije** [comment]
<img width="481" alt="Screenshot 2023-10-03 at 18 20 21" src="https://github.com/esm-dev/esm.sh/assets/2883484/0945cc54-7b0d-4d6b-8ee4-e49f723d7666">
just works 😜hhh
