### ISSUE TITLE
Allow cross origin requests

### ISSUE THREAD

**Issue by Janpot** [esm-dev/esm.sh#329]
Would it be possible to set the access control header to allow all origins so that modules can be fetched from javascript?

```
Access-Control-Allow-Origin: *
```

**Comment by jimisaacs** [comment]
<img width="1525" alt="Screen Shot 2022-05-15 at 9 55 07 PM" src="https://user-images.githubusercontent.com/299156/168507089-7df8ac9a-992a-4ac7-9709-5c39ec940936.png">

**Comment by jimisaacs** [comment]
What is the url of the page in chrome you are fetching lodash on? I'm not entirely sure of the implementation since it's in another library called rex, but it might only appear when an actual cross origin request is made.

**Comment by Janpot** [comment]
Ah, just noticed it only sends the header on `fetch` requests. Encountered this while testing `HEAD` requests and didn't retry this on `GET`

**Comment by tarnishablec** [comment]
> Ah, just noticed it only sends the header on `fetch` requests. Encountered this while testing `HEAD` requests and didn't retry this on `GET`

I met the same problem as yours, when `fetching` content from url `localhost:10089`
