### ISSUE TITLE
types across packages are different instances

### ISSUE THREAD

**Issue by sachinraja** [esm-dev/esm.sh#333]
Noticing an issue after #102. If I have an files like this:
```ts
// one@1.0.0/index.ts
export declare const marker: unique symbol
```

```ts
// two@1.0.0/index.ts
import { marker } from 'https://esm.sh/one@1.0.0'
export interface Thing {
  marker: typeof marker
}
```

```ts
import { Thing } from 'https://esm.sh/two@1.0.0?deps=one@1.0.0'
import { marker } from 'https://esm.sh/one@1.0.0'

type Eval = Thing['marker'] extends typeof marker ? true : false // false
```

I would expect `Eval` to be true in this case. This can break libraries that use peerDependencies and have a `Symbol` type. I believe this is due to the type files not resolving to the same build.

**Comment by ije** [comment]
@sachinraja  thanks, can you please provide the real case i can test?

**Comment by sachinraja** [comment]
here's the repro @ije https://github.com/sachinraja/esm.sh-issue-333-repro

**Comment by sachinraja** [comment]
I think this can't be solved easily. My current solution is to alias the dependencies so they all import from the same URL:
```
https://esm.sh/trpc-swr@0.1.0?alias=swr:https%3A%2F%2Fesm.sh%2Fswr%401.3.0%3Fdeps%3Dreact%4018,@trpc/server:https%3A%2F%2Fesm.sh%2F%40trpc%2Fserver%4010.0.0-alpha.22,@trpc/client:https%3A%2F%2Fesm.sh%2F%40trpc%2Fclient%4010.0.0-alpha.22&deps=react@18
```

**Comment by ije** [comment]
> I think this can't be solved easily. My current solution is to alias the dependencies so they all import from the same URL:
> 
> ```
> https://esm.sh/trpc-swr@0.1.0?alias=swr:https%3A%2F%2Fesm.sh%2Fswr%401.3.0%3Fdeps%3Dreact%4018,@trpc/server:https%3A%2F%2Fesm.sh%2F%40trpc%2Fserver%4010.0.0-alpha.22,@trpc/client:https%3A%2F%2Fesm.sh%2F%40trpc%2Fclient%4010.0.0-alpha.22&deps=react@18
> ```
 
omg, i just fixed it for https://github.com/sachinraja/esm.sh-issue-333-repro, but this is going to be kick-ass LOL

**Comment by sachinraja** [comment]
Lol yeah it's crazy. Nested peer dependencies.
