### ISSUE TITLE
Support esbuild --keep-names to prevent Ccass/function names erasing

### ISSUE THREAD

**Issue by inca** [esm-dev/esm.sh#335]
As stated in https://github.com/evanw/esbuild/issues/931, https://github.com/evanw/esbuild/issues/510 and elsewhere, sometimes it is undesirable to have class names erased.

Current behaviour of esm.sh seems to be erasing the class/function names, e.g. `export class Price { ... }` would be transpiled into `var t = class {}; export { t as Price }` which makes `mahPrice.constructor.name` return `"t"` instead of `"Price"`.

Esbuild supports [--keep-names](https://esbuild.github.io/api/#keep-names) which solves this problem; however, there is currently no way of enabling it with esm.sh.

**Comment by inca** [comment]
Thank you! You folks are the best ❤️

**Comment by ije** [comment]
thanks for suggestion
