### ISSUE TITLE
Occasional 403 errors when importing from esm.sh 

### ISSUE THREAD

**Issue by lucacasonato** [esm-dev/esm.sh#337]
https://github.com/lucacasonato/fresh/runs/6639123029?check_suite_focus=true
https://github.com/lucacasonato/fresh/runs/6639108924?check_suite_focus=true

@ije You said this may be related to some WAF blocking by Cloudflare.

Maybe you need to update this Level 7 DDOS protection option to "Essentially Off"?

![image](https://user-images.githubusercontent.com/7829205/170842453-d492eb16-faf8-4929-9319-86d87b9527ad.png)

**Comment by ije** [comment]
Essentially Off now, thanks for suggestion

**Comment by ije** [comment]
<img width="1103" alt="Screen Shot 2022-05-29 at 11 28 51" src="https://user-images.githubusercontent.com/2883484/170850752-769685e1-a6bd-45b5-bed9-c8b98baf493f.png">
