### ISSUE TITLE
The unit test success rate for esm.sh is lower after refactoring

### ISSUE THREAD

**Issue by zhoukekestar** [esm-dev/esm.sh#44]
Hey, @ije nice try for esm.sh 's refactoring to transform `node eval` to `ast parser`. 
Better for some package like: `/@lume/element`, `/@lume/variable`. 
But bad for some packages too, here is the details:

[Online Test for current esm.sh](https://g.alicdn.com/code/npm/@ali/esm-unit-test/0.0.6/detail.html?bases=https://esm.sh) : 66.23%
![Xnip2021-04-02_14-55-33](https://user-images.githubusercontent.com/7157346/113389978-7ec9eb00-93c3-11eb-973f-fd7c0f6ca7aa.jpg)

Online Test for (esm.alibaba-inc.com) which is based on old version: 89.61%
![Xnip2021-04-02_14-57-05](https://user-images.githubusercontent.com/7157346/113390139-b9cc1e80-93c3-11eb-99d4-a472a629c066.jpg)

**Comment by zhoukekestar** [comment]
Maybe we need `node eval` and `ast parser` both for named export & packaging.

**Comment by ije** [comment]
@zhoukekestar i think the AST parser is ok, guess the main problem is that i updated esbuild to **0.11**, the external module resolver needs to be updated too becuase i saw a lot **require is not defined** errors, i will fix it asap, thanks 🙏
btw the testing looks amazing, can you please share it for me?

**Comment by zhoukekestar** [comment]
Thanks for your hard working, the unit test is  very simple which is written in native JavaScript. I will open-source it if you need this so that we can deliver esm.sh with confidence.

**Comment by ije** [comment]
<img width="1112" alt="Screenshot 2021-04-04 at 00 01 29" src="https://user-images.githubusercontent.com/2883484/113484034-ea51ac80-94d8-11eb-9b45-ec1948bd1e5f.png">
i added a simple testing page, do you have interest in improving it? thanks

**Comment by ije** [comment]
you can update it in here: https://github.com/postui/esm.sh/blob/master/embed/assets/testing.js

**Comment by ije** [comment]
run the testing in `http://localhost/?test`

**Comment by ije** [comment]
btw, i added a build queue instead of mutex lock that can use the multiple CPU units. in my computer(i7 8 cores) it got almost 7x build speed faster!

**Comment by zhoukekestar** [comment]
Great, that's awesome!

**Comment by zhoukekestar** [comment]
We just need check `variable` exist or not in most case. If esm.sh import works and has no-undefined variable, it's always works for me.

**Comment by zhoukekestar** [comment]
Some hack details maybe useful for you to pass all unit test:
* named export solution PRed by @wleonardo 
* some npm packaged by webpack
* some npm use browser entry directly. For example: https://unpkg.com/browse/yargs@16.2.0/browser.mjs
* some necessary polyfill like: @jspm/core & entends it. For example: https://github.com/jspm/jspm-core/issues/13
* some named export like `arguments` seems NO-SOLUTION for it, and may be the only way is use `is.default.arguments`. For example: https://github.com/postui/esm.sh/issues/28
