### ISSUE TITLE
Failed to import `centerCrop` of `react-image-crop`

### ISSUE THREAD

**Issue by yykamei** [esm-dev/esm.sh#458]
## Failing module

- **GitHub**: https://github.com/DominicTobias/react-image-crop
- **npm**: https://www.npmjs.com/package/react-image-crop

```js
import { centerCrop } from 'https://esm.sh/v99/react-image-crop@10.0.9'
```

## Error message

After `onload` I got this:

```
Uncaught SyntaxError: The requested module 'https://esm.sh/v99/react-image-crop@10.0.9' does not provide an export named 'centerCrop' (at my-module.js:2:10)
```

## Additional info

- **esm.sh version**: v99
- **Browser version**: Version 108.0.5359.94

**Comment by ije** [comment]
cool!
