### ISSUE TITLE
Unnecessary /* fake(empty) types */ for nested imports; here: missing tRPC types

### ISSUE THREAD

**Issue by ccssmnn** [esm-dev/esm.sh#495]
The `@trpc/client` package imports successfully, but the loaded types lack some information that is loaded from a subfolder of `@trpc/server`. These types missing lead to lack of type inference, killing the main benefit from the whole package, see the code below. This bug might affect other libraries relying on similar imports for their exported types.

You can use the below code to reproduce this, following the type definition of `trpc.getCount.query` in the client file, where the count variable incorrectly gets inferred as `any`.

`@trpc/client` is importing types from `@trpc/server` as well as `@trpc/server/shared` [here](https://github.com/trpc/trpc/blob/6d3a302dca9cf691082108fe2bfb0a9b62e1aa28/packages/client/src/createTRPCClientProxy.ts#L18).

While the former get resolved correctly to `'https://esm.sh/v102/@trpc/server@10.8.1/dist/index.d.ts'`, the latter resolves to `https://esm.sh/v102/@trpc/server@10.8.1/shared/dist/index.d.ts`, with `shared` and `dist` in the incorrect order. As they are not found, the modules are replaced as `/* fake(empty) types */`.

Reproduction steps

```typescript
// server.ts
import { initTRPC } from "https://esm.sh/@trpc/server@10.8.1";
import { z } from "https://esm.sh/zod@3.20.2";

const t = initTRPC.create();

let count = 0;

const appRouter = t.router({
  getCount: t.procedure.input(() => {}).query(() => {
    return { count };
  }),
  increment: t.procedure.input(z.object({ amount: z.number().optional() }))
    .mutation((req) => {
      count += req.input.amount ?? 1;
    }),
});

export type AppRouter = typeof appRouter;

// client.ts
import {
  createTRPCProxyClient,
  httpBatchLink,
} from "https://esm.sh/@trpc/client@10.8.1";
import type { AppRouter } from "./server.ts";

export const trpc = createTRPCProxyClient<AppRouter>({
  links: [httpBatchLink({ url: "/api/trpc" })],
});

const res = await trpc.getCount.query();
export const count = res.count; // ⛔️ this has type any, but should have type number
```

**Comment by ije** [comment]
v104 removes the fake types, just returns 404 instead. Can you pls try again? thanks

**Comment by ccssmnn** [comment]
Thanks for the update. Like you said, the types are still missing because imports from directories inside modules are resolved incorrectly.

- `@trpc/client` imports types from `@trpc/server/shared`
- The import is resolved to`'https://esm.sh/v104/@trpc/server@10.8.1/shared/dist/index.d.ts';` but should be`'https://esm.sh/v104/@trpc/server@10.8.1/dist/shared/index.d.ts';`
- The nested folder should be appended after, not before the `/dist`
- missing types kill the benefits of the whole package
- This bug might break packages, that import code from other packages this way

**Comment by ije** [comment]
the wrong dts path may have been cached, i will release v105 soon

**Comment by ccssmnn** [comment]
Just checking in again. With v120 & the latest tRPC version, the types inferred correctly. Thank you!
