### ISSUE TITLE
Failed to import - es-module-lexer

### ISSUE THREAD

**Issue by ctemplin** [esm-dev/esm.sh#507]
## Failing module
es-module-lexer

## Error message

After running `deno run` I got this:

```
Run deno run -A ./build.js
  deno run -A ./build.js
  shell: /usr/bin/bash -e {0}
Download https://deno.land/x/ultra@v2.1.7/build.ts
...
Download https://deno.land/std@0.163.0/io/types.d.ts
error: Import 'https://esm.sh/es-module-lexer@1.0.3/es-module-lexer.js' failed: 500 Internal Server Error
    at https://deno.land/x/mesozoic@v1.2.6/lib/deps.ts:9:8
Error: Process completed with exit code 1.
```

## Additional info

- **esm.sh version**: ?
- **Deno version**: 1.25.1 via Github action

Thank you!

**Comment by ije** [comment]
the import url should be `https://esm.sh/es-module-lexer@1.0.3` or `https://esm.sh/v104/es-module-lexer@1.0.3/deno/es-module-lexer.js`

**Comment by ije** [comment]
plase import the module from "https://esm.sh/es-module-lexer@1.0.3"
