### ISSUE TITLE
Failed to import non-js files of private package

### ISSUE THREAD

**Issue by Justinidlerz** [esm-dev/esm.sh#515]
## Failing module
 All non-js files of private packages.

I found some logic about getting all non-js files from upstream of the unpkg CDN.
![image](https://user-images.githubusercontent.com/7475347/216896747-fc24aef3-727d-4253-b152-fa59ab67a08d.png)

Due to support the private package serves logic but the upstream is not, we cannot get any non-js files of private packages.
I don't want to serve another supporting private package CDN server for that. 

I have an idea: we cache & serve all files of private packages.

@ije Do you have some ideas for this problem? Wanted to get your thoughts on this first before doing a PR if there's interest.

**Comment by ije** [comment]
> we cache & serve all files of private packages.
sounds great to me, we need to download and cache non-js files of a private package via npm, you can use the `yarnAdd` func

**Comment by ije** [comment]
now i think we should implement this, since the unpkg/jsdelivr don't support private registry, or if them are down the service will be affected
