### ISSUE TITLE
esbuild: Could not resolve error for codemirror when using `exports`

### ISSUE THREAD

**Issue by not-my-profile** [esm-dev/esm.sh#521]
https://esm.sh/codemirror@6.0.1?exports=minimalSetup returns the following:

```js
/* esm.sh - error */
throw new Error("[esm.sh] " + "esbuild: Could not resolve \"codemirror/dist/index.js\"");
export default null;
```

The code for the package [is here](https://github.com/codemirror/basic-setup/tree/6.0.1).

**Comment by tachibana-shin** [comment]
Same error message with https://esm.sh/fcanvas@1.1.0-rc.39?exports=ref,watch,Circle

**Comment by ije** [comment]
works in v112

**Comment by not-my-profile** [comment]
Awesome, thanks!
