### ISSUE TITLE
Failed to import - JSONStream

### ISSUE THREAD

**Issue by talentlessguy** [esm-dev/esm.sh#541]
## Failing module

- **GitHub**: https://github.com/dominictarr/JSONStream
- **npm**: https://www.npmjs.com/package/JSONStream

```js
import JSONStream from 'https://esm.sh/v111/JSONStream@1.3.5/deno/JSONStream.js'
```

## Error message

After running `deno run` I got this:

```
Invalid package name 'JSONStream'
```

## Additional info

- **esm.sh version**: 111
- **Deno version**: 1.31.1

**Comment by ije** [comment]
fixed, thanks!
