### ISSUE TITLE
Failed to import - ipfs-utils/src/http.js

### ISSUE THREAD

**Issue by talentlessguy** [esm-dev/esm.sh#553]
## Failing module

- **GitHub**: https://github.com/ipfs/js-ipfs-utils/blob/master/src/http.js
- **npm**: http://npmjs.com/ipfs-utils

```js
import HTTP from 'https://esm.sh/ipfs-utils/src/http.js'
```

## Error message

After running `deno run` I got this:

```
Uncaught TypeError: __0$.bind is not a function
    at https://esm.sh/v111/ipfs-utils@9.0.14/deno/src/http.js:2:1638
    at https://esm.sh/v111/ipfs-utils@9.0.14/deno/src/http.js:2:1110
    at https://esm.sh/v111/ipfs-utils@9.0.14/deno/src/http.js:2:4537
```

I found a `.bind` [here](https://github.com/ipfs/js-ipfs-utils/blob/6bb160a69383bd8138f3528f8427d543c42e81e4/src/http.js#L271) but I'm not sure if it's related to the bug

## Additional info

- **esm.sh version**: 111
- **Deno version**: 1.31.3

**Comment by ije** [comment]
thanks, i will look into it

**Comment by ije** [comment]
i think is a bug of cjs exports resolving at https://github.com/ipfs/js-ipfs-utils/blob/6bb160a69383bd8138f3528f8427d543c42e81e4/src/http.js#L6

**Comment by talentlessguy** [comment]
@ije is it possible for esm.sh to resolve dynamic requires as `await import()`?

**Comment by talentlessguy** [comment]
it's working, thank you very much!
