### ISSUE TITLE
Failed to import - https://esm.sh/vue and https://esm.sh/vue/server-renderer

### ISSUE THREAD

**Issue by Antonio476587** [esm-dev/esm.sh#555]
## Failing module

- **GitHub**:  https://github.com/vuejs/
- **npm**:  https://www.npmjs.com/package/vue

```js
import { createSSRApp, createApp } from 'https://esm.sh/vue'
import { renderToString } from 'https://esm.sh/vue/server-renderer'
```

### The following problems doesn't appear with `npm:vue`

When I try to mount the app like

```js
app.mount("#app")
```

it doesn't mount the app, and when I try to use de `renderToString` function from https://esm.sh/vue@3.2.47/server-renderer it doesn't return the desired output, instead it returns a html comment tag.

## Additional info

- **esm.sh version**: v111
- **Deno version**: 
deno 1.31.3 (release, x86_64-unknown-linux-gnu)
v8 11.0.226.19
typescript 4.9.4

**Comment by ije** [comment]
you can not use DOM in Deno, use it in browser instead

**Comment by Antonio476587** [comment]
> you can not use DOM in Deno, use it in browser instead

Yes, I know that.

I am using SSR with Deno, the function `renderToString`works fine when it's imported from npm, but when it's imported from esm It doesn't bring the expected functionality

And the client should hydrate the DOM, because I am bundling the packages and adding the script to the page, but it doesn't work as expected

**Comment by ije** [comment]
there is a testing for vue shows the SSR in deno is normally working
https://github.com/esm-dev/esm.sh/blob/main/test/vue/vue.test.ts

**Comment by ije** [comment]
can you please give more details? or can you post the code? thanks

**Comment by Antonio476587** [comment]
Thanks for the testing module, I modified it

``` typescript
import { assertEquals } from "https://deno.land/std@0.178.0/testing/asserts.ts";

import { createSSRApp } from "https://esm.sh/vue@3.2.47";
import {
  renderToString,
  renderToWebStream,
} from "https://esm.sh/vue@3.2.47/server-renderer";

const app = createSSRApp({
  data: () => ({ msg: "The Progressive JavaScript Framework" }),
  template: "<div>The Progressive JavaScript Framework</div>",
//   render() {
//     return h("div", this.msg);
//   },
});

Deno.test("Vue", async () => {
  assertEquals(
    await renderToString(app),
    "<div>The Progressive JavaScript Framework</div>",
  );
  assertEquals(
    await new Response(renderToWebStream(app)).text(),
    "<div>The Progressive JavaScript Framework</div>",
  );
});
```
The problem is happening with the template property.

**Comment by Antonio476587** [comment]
If there's anything I can do to help resolve that issue, I'd be happy to help.

**Comment by ije** [comment]
> vue.runtime.esm-bundler.js (default) is runtime only, and requires all templates to be pre-compiled. This is the default entry for bundlers (via module field in package.json) because when using a bundler templates are typically pre-compiled (e.g. in *.vue files).

the vue default export doesn't support template compiler, you need to transpile it before render it with https://github.com/vuejs/core/tree/main/packages/compiler-sfc

**Comment by ije** [comment]
basically it transforms the `template` to `render` above example you changed

**Comment by ije** [comment]
or use `import {createSSRApp} from "https://esm.sh/vue@3.2.47/dist/vue.esm-bundler.js"` instead, this is large module that includes vue compiler, don't use it in prod as vue official suggestion
