### ISSUE TITLE
Failed to import - preact

### ISSUE THREAD

**Issue by notangelmario** [esm-dev/esm.sh#559]
## Failing module

Aparently fetching `preact` while using pinned build versions throws errors. When fetching from `https://esm.sh/preact` everything is fine, but fetching `https://esm.sh/v111/preact` throws something. After digging into it I found that this URL is the problem `https://esm.sh/stable/preact@10.13.1/es2022/preact.js`.

## Error message

After `onload` I got this:

```
/* esm.sh - error */
throw new Error("[esm.sh] " + "resovleESModule: open /tmp/esm-build-preact-10.13.1/node_modules/preact/preact.js: no such file or directory");
export default null;
```

## Additional info

- **esm.sh version**:v111
- **Browser version**: Chrome 111 (Though it doesn't matter, it throws the same error even in deno)

**Comment by ije** [comment]
just fixed, thanks

**Comment by notangelmario** [comment]
Wow, that was quick. I didn't even start looking into it. Great job!
