### ISSUE TITLE
Problems in v112

### ISSUE THREAD

**Issue by lucis** [esm-dev/esm.sh#560]
We're still investigating, but apparently the last release of esm.sh broke some things in our Fresh app.

![image](https://user-images.githubusercontent.com/18706156/227049828-668e9fcf-a044-4756-ae3d-b183ae66c520.png)

This error usually occurs due to version mismatch between server and client's Preact

**Comment by lucis** [comment]
Update:

We had Preact's esm version pinned on v110 and removing the pin fixed it.

**Comment by ije** [comment]
looking into it

**Comment by ije** [comment]
in latest update, the build version prefix will be removed if it's a stable build (react/preact/vue)

https://esm.sh/v110/preact@10.13.1 -> https://esm.sh/preact@10.13.1 (https://esm.sh/stable/preact@10.13.1/es2022/preact.mjs)

**Comment by ije** [comment]
@lucis can you please try again? you may need to update the `deno.lock`

**Comment by lucis** [comment]
@ije what would you like for me to test?

After this change, the problem went away: 

<img width="1151" alt="image" src="https://user-images.githubusercontent.com/18706156/227202888-b8236d01-1daa-4e18-b0e4-b74fe40d8c93.png">

**Comment by ije** [comment]
i see, no need to pin the version, but pin also works

**Comment by lucis** [comment]
Thanks, @ije!

Would you be interested in talking with us from https://deco.cx about what we're doing and how we're using esm.sh? Funding the project would be something we're available.

**Comment by ije** [comment]
> Thanks, @ije!
> 
> Would you be interested in talking with us from https://deco.cx about what we're doing and how we're using esm.sh? Funding the project would be something we're available.

sounds very interesting, what can I do?
