### ISSUE TITLE
Failed to import - expo-server-sdk – Issue with transpiling

### ISSUE THREAD

**Issue by aaron-barbieriaghib** [esm-dev/esm.sh#566]
## Failing module

- **GitHub**: https://github.com/expo/expo-server-sdk-node
- **npm**: https://www.npmjs.com/package/expo-server-sdk

```js
import { Expo } from "https://esm.sh/expo-server-sdk@3.7.0"
```

## Error message

After running `deno run` I got this:

```
Relative import path "http" not prefixed with / or ./ or ../ and not in import map
```

## Additional info

Smart guy at deno said: "Seems like it's not transpiling the module correctly. It probably should be node:http instead of just http." Not sure if that's the only issue.

**Comment by ije** [comment]
fixed in v113
