### ISSUE TITLE
Failed to import - preact/hooks correct version of `create-context.js` Uncaught TypeError: Cannot read properties of undefined (reading '__H')

### ISSUE THREAD

**Issue by pankgeorg** [esm-dev/esm.sh#567]
## Failing module

- **GitHub**: https://github.com/fonsp/Pluto.jl/tree/main/frontend (report https://github.com/fonsp/Pluto.jl/issues/2513)

<img width="389" alt="image" src="https://user-images.githubusercontent.com/8681967/227789736-f1b7180c-4d30-4d91-b4ba-df7792df977d.png">

```js
// @ts-nocheck
import {
    //
    render,
    Component,
    h,
    cloneElement,
    createContext,
    createRef,
    hydrate,
} from "https://esm.sh/v66/preact@10.6.6?target=es2020"
import {
    //
    useEffect,
    useLayoutEffect,
    useState,
    useRef,
    useMemo,
    useCallback,
    useContext,
    useErrorBoundary,
} from "https://esm.sh/v66/preact@10.6.6/hooks?target=es2020"

import htm from "https://esm.sh/v66/htm@3.1.0?target=es2020"

const html = htm.bind(h)

export {
    //
    html,
    render,
    Component,
    useEffect,
    useLayoutEffect,
    useState,
    useRef,
    useMemo,
    useCallback,
    useErrorBoundary,
    createContext,
    createRef,
    useContext,
    h,
    cloneElement,
    hydrate,
}
```

## Error message

After `onload` I got this:

```
Uncaught TypeError: Cannot read properties of undefined (reading '__H')
    at a (index.js:385:43)
    at q (index.js:385:43)
    at F (index.js:385:43)
    at E.EditorLoader [as constructor] (editor.js:136:76)
    at E._e [as render] (create-context.js:3:16)
    at M (create-context.js:3:16)
    at z (create-context.js:3:16)
    at M (create-context.js:3:16)
    at oe (create-context.js:3:16)
    at PlutoEditorComponent.connectedCallback (editor.js:196:9)
```

## Additional info

- **esm.sh version**: 66
- **Browser version**: Google Chrome (Windows 11) 111.0.5563.111 (Official Build) (64-bit) (cohort: Stable)

**Comment by ije** [comment]
<img width="1440" alt="Screenshot 2023-03-27 at 02 37 43" src="https://user-images.githubusercontent.com/2883484/227796852-4430136f-7859-4fe0-af10-4da9972a875b.png">
<img width="1434" alt="Screenshot 2023-03-27 at 02 38 07" src="https://user-images.githubusercontent.com/2883484/227796855-4a6a2767-feac-44c5-ba4e-c66766a959b3.png">

**Comment by ije** [comment]
sorry the v112 changed the module entry name to make you import multiple preact instances, i just added the 301 redirect to those broken modules. it should work fine now. please try again

**Comment by pankgeorg** [comment]
Seems to work ok, thanks!!

**Comment by ije** [comment]
better pin to v113
