### ISSUE TITLE
Failed to import - SolidJS

### ISSUE THREAD

**Issue by modderme123** [esm-dev/esm.sh#568]
## Failing module

- **GitHub**: https://github.com/solidjs/solid
- **npm**: https://npmjs.com/package/solid-js

```js
import * from "https://esm.sh/solid-js"
import * from "https://esm.sh/solid-js/web"
```

This is causing the SolidJS playground to fail

## Error message

After `onload` I got this:

```
You appear to have multiple instances of Solid. This can lead to unexpected behavior.
(anonymous) @ solid-js.development.mjs:1819
```

## Additional info

- **esm.sh version**: v113 (stable urls seems to be referencing v112 versions which is causing issues)
- **Browser version**: Chrome 111

**Comment by ije** [comment]
just fixed, now the server will redirect `/vNUM/...` to `/stable/...`  that gives you a single solid instance

**Comment by modderme123** [comment]
Thanks for the quick response! I tested again and it seems like the ?dev query is no longer being propagated, so we get dev solid-js, then dev solid-js/web, but that imports prod solid-js. Is that possible?

**Comment by modderme123** [comment]
Thanks for the quick response! I tested again and it seems like the ?dev query is no longer being propagated, so we get dev solid-js, then dev solid-js/web, but that imports prod solid-js. Is that possible?

**Comment by ije** [comment]
@modderme123 i also found this issue, will look into it

**Comment by ije** [comment]
only browsers respect the `?dev` and deno uses the server.js based on the `exports` conditions
