### ISSUE TITLE
Typings not being loaded for "dedent" NPM package

### ISSUE THREAD

**Issue by heyajulia** [esm-dev/esm.sh#576]
## Failing module

- **GitHub**: https://github.com/dmnd/dedent
- **npm**: https://www.npmjs.com/package/dedent

```js
import dedent from "https://esm.sh/v113/dedent@0.7.0";
```

## Error message

There's no error message per se, but typings are not loaded, so the function typed as `any` when I mouse over it in Visual Studio Code ([even though typings are available](https://www.npmjs.com/package/@types/dedent)). As a workaround, I'm using https://cdn.skypack.dev/dedent@0.7.0?dts, which does work as expected.

## Additional info

- **esm.sh version**: 113 (I think)
- **Deno version**:

```
deno 1.32.0 (release, x86_64-unknown-linux-gnu)
v8 11.2.214.9
typescript 5.0.2
```

**Comment by echoptic** [comment]
having the same issue with dayjs. when importing from 'npm:' the types work.
```ts
import dayjs from "https://esm.sh/v113/dayjs@1.11.7";
import relativeTime from "https://esm.sh/v113/dayjs@1.11.7/plugin/relativeTime.js";

dayjs.extend(relativeTime);

  // @ts-ignore Deno doesn't recognize the function fromNow
  const ago = dayjs(props.time * 1000).fromNow();
```

**Comment by ije** [comment]
@heyajulia but seems there is no `types` defined in the [package.json](https://registry.npmjs.org/dedent/0.7.0)

**Comment by heyajulia** [comment]
> @heyajulia but seems there is no `types` defined in the [package.json](https://registry.npmjs.org/dedent/0.7.0)

I see that's true; I did not know that was a requirement. I'm guessing Skypack tries to look for (and finds) `@types/dedent` in that case, and esm.sh doesn't.

**Comment by ije** [comment]
> I'm guessing Skypack tries to look for (and finds) @types/dedent in that case, and esm.sh doesn't.

`@types/dedent` doesn't define the `types` field neither, but should use `index.d.ts` instead. i will fix!

**Comment by ije** [comment]
> @ije I'm interested in helping somehow if possible. Is there a related issue open for this?

@echoptic can you please open another issue we can discuss? thanks
