### ISSUE TITLE
Failed to import types - PocketBase

### ISSUE THREAD

**Issue by jerebtw** [esm-dev/esm.sh#580]
## Failing types

- **GitHub**: https://github.com/pocketbase/js-sdk
- **npm**: https://www.npmjs.com/package/pocketbase

```js
import PocketBase from "https://esm.sh/pocketbase"
```

## Description

This is what current is in the `x-typescript-types` header:
https://esm.sh/v113/pocketbase@0.13.1/dist/pocketbase.es.d.mts~.d.ts

This is what should be there:
https://esm.sh/v113/pocketbase@0.13.1/dist/pocketbase.es.d.mts

## Additional info

- **esm.sh version**: v113
- **Deno version**: v1.32.3

**Comment by jerebtw** [comment]
Duplicate of https://github.com/esm-dev/esm.sh/issues/578

**Comment by ije** [comment]
this issue is caused by lacking `.d.mts` support

**Comment by jerebtw** [comment]
I see thanks :)
