### ISSUE TITLE
Failed to import - style-to-js

### ISSUE THREAD

**Issue by MariusVatasoiu** [esm-dev/esm.sh#583]
## Failing module

- **GitHub**: https://github.com/remarkablemark/style-to-js
- **npm**: https://www.npmjs.com/package/style-to-js

```js
import styleToJS from 'https://esm.sh/style-to-js@1.1.3';

console.log(styleToJS("width:100%;", {reactCompat: true}));
```

## Error message

After `onload` I got this:

```
index.js:15 Uncaught TypeError: (0 , style_to_object_1.default) is not a function
    at StyleToJS (index.js:15:36)
```

## Additional info

- **esm.sh version**: v114
- **Browser version**: 111.0.5563.147
- 
This seems to be a regression since with `v113` it works. I think it might be related with #577.

**Comment by ije** [comment]
thank will fix ASAP ❤️
