### ISSUE TITLE
Many modules timing out as of v114

### ISSUE THREAD

**Issue by evelant** [esm-dev/esm.sh#587]
As of a few hours ago (~2:00pm EST) many modules are failing to load from esm.sh. The ones that do load are loading _very_ slowly. Eventually caching deps with Deno will fail with something like

```
error: Import 'https://esm.sh/v114/@effect/data@0.11.8/deno/internal/Iterable.js' failed: 408 Request Timeout
    at https://esm.sh/v114/@effect/data@0.11.8/deno/typeclass/Semigroup.js:2:99
```

I can't even cache the deps for a single Deno script at the moment. Not sure if this is due to a change in esm.sh (things worked fine on v113) or if Cloudflare is having problems.

## Additional info

- **esm.sh version**: 114
- **Deno version**: 1.31.0

**Comment by ije** [comment]
seems it backs to normal, will check the logs

**Comment by ije** [comment]
this should be fixed in v115, thanks for reporting
