### ISSUE TITLE
Failed to import - @superfluid-finance/sdk-core

### ISSUE THREAD

**Issue by ayame113** [esm-dev/esm.sh#588]
## Failing module

- **GitHub**: https://github.com/superfluid-finance/protocol-monorepo/tree/dev/packages/sdk-core
- **npm**: https://www.npmjs.com/package/@superfluid-finance/sdk-core

```js
import "https://esm.sh/@superfluid-finance/sdk-core@0.6.3?target=es2020"
```

## Error message

After `onload` I got this:

```
https://esm.sh/v114/@superfluid-finance/metadata@1.1.3/es2020/metadata.mjs net::ERR_ABORTED 500
```

## Additional info

- **esm.sh version**: v114
- **Browser version**: Google Chrome	112.0.5615.49

`@superfluid-finance/sdk-core` contains a git dependency. esm.sh doesn't support this yet?
https://github.com/superfluid-finance/protocol-monorepo/blob/dev/packages/sdk-core/package.json#L60

**Comment by ije** [comment]
yeah currently we get package info from https://registry.npmjs.org/, doesn't support git repo yet, i have the plan to add it later maybe in next build

**Comment by ayame113** [comment]
I'm happy to hear that. thank you!

**Comment by ije** [comment]
Just added `/gh/superfluid-finance/metadata` pattern to fix this, will work in next build deployed, thanks for reporting

**Comment by ayame113** [comment]
> Just added `/gh/superfluid-finance/metadata` pattern to fix this, will work in next build deployed, thanks for reporting

very cool!!!
