### ISSUE TITLE
Typescript declaration conflicts

### ISSUE THREAD

**Issue by aegooby** [esm-dev/esm.sh#59]
Might be related to #58; importing several packages that depend on different versions of `@types/[package]` for the same package seems to cause major issues. For example, trying to import `react` and `react-dom-router@next` will use `@types/react@17.0.2` and `@types/react@17.0.3` which will lead to TS errors due to things being declared twice. Can be reproduced with the following code:
```ts
import * as React from "https://esm.sh/react";
import * as ReactRouter from "https://esm.sh/react-router-dom@next";
```
This also causes issues with `react-relay` and many other packages (not just these two).

**Comment by ije** [comment]
@types/react is using a fixed version now
