### ISSUE TITLE
blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.

### ISSUE THREAD

**Issue by pankgeorg** [esm-dev/esm.sh#590]
Access to script at 'https://cdn.esm.sh/v64/many-keys-weakmap@1.0.0/es2021/many-keys-weakmap.js' from origin 'https://my-website.com' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.

🤔

**Comment by ije** [comment]
just fixed, the hostname `cdn.esm.sh` will redirect to `esm.sh` now (this issue is caused by missed cors headers of the redirect response), better use `esm.sh` instead

**Comment by ije** [comment]
> Amazing! It didn't block me; I patched the issue on my side and more recent code won't face this, but an old deployment stumbled upon this and thought it would be good to share!
> 
> Thanks!

thanks for sharing!
