### ISSUE TITLE
Feature/Fix: Remove shebang from codes

### ISSUE THREAD

**Issue by renhiyama** [esm-dev/esm.sh#596]
I was thinking of running my cli package that is a nodejs app, directly running it on deno like this:
```sh
 deno run -A -r https://esm.sh/reejs@0.9.0/src/cli/index.js test
```

However, the file doesn't make use of shebang, as we can see the code at https://esm.sh/v115/reejs@0.9.0/deno/src/cli/index.js

```js
/* esm.sh - esbuild bundle(reejs@0.9.0/src/cli/index) deno production */
import __Process$ from "https://deno.land/std@0.177.0/node/process.ts";#!/usr/bin/env node
import{dirname as m}from"/v115/reejs@0.9.0/deno/src/imports/env.js";import a from"/v115/reejs@0.9.0/deno/src/imports/nativeImport.js";import"/v115/reejs@0.9.0/deno/src/utils/log.js";import{Import as e}from"/v115/reejs@0.9.0/deno/src/imports/URLImport.js";import i from"/v115/reejs@0.9.0/deno/src/imports/dynamicImport.js";await Promise.all([e("sade@1.8.1"),e("ora@6.1.2"),e("terser@5.16.6")]);var s=await e("sade@1.8.1"),p=await a("node:fs"),d=await a("node:path"),n=i(await import("/v115/reejs@0.9.0/deno/package.json.js",{assert:{type:"json"}})),l=p.readdirSync(d.join(m,"./cli/cmds")),r={},o=s("reejs");o.version(n.version);for(let t of l)r[t.split(".")[0]]=i(await import(`./cmds/${t}`));for(let t in r)r[t].default(o);o.parse(__Process$.argv);
//# sourceMappingURL=index.js.map
```

Esm.sh adds its own comment at the start of the code, followed by polyfills... then comes our shebang...

Also, if possible, modify the shebang from `node` to the User-Agent used (like bun/node/deno) so it makes sure that we run directly on the runtime we want, and not just running a child process in theory 😄

**Comment by ije** [comment]
since esm.sh serves module as url, i don't see the necessary to modify it for deno/bun.

**Comment by renhiyama** [comment]
maybe atleast remove the shebang from the code so it isnt doesnt result in a syntax error ?

**Comment by ije** [comment]
yes, i am working on it
