### ISSUE TITLE
Failed to import - mqtt@4.3.7 due to missing node_buffer.js

### ISSUE THREAD

**Issue by robinbullock** [esm-dev/esm.sh#604]
## Failing module

- **GitHub**: https://github.com/mqttjs/MQTT.js
- **npm**: https://www.npmjs.com/package/mqtt

```js
import mqtt from "https://esm.sh/mqtt@4.3.7?target=es2022&pin=v99&bundle"
```

## Error message

After `onload` I got this:

```
GET https://esm.sh/v99/node_buffer.js 404
```

## Additional info

- **esm.sh version**: v99
- **Browser version**: Chrome 112.0.5615.49 (Official Build) (arm64)

mqtt depends on rfdc, which in turn depends on the node_buffer polyfill, which seems to have gone missing.

**Comment by robinbullock** [comment]
Guessing it might be related to [this commit](https://github.com/esm-dev/esm.sh/commit/348316efb21c7b5e4ca1bb632876e44268b4ec54) @ije

**Comment by ije** [comment]
oh, sorry for the break change, just deployed a fix patch

**Comment by ije** [comment]
https://esm.sh/v99/node_buffer.js -> https://esm.sh/v99/buffer@6.0.3

**Comment by ije** [comment]
> https://esm.sh/v99/node_buffer.js -> https://esm.sh/v99/buffer@6.0.3

they are same actually

**Comment by robinbullock** [comment]
Confirmed working again, thank you, @ije.
