### ISSUE TITLE
Failed to import - @resvg/resvg-js@2.4.1

### ISSUE THREAD

**Issue by adamjcook** [esm-dev/esm.sh#612]
## Failing module

- **GitHub**: https://github.com/yisibl/resvg-js
- **npm**: https://www.npmjs.com/package/@resvg/resvg-js

```js
import SVGSpriter from "https://esm.sh/v117/*svg-sprite@2.0.2";
```

## Error message

After running `deno run` I got this:

```
error: Import 'https://esm.sh/v117/@resvg/resvg-js@2.4.1' failed: 500 Internal Server Error
    at https://esm.sh/v117/svg-sprite@2.0.2/X-ZS8q/deno/svg-sprite.mjs:2:602
```

## Additional info

- **esm.sh version**: v117
- **Deno version**: 1.32.5

**Comment by ije** [comment]
the error is
```
npm: package '@resvg/resvg-js-darwin-universal'
```

**Comment by adamjcook** [comment]
Hmm.

Probably has something to do with this: https://github.com/yisibl/resvg-js/issues/153

Not sure how to resolve it.

But I will poke around.

Thanks.
