### ISSUE TITLE
Regression: Failed to import - webtorrent [again], excluded modules should be resolved as an empty object

### ISSUE THREAD

**Issue by ThaUnknown** [esm-dev/esm.sh#613]
## Failing module

- **GitHub**: https://github.com/webtorrent/webtorrent
- **npm**: https://npmjs.com/package/webtorrent

```js
import WebTorrent from "https://esm.sh/webtorrent"
```

## Error message

After `onload` I got this:

```
Uncaught TypeError: Cannot read properties of null (reading 'tmpdir')
```

## Additional info

- **esm.sh version**: v117
- **Browser version**: Chromium: 112.0.5615.138

This happens because esm.sh includes polyfills it doesn't support, in this case, fs, which should be resolved to null by the [browser field](https://github.com/webtorrent/webtorrent/blob/master/package.json#L16), I assume the fs polyfill is hardcoded to be included by esm.sh, regardless of if its excluded from the browser field or not

**Comment by ije** [comment]
oh, i will check

**Comment by ThaUnknown** [comment]
ah, my bad, this isn't actually caused by the FS polyfill, but the OS polyfill? see: https://github.com/webtorrent/webtorrent/blob/master/lib/torrent.js#L62-L66

**Comment by ije** [comment]
> https://github.com/webtorrent/webtorrent/blob/master/lib/torrent.js#L62-L66

the server will treat `import os from 'os' // browser exclude` as `const os = null`, but the catch block access field of the null-ish `os`

**Comment by ThaUnknown** [comment]
@ije sorry for late reply

shouldnt it resolve to `const os = {}`? this part isn't documented in the spec, so I'm not sure :/

**Comment by ije** [comment]
ok, i will change to `{}`

**Comment by ThaUnknown** [comment]
> ok, i will change to `{}`

is that really the right choice? again I can't find this in the spec, maybe we could look at how say webpack does it?

**Comment by ThaUnknown** [comment]
@ije sorry for taking so long, yes webpack resolves it to an empty object, so you could change it to `{}` or `new Object()`

**Comment by ije** [comment]
> @ije sorry for taking so long, yes webpack resolves it to an empty object, so you could change it to `{}` or `new Object()`

@ThaUnknown thanks for the info! i will fix~

**Comment by renhiyama** [comment]
@ije @ThaUnknown instead of disabling fs, may I suggest browserfs? There might be any possible npm package that needs fs to boot up and perform basic tasks; so I suggest using this https://github.com/jvilk/BrowserFS
From what I've seen at their readme, it has the same api as node:fs.

**Comment by ije** [comment]
@renhiyama the fs is disabled by package author via `browser` field of package.json, we should not replace it with `browserfs` in this case

**Comment by renhiyama** [comment]
Then what about the other npm packages?

**Comment by ije** [comment]
for other packages, the server use https://esm.sh/v119/node_fs.js
