### ISSUE TITLE
Failed to import - discord.js

### ISSUE THREAD

**Issue by nupanick** [esm-dev/esm.sh#621]
## Failing module

- **GitHub**: https://github.com/discordjs/discord.js
- **npm**: https://www.npmjs.com/package/discord.js

```js
import * as discord from 'https://esm.sh/discord.js@14.10.2';

if (import.meta.main) {
  const dc = new discord.Client();
}

```

## Error message

After running `deno run` I got this:

```
error: Import 'https://esm.sh/discord.js@14.10.2' failed: 500 Internal Server Error
    at file:///D:/Nupa/Spells/nupa-bot-2/main.ts:1:26
```

## Additional info

- **esm.sh version**: 119
- **Deno version**: 1.33.2 (release, x86_64-pc-windows-msvc)

**Comment by nupanick** [comment]
I tried downgrading to discord.js at 13.15.1, but got this instead:

```
error: Import 'https://esm.sh/v119/zlib-sync@0.1.8/deno/zlib-sync.mjs' failed: 500 Internal Server Error
    at https://esm.sh/v119/discord.js@13.15.1/deno/discord.mjs:2:921
```

**Comment by ije** [comment]
currently deno doesn't support native node module from remote
