### ISSUE TITLE
Failed to import - `stripe@12.4.0`

### ISSUE THREAD

**Issue by iuioiua** [esm-dev/esm.sh#623]
## Failing module

- **GitHub**: https://github.com/denoland/saaskit
- **npm**: https://www.npmjs.com/package/stripe

```ts
import Stripe from "https://esm.sh/stripe@12.4.0";
```

```ts
import type { Stripe } from "https://esm.sh/stripe@12.4.0";
```

## Error message

While running `deno check main.ts` within CI, I get this on Ubuntu 22.04:

```
error: Uncaught AssertionError: "data" is unexpectedly null for "https://esm.sh/v119/stripe@12.4.0/types/ProductsResource.d.ts".
    at <anonymous> (ext:deno_tsc/99_main_compiler.js:98:13)
Error: Process completed with exit code 1.
```

and this on macOS 12:

```
error: Uncaught AssertionError: "data" is unexpectedly null for "https://esm.sh/v119/stripe@12.4.0/types/SubscriptionItemsResource.d.ts".
    at <anonymous> (ext:deno_tsc/99_main_compiler.js:98:13)
Error: Process completed with exit code 1.
```

This issue is intermittent, and the type file that raises this assertion error seems to vary unpredictably. Sometimes, I get no issues at all. I've also seen this issue on my local machine:

```
deno 1.33.2 (release, aarch64-apple-darwin)
v8 11.4.183.1
typescript 5.0.3
```

There are other PRs in the repo where CI has failed due to the same issue.

## Additional info

- **esm.sh version**: v119
- **Deno version**: 1.33.2

**Comment by ije** [comment]
@iuioiua  can you share with me the `main.ts` ?

**Comment by iuioiua** [comment]
I just rebased 2 PRs a total of 3 times without error. Previously, I saw this error almost every time CI was engaged. I'll assume this issue is fixed, but re-open if the problem reoccurs.

**Comment by ije** [comment]
@iuioiua thanks 🙏

**Comment by iuioiua** [comment]
The issue appears to be back (see [here](https://github.com/denoland/saaskit/actions/runs/4955956310/jobs/8865858201?pr=187)).
