### ISSUE TITLE
Syntax Error in es6-symbol

### ISSUE THREAD

**Issue by moritztim** [esm-dev/esm.sh#626]
```
error: Uncaught SyntaxError: Identifier '__2$' has already been declared
    at <anonymous> (https://esm.sh/v120/es6-symbol@3.1.3/deno/es6-symbol.mjs:2:168)
```

Deno CLI:
```ts
import * as _ from "https://esm.sh/v120/es6-symbol/deno/es6-symbol.mjs"
```
> Uncaught SyntaxError: Identifier '__2$' has already been declared
>    at async <anonymous>:2:11

Deno File:
```ts
import * as test from "https://esm.sh/v120/es6-symbol/deno/es6-symbol.mjs"
test;
```
> error: Uncaught SyntaxError: Identifier '__2$' has already been declared
>    at <anonymous> (https://esm.sh/v120/es6-symbol@3.1.3/deno/es6-symbol.mjs:2:168)

There's no issue with the original package.
https://github.com/medikoo/es6-symbol/issues/34#issuecomment-1545835900

**Comment by ije** [comment]
thanks, i will look into

**Comment by ije** [comment]
closed in v121
