### ISSUE TITLE
esm.sh fails to import modules with multiple dots in the name

### ISSUE THREAD

**Issue by lino-levan** [esm-dev/esm.sh#627]
It seems like modules ending in several dots doesn't work (something gets truncated incorrectly?)

## Reproduction

```js
import { something } from "https://esm.sh/@wooorm/starry-night@2.0.0/lang/source.ts.js"
```

I get the following error:

```js
/* esm.sh - error */
throw new Error("[esm.sh] " + "resovleESModule: open /esmd/npm/@wooorm/starry-night@2.0.0/node_modules/@wooorm/starry-night/lang/source.ts: no such file or directory");
export default null;
```

## Additional info

Not really relevant but

- **esm.sh version**: v120
- **Deno version**: 1.33.2

**Comment by ije** [comment]
will deploy the patch later
