### ISSUE TITLE
Failed to import - radix3 because of CORS error

### ISSUE THREAD

**Issue by pyrossh** [esm-dev/esm.sh#631]
## Failing module

- **GitHub**: https://github.com/unjs/radix3
- **npm**: https://www.npmjs.com/package/radix3

```js
import { createRouter } from "https://esm.sh/radix3"
```

## Error message

After `onload` I got this:

```
Acess to script at 'https://esm.sh/radix3' from origin 'http://0.0.0.0:3000' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
GET https://esm.sh/radix3 net::ERR_FAILED 302
```

## Additional info

- **esm.sh version**: 121 (from status.json)
- **Browser version**: Chromium: 113.0.5672.77

**Comment by pyrossh** [comment]
Don't know if this an issue now.
But I got it fixed by adding the version in the dependency,
```
https://esm.sh/radix3@1.0.1
```

**Comment by rmorshea** [comment]
I'm experiencing this as well with https://esm.sh/react

**Comment by ije** [comment]
the v121 update breaks the CORS of redircts, just fixed

**Comment by ije** [comment]
@pyrossh @rmorshea can you please comfirm it? thanks

**Comment by rmorshea** [comment]
This has fixed the issue for me.

**Comment by pyrossh** [comment]
Yep it works for me as well without the version tag anymore. Thanks.
