### ISSUE TITLE
Failed to import `https://esm.sh/v92/csstype@3.1.0/index.d.ts`

### ISSUE THREAD

**Issue by piscisaureus** [esm-dev/esm.sh#635]
## Failing module

`https://esm.sh/v92/csstype@3.1.0/index.d.ts`

## Problem

`Content-Type` header is set to `undefined`.

![image](https://github.com/esm-dev/esm.sh/assets/218257/97f29e89-f419-4478-8079-058801fc1d35)

**Comment by renhiyama** [comment]
@piscisaureus shouldn't you use the newer version of esm.sh? V92 is very old.

**Comment by piscisaureus** [comment]
@renhiyama I opened this issue because a Deno Deploy user ran into this issue. 
Ideally the behavior of esm.sh wouldn't change.

**Comment by piscisaureus** [comment]
cc @Crizpy

**Comment by ije** [comment]
@piscisaureus I thanks for reporting, I will fix ASAP

**Comment by piscisaureus** [comment]
cc @Chrizpy

**Comment by piscisaureus** [comment]
Thanks @ije !
