### ISSUE TITLE
Failed to import - async-mutex@0.4.0 (types)

### ISSUE THREAD

**Issue by ije** [esm-dev/esm.sh#642]
![image](https://github.com/esm-dev/esm.sh/assets/2883484/a8505517-ff82-4c0d-b87b-8cd438624367)
<img width="772" alt="Screenshot 2023-05-22 at 20 18 58" src="https://github.com/esm-dev/esm.sh/assets/2883484/837792c0-8c07-4762-99e0-d575af765d6d">

**Comment by roj1512** [comment]
<img width="311" alt="Screenshot 2023-05-22 at 3 21 24 PM" src="https://github.com/esm-dev/esm.sh/assets/49933115/ea87dd94-02c6-4827-b2f3-ec2750e95e02">

Failed attempt: https://github.com/MTKruto/MTKruto/actions/runs/5045546471/jobs/9049958602

**Comment by roj1512** [comment]
Thanks! I will report if it occurs again.
