### ISSUE TITLE
Failed to import - @aws-sdk/client-dynamodb

### ISSUE THREAD

**Issue by gm112** [esm-dev/esm.sh#658]
## Failing module

- **GitHub**: https://github.com/aws/aws-sdk-js-v3
- **npm**: https://www.npmjs.com/package/@aws-sdk/client-dynamodb

```js
import { DynamoDB } from "https://esm.sh/@aws-sdk/client-dynamodb"
```

## Error message

After running `deno bundle file.ts` I got this:

```
[/* your error log here */](error: Node specifiers have not yet been implemented for this subcommand (https://github.com/denoland/deno/issues/15960). Found: node:buffer)
```

I do not want to switch to esbuild if I can avoid it. deno_emit currently throws exceptions with the package as well, but that is not an issue with esm.sh, but with deno_emit.

**Comment by ije** [comment]
`import { DynamoDB } from "https://esm.sh/@aws-sdk/client-dynamodb?target=deno"` should work

**Comment by gm112** [comment]
@ije You're correct - this did work!

Thank you.
