### ISSUE TITLE
Failed to import - @octokit/oauth-app

### ISSUE THREAD

**Issue by wolfy1339** [esm-dev/esm.sh#659]
## Failing module

- **GitHub**: https://github.com/octokit/oauth-app.js/
- **npm**: https://npmjs.com/@octokit/oauth-app

```js
import { createNodeMiddleware } from "https://esm.sh/@octokit/oauth-app"
```

## Error message

After running `deno run` I got this:

```
error: Uncaught SyntaxError: The requested module '/v125/@octokit/oauth-app@4.2.2/denonext/oauth-app.mjs' does not provide an export named 'createNodeMiddleware'
    at <anonymous> (https://esm.sh/v125/@octokit/app@13.1.5/denonext/app.mjs:2:842)

```

## Additional info

- **esm.sh version**: 125
- **Deno version**: 1.34.2

See https://github.com/octokit/oauth-app.js/issues/424

**Comment by ije** [comment]
c77ed5168e0936445b18ac35c4e13d57af5fa0c4 should fix this, i will deploy the patch later

**Comment by wolfy1339** [comment]
Thanks for the quick fix 👍

**Comment by ije** [comment]
@wolfy1339 v126 deployed, please try again (you may need to use the `--reload` flag)

**Comment by wolfy1339** [comment]
Confirmed working
