### ISSUE TITLE
Failed to fetch file returning binary

### ISSUE THREAD

**Issue by igorbrasileiro** [esm-dev/esm.sh#664]
## Failing module

- **preact-render-to-string**: https://esm.sh/preact-render-to-string
Supabase-js and other packages are returning a binary instead of file.

If I add a random querystring with random value, this works https://esm.sh/preact-render-to-string?ije=helpme

This error also happens via deno if uses target=es2022

## Error message
![Screenshot_20230620_125309_Chrome](https://github.com/esm-dev/esm.sh/assets/15680320/a0cb89c8-45b1-46a7-9dc8-4bcd48b042d7)

## Additional info

- **esm.sh version**: latest
- **Browser version**: chrome 114

**Comment by ije** [comment]
seems it's CF CDN cache get bad response, just purged the cache seem it works again

**Comment by igorbrasileiro** [comment]
Thank you @ije it's working properly now.

**Comment by ije** [comment]
better to use pined url https://esm.sh/v126/preact-render-to-string@6.1.0

**Comment by igorbrasileiro** [comment]
> better to use pined url https://esm.sh/v126/preact-render-to-string@6.1.0

You mean to use pined URL to prevent this problem? Ain't fully sure, but I tried this and faced the same issue.

**Comment by KrasserTommy** [comment]
> better to use pined url https://esm.sh/v126/preact-render-to-string@6.1.0

I am getting this error with other modules (react, i18next), and I am using already the pined url. What can I do instead? The webpage only works for a few persons, the others get binaries and errors...

**Comment by rpggio** [comment]
I am seeing the same issue with all of the langchain modules. The response headers declare the content type to be `application/javascript`, but it is not.
Ex: https://esm.sh/langchain@0.0.103/llms/openai

**Comment by igorbrasileiro** [comment]
https://esm.sh/@supabase/supabase-js@2.7.0
This error is happening again

**Comment by rpggio** [comment]
esm CLI chokes on the response (as expected)

```
deno task esm:add langchain
Task esm:add deno run -A https://esm.sh/v128 add "langchain"
error: Uncaught (in promise) SyntaxError: Unexpected token '', "�!D�P�
                                                                      "... is not valid JSON
  const pkg = await res.json();
              ^
```

**Comment by rpggio** [comment]
> > better to use pined url https://esm.sh/v126/preact-render-to-string@6.1.0
> 
> I am getting this error with other modules (react, i18next), and I am using already the pined url. What can I do instead? The webpage only works for a few persons, the others get binaries and errors...

@KrasserTommy I was able to use [npm import](https://deno.land/manual@v1.35.0/node/npm_specifiers) to work around this. 
`import { OpenAI } from "npm:langchain"`

**Comment by matheusgr** [comment]
@ije I am also getting this error with some packages (including the pinned dep: https://esm.sh/v126/preact-render-to-string@6.1.0).

Maybe another CF cache clear will solve this issue?

**Comment by iuioiua** [comment]
> @KrasserTommy If you're using Deno, [npm import](https://deno.land/manual@v1.35.0/node/npm_specifiers) is a workaround.
> `import { OpenAI } from "npm:langchain"`

Heads up. NPM specifiers are not yet supported in Deno Deploy.

**Comment by max-l** [comment]
Is it possible to downgrade versions of esm, as a work around ? 

I was under the impression that the version specifier  (ex: v124  -> https://esm.sh/v124)
could be used for this purpose

**Comment by renhiyama** [comment]
Changing versions wont fix anything. esm.sh on a whole is affected via this bug, I dont think changing versions fixes anything.

**Comment by ije** [comment]
this is a bug of the cache layer not the build server
