### ISSUE TITLE
Feature Request: Preloading files support

### ISSUE THREAD

**Issue by renhiyama** [esm-dev/esm.sh#667]
From what I've speculated, esm.sh build servers are somewhat powerful, being able to build large packages within seconds, not to mention - I feel the code should be efficient too.

However, not every developer has the best pc out there that can perform at the same level. (Running a desktop environment and/or vscode with extensions already means some PCs are way slower than cheap vps too.) So to make downloads more faster (or guessing what files to download beforehand) I feel like esm.sh needs to start adding a "preload" like feature for downloading modules from here.

Preloading js and other binary files on browsers mean downloading them beforehand, so they are always ready to be executed when required. However that might not mean the same here, as  I'm talking about downloading all the files all at once.

In order to have faster downloads and make full use of our internet bandwidth speed, and also in order to fight against npm-like package manager's speed, I have a few recommendations that we could have on esm.sh. Do note that I've taken time thinking about it, and the ideas, if added in esm.sh, are meant to be "cherry on top" and not **breaking changes** to the existing runtimes that make use of URL Imports with using esm.sh in dev/prod. Keeping that in mind, here are 2 ideas:

- Using the official recommended way (how browsers actually work lol)

Making use of the [Link Header](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Link). The noticable downsides are that some libraries (like reejs) needs to include a custom parser for html to json in order to retrieve the data. I expect any interested people to use the following code to parse link header:
```js
const linkHeader = '<https://esm.sh/package/dep1.js>; rel="preload"; as="script", <https://esm.sh/package/dep2.js>; rel="preload"; as="script"';

const links = linkHeader.split(',').map(link => {
  const [url, rel, as] = link.trim().split(';');
  return {
    url: url.slice(1, -1),
    rel: rel.split('=')[1].slice(1, -1),
    as: as.split('=')[1].slice(1, -1)
  };
});

console.log(links);
```
It outputs something as:
```json
[
  {
    "url": "https://esm.sh/package/dep1.js",
    "rel": "preload",
    "as": "script"
  },
  {
    "url": "https://esm.sh/package/dep2.js",
    "rel": "preload",
    "as": "script"
  }
]
```

- Using a non-official way, might be faster/smaller response size:

Using `X-Preload-Deps`header and putting an array of files that can be downloaded parallely (in batches I suppose, so we don't get blacklisted from cloudflare lol)

---

I would personally prefer the first way, esm.sh could easily let **Web Browsers** make use of preload and minimise the total time taken, and improve lighthouse score. The same can't be said for the second method.

I expect esm.sh to support this for the following runtimes/libraries:

- Browser (this feature might actually speed up loading times of a site)
- Reejs (since I'm the owner, I would love to support this feature the first day it launches haha)
- Deno (you might need to ask their devs whether they support it + would there be any unintended side effects?)

**Point to be noted:** esm.sh should only provide this header for the main request. Having Link header on every request of any file might become duplicated/extra not needed "data" sent to clients (browsers?)
As such, it should be enabled for URLs like:

- `https://esm.sh/package`
- `https://esm.sh/package@x.y.z`
- `https://esm.sh/package@x.y.z?<parameters>`
- `https://esm.sh/v<versioning>/package@x.y.z`

And not enabled for:

- `https://esm.sh/v<versioning>/package@x.y.z/some/file.js`

**Comment by ije** [comment]
i am working on it!!!

**Comment by renhiyama** [comment]
@ije so this feature was added in v127 ig. Feel free to close if it did so. I would be adding support for preloading in a week!
