### ISSUE TITLE
Faulty Source Maps

### ISSUE THREAD

**Issue by kylehue** [esm-dev/esm.sh#668]
I've been testing the source maps using this [tool](https://evanw.github.io/source-map-visualization/) and noticed that the original code do not properly align with the generated code. I specifically tested the path-browserify library on both esm.sh and jsDelivr, and the source maps on jsDelivr works like a charm.

**Comment by ije** [comment]
i will look into it, thanks

**Comment by ije** [comment]
<img width="1180" alt="Screenshot 2023-06-27 at 03 20 39" src="https://github.com/esm-dev/esm.sh/assets/2883484/8725e092-45e3-42da-ac23-36a020ed31de">

**Comment by ije** [comment]
will deploy the patch later

**Comment by kylehue** [comment]
i think this should be re-opened because some of the source maps are still faulty, for instance, the @vue/shared package on vue:
![image](https://github.com/esm-dev/esm.sh/assets/84823378/185d6cb0-6607-42fe-8558-53ae7d6e86f9)

this is the same package on jsdelivr and it works fine:
![image](https://github.com/esm-dev/esm.sh/assets/84823378/249a5abf-5b60-4ae3-98ef-e7502ea5a741)

**Comment by ije** [comment]
<img width="927" alt="Screenshot 2023-07-03 at 16 02 13" src="https://github.com/esm-dev/esm.sh/assets/2883484/8dd591ac-20d0-41d1-8670-019b3543c760">
seem it works for me.

**Comment by kylehue** [comment]
> <img alt="Screenshot 2023-07-03 at 16 02 13" width="927" src="https://user-images.githubusercontent.com/2883484/250495525-8dd591ac-20d0-41d1-8670-019b3543c760.png"> seem it works for me.
> https://esm.sh/v127/@vue/shared@3.2.47/es2022/shared.mjs https://esm.sh/v127/@vue/shared@3.2.47/es2022/shared.mjs.map

Oops sorry hahaha, yeah it's working. I just realized that some of the urls are still getting redirected to the older version (v126) 😅
