### ISSUE TITLE
Module aliases not working

### ISSUE THREAD

**Issue by marvinhagemeister** [esm-dev/esm.sh#671]
Aliasing `react` and `react-dom` to `preact/compat` seems to sometimes work and sometimes not.

Works:

- https://esm.sh/@headlessui/react@1.7.14?alias=react:preact/compat,react-dom:preact/compat

Doesn't work because it pulls in `react-dom` even when `?alias` is set:

- https://esm.sh/flowbite-react@v0.4.9?alias=react:preact/compat,react-dom:preact/compat

## Failing module

- **GitHub**: https://github.com/themesberg/flowbite-react
- **npm**: https://www.npmjs.com/package/flowbite-react

```html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Document</title>
  </head>
  <body>
    <script type="importmap">
      {
        "imports": {
          "preact": "https://esm.sh/preact",
          "preact/": "https://esm.sh/preact/",
          "preact/compat": "https://esm.sh/preact/compat",
          "preact/jsx-runtime": "https://esm.sh/preact/jsx-runtime",
          "flowbite-react": "https://esm.sh/flowbite-react@v0.4.9?alias=react:preact/compat,react-dom:preact/compat"
        }
      }
    </script>
    <div id="app"></div>
    <script type="module">
      import { render, h } from "preact";
      import { Button } from "flowbite-react";

      render(h(Button, null, "Click me"), document.getElementById("app"));
    </script>
  </body>
</html>
```

## Error message

None, because it renders nothing as `react-dom` is pulled in instead of `preact`.

## Additional info

- **esm.sh version**: 126
- **Browser version**: Chrome 114.0.5735.133

**Comment by ije** [comment]
thanks! i will look into it

**Comment by ije** [comment]
you can use `?external` param with import maps:
```html
 <script type="importmap">
  {
    "imports": {
      "preact": "https://esm.sh/preact",
      "preact/": "https://esm.sh/preact/",
      "react": "https://esm.sh/preact/compat",
      "react-dom": "https://esm.sh/preact/compat",
      "flowbite-react": "https://esm.sh/flowbite-react@v0.4.9?external=react,react-dom"
    }
  }
</script>
```

**Comment by ije** [comment]
> Works:
>
> https://esm.sh/@headlessui/react@1.7.14?alias=react:preact/compat,react-dom:preact/compat
> Doesn't work because it pulls in `react-dom` even when `?alias` is set:
>
> https://esm.sh/flowbite-react@v0.4.9?alias=react:preact/compat,react-dom:preact/compat

there is a bug of handing subpath of `alias` (react/jsx-runtim in this case)

**Comment by ije** [comment]
i will fix ASAP

**Comment by marvinhagemeister** [comment]
Good call on using `external` and just setting the alias inside the import map. I didn't think of that 👍 

Thanks for fixing the runtime aliasing issue 🙌
