### ISSUE TITLE
Failed to import - `natural@6.5.0`

### ISSUE THREAD

**Issue by whaaaley** [esm-dev/esm.sh#674]
## Failing module

- **GitHub**: https://github.com/NaturalNode/natural
- **npm**: https://www.npmjs.com/package/natural

```js
import natural from 'https://esm.sh/natural@6.5.0'
```

## Error message

After running `deno run` I got this:

```
error: Uncaught Error: Dynamic require of "/home/x/x/x/build/WebWorkerThreads.node" is not supported
    at https://esm.sh/v125/bindings@1.5.0/denonext/bindings.mjs:2:582
    at P (https://esm.sh/v125/bindings@1.5.0/denonext/bindings.mjs:2:2650)
    at https://esm.sh/v125/webworker-threads@0.7.17/denonext/webworker-threads.mjs:2:993
    at https://esm.sh/v125/webworker-threads@0.7.17/denonext/webworker-threads.mjs:2:552
    at https://esm.sh/v125/webworker-threads@0.7.17/denonext/webworker-threads.mjs:2:1070
```

## Additional info

- **esm.sh version**: latest? (how do i check?)
- **Deno version**: 1.34.3

I filed an issue on Natural as well. I have no idea which project should be updated.
https://github.com/NaturalNode/natural/issues/691

**Comment by ije** [comment]
> /home/x/x/x/build/WebWorkerThreads.node

currently esm.sh doesn't support node native module (*.node)

**Comment by whaaaley** [comment]
Natural runs in a browser. I'm not sure why esm.sh is using the native mode module.
