### ISSUE TITLE
Failed to import - firebase@9.23.0/app

### ISSUE THREAD

**Issue by nojaf** [esm-dev/esm.sh#676]
## Failing module

- **GitHub**: https://github.com/firebase/firebase-js-sdk
- **npm**: https://www.npmjs.com/package/firebase

```js
import { initializeApp} from ":https://esm.sh/firebase@9.23.0/app"
```

## Error message

After `onload` I got this:

```
Uncaught SyntaxError: Invalid or unexpected token (at app:1:2))
```

![image](https://github.com/esm-dev/esm.sh/assets/2621499/a33d09b8-304a-4824-adf0-666e617e3221)

## Additional info

- **esm.sh version**:`128` I think (`X-Esm-Deps: https://esm.sh/v128/@firebase/app@0.9.13/es2022/app.mjs`)
- **Browser version**: Chrome 114

This was working yesterday for me.

**Comment by smcardle** [comment]
This looks to be a serious issue with esm.sh in general. Most of the libraries I am using are scrambles in the same way including back to version v89 (the oldest I use) 
I thought the whole point of esm.sh was that any updates DO NOT affect older versions already in the CDN

example; https://esm.sh/v89/lodash@4.17.21

output

!�� W����s�O�
6�D,����e���9^�KĐ�=_+`ЍY�V��e�+2`Qȯi\6�p|4Q�m��bk��e������(��Y�+��F~�

**Comment by thatcher-gaming** [comment]
yeah, i'm getting this too. seems to happen basically at random

**Comment by ije** [comment]
sorry, a mistake i made broken the cache key of CF R2, i am going to revert the commit

**Comment by ije** [comment]
the server is back to normal, @smcardle @nojaf @thatcher-gaming can you please try again

**Comment by thatcher-gaming** [comment]
![image](https://github.com/esm-dev/esm.sh/assets/91325835/870367db-b502-470f-8dfb-dd24a47b4f96)
all good now :)

**Comment by mkeftz** [comment]
Thanks for the quick fix @ije 
Unfortunately it's still not fixed for me requesting this URL: https://esm.sh/react@18.2.0

**Comment by tsirysndr** [comment]
same problems with these packages :
https://esm.sh/@dagger.io/dagger@0.6.3
https://esm.sh/express@4.18.2
https://esm.sh/yaml@2.3.1

**Comment by thatcher-gaming** [comment]
update: it appears to be broken again

**Comment by smcardle** [comment]
This affects loads of the libraries for instance

https://esm.sh/v89/htm@3.1.1

still returns scrambled data

**Comment by ije** [comment]
updated, can you please try again?

**Comment by ije** [comment]
let me explain what happened

**Comment by smcardle** [comment]
Every request for an esm.sh library from my code is now resulting in a 502

**Comment by mkeftz** [comment]
Seems to be working for me now, although required a force refresh. Thank you for your quick response 🙏

**Comment by smcardle** [comment]
Definitely still NOT working

https://esm.sh/v89/preact@10.10.0

**Comment by ije** [comment]
> Definitely still NOT working
> 
> https://esm.sh/v89/preact@10.10.0

did you try to purge your browser/deno cache? seem it works for me

**Comment by smcardle** [comment]
OK. It is now working....

I have no reason to purge the cache as I run in dev tools mode with cache disabled

Anyway thanks for fixing and a bit of re-assurance this will not happen again would be good. 

A discord server or something to report these types of issues and get a "conversation" going would be useful in the future. This kind of issue is a critical issue to some of us and knowing some of the devs are watching / online would be great.

Anyway, esm.sh is my favourite CDN but an explanation of what caused the issue so I can go back to my boss with a "why it happened" scenario would be great.

Also, why would this have affected older version i.e. v89 that were already available and cached ? I thought the whole point of the versioning is that older versions we depend on never get regenerated

**Comment by ije** [comment]
**Let me explain a bit what happened.**

In latest update, I updated the stable build version from v118 to latest(v112) to fix some invalid source map (#668) for react. 

The testing was [passed](https://github.com/esm-dev/esm.sh/actions/runs/5466730371/jobs/9952083334) in github CI env, but i made a mistake to use a different KV that is used to store esm.sh modules at edge. since the new KV is empty the worker need to fetch the module from origin server, but I have no idea why CF worker's `fetch` get garbage content from the esm.sh origin server with correct headers. This doesn't happen in local/CI env.

To fix this, i have to added an [`isValidUTF8`](https://github.com/esm-dev/esm.sh/blob/e864c7e6bf737f1e2a6499448e190f812bd56bfa/packages/esm-worker/src/utils.ts#L69) function to check the content from origin server.

**Comment by ije** [comment]
> A discord server or something to report these types of issues and get a "conversation" going would be useful in the future. This kind of issue is a critical issue to some of us and knowing some of the devs are watching / online would be great.

Discord server: https://discord.gg/XDbjMeb7pb
Status page: https://esm.instatus.com

> Also, why would this have affected older version i.e. v89 that were already available and cached ? I thought the whole point of the versioning is that older versions we depend on never get regenerated
I agree, this is why the version exists. The issue was caused by the cache layer not the build server, i didn't handle it careflully. I should change the KV config seriously in feature updates!

**Comment by zzeleznick** [comment]
Not sure if I'm also seeing a downstream effect due to these changes, but I'm now seeing `Invalid Body` for some packages in addition to 502 responses.

For one of my transitive dependencies (e.g. [he](https://www.npmjs.com/package/he)) there's no longer any valid output (i.e. https://esm.sh/he@1.2.0)

**Comment by nojaf** [comment]
The problem is still ongoing for me in Europe. Getting 502's as well.
It might be a caching problem at this point.

As a local workaround, I spun up a Docker container

> docker run -p 9004:8080 -d --name esm ghcr.io/esm-dev/esm.sh:latest

`http://localhost:9004/firebase@9.23.0/app` works like a charm.

**Comment by nojaf** [comment]
Works again for me:
![image](https://github.com/esm-dev/esm.sh/assets/2621499/68df63a4-6a75-4988-9121-8bcaadcc403e)

Thanks to everyone involved!
