### ISSUE TITLE
This looks to be a serious issue with esm.sh in general.

### ISSUE THREAD

**Issue by smcardle** [esm-dev/esm.sh#677]
This looks to be a serious issue with esm.sh in general. 
Most of the libraries I am using are scrambled in the same way including back to version v89 (the oldest I use) through the latest.
I thought the whole point of esm.sh was that any updates DO NOT affect older versions already in the CDN

example; https://esm.sh/v89/lodash@4.17.21

output

!�� W����s�O�
6�D,����e���9^�KĐ�=_+`ЍY�V��e�+2`Qȯi\6�p|4Q�m��bk��e������(��Y�+��F~�

Additional note:

We reference the url's in the browser <script.../> importmap imports section. This has been working for a very long time and it now not working at all

_Originally posted by @smcardle in https://github.com/esm-dev/esm.sh/issues/676#issuecomment-1624375013_

**Comment by ije** [comment]
my bad mistake, now it should work normal

**Comment by smcardle** [comment]
This is still not resolved. I am now also getting 502 responses

**Comment by khoaln** [comment]
I am getting "Invalid Body" with https://esm.sh/@supabase/supabase-js@2.26.0

**Comment by KrasserTommy** [comment]
Still not resolved :(

**Comment by sndrem** [comment]
I get 502 Invalid body for react-dom

**Comment by sndrem** [comment]
> I get 502 Invalid body for react-dom

Seems to be okay now

**Comment by renhiyama** [comment]
We can close this pr. It's been 4 hours since it's working flawlessly without crashing a single time.
