### ISSUE TITLE
server/build: browser polyfill is missing URL base

### ISSUE THREAD

**Issue by lucab** [esm-dev/esm.sh#678]
In the server-side build logic there is some code to inject polyfills based on the requested target.

The one I've encountered tries to forward a `__Process$` import to https://esm.sh/v128/node_process.js:
https://github.com/esm-dev/esm.sh/blob/703ac3f8cca96889686642cce87bcbd9d51d5393/server/build.go#L732-L740

However the `cfg.CdnBasePath` argument seems to empty, resulting in a rendered URL which is missing the base (i.e. no scheme and hostname).

One example of this can be observed on https://esm.sh/v128/async-validator@4.2.5/esnext/async-validator.mjs:
```js
/* esm.sh - esbuild bundle(async-validator@4.2.5) esnext production */
import __Process$ from "/v128/node_process.js";
[...]
```

**Comment by ije** [comment]
`/v128/node_process.js` is absolute path to current module host nad scheme

**Comment by lucab** [comment]
Thanks for the quick feedback! You are indeed right, I thought the URL was missing the base part and I didn't realize it was instead an absolute path on purpose.
This came up while investigating some other import issues, but I think in the end it was a red herring.
Sorry for noise.
