### ISSUE TITLE
Failed to import due to hash instability for pinned dependency

### ISSUE THREAD

**Issue by rajsite** [esm-dev/esm.sh#680]
## Failing module

- **GitHub**: not public, but package is public
- **npm**: https://www.npmjs.com/package/webvi-websockets

## Error message

After running `deno run` I got this:

```
error: The source code is invalid, as it does not match the expected hash in the lock file.
  Specifier: https://esm.sh/v112/webvi-websockets@3.2.0/deno/source/main.js
  Lock file: C:\dev\github\webvi-experiments\Deno\deno.lock
```

The hash changed for some reason even though it is pinned at esm.sh v112. The lock file was initially created June 6, 2023 and tried to run today and had this failure.

![image](https://github.com/esm-dev/esm.sh/assets/1588923/f3975664-11ec-420a-9247-08d297751569)

I had to update the lock file as a workaround

## Additional info
 
- **esm.sh version**: pinned to v112
- **Deno version**: 1.35.0

**Comment by renhiyama** [comment]
@rajsite with the release of v128, esm.sh bumped the "stable" version to v128 too. It's said on the "releases" page that it will break deno lockfile, you're suggested to delete the lockfile and reinstall the dependencies. I hope this makes it clear for you. If your issue has been fixed, consider closing this issue 🙃

**Comment by rajsite** [comment]
If that's an expected workflow (that some releases may break existing pinned versions) that would be useful as a note in the pinned docs: https://github.com/esm-dev/esm.sh#pinning-build-version

Maybe something like:

```
Note: Periodically the esm.sh service may need to make changes that can cause existing pinned hashes to change and require updating your pinned version to at least the minimum `stableBuild`. The current minimum `stableBuild` is `v128`.
```

Also in the change log I now see the stableBuild is set to v128 but it's very subtle and I did not notice it trying to understand what's happening. I think more strongly worded breaking changes with instructions would help:

```
**BREAKING CHANGE**: The minimum stableBuild was increased to v128. Pinning to older versions is now considered unstable / unsupported.
```

**Comment by rajsite** [comment]
> It's said on the "releases" page that it will break deno lockfile

Unfortunately looking at the releases didn't occur to me as the mental model from the current Pinned readme docs is that I was pinned to a specific release and should not expect changes from new releases.

**Comment by ije** [comment]
@rajsite v128 should not change the content of pined `v112/webvi-websockets@3.2.0`, but i made a mistake that breaks the CDN cache layer. i explained in https://github.com/esm-dev/esm.sh/issues/676#issuecomment-1624482309

**Comment by rajsite** [comment]
Ah that makes more sense. Was getting worried that pinned versions were expected to break periodically.

It sounds like that was a one off issue and not an expected reoccurring behavior. If that's the case makes sense to close this issue. 👍

**Comment by ije** [comment]
thanks for understanding, I will be seriously careful in future updates 🙏

**Comment by rajsite** [comment]
> thanks for understanding, I will be seriously careful in future updates 🙏

Stuff happens! 😂 Thanks for taking the time to respond to my issue and for making the service! Been very helpful!
