### ISSUE TITLE
Failed to import - pug deno

### ISSUE THREAD

**Issue by riverfeya** [esm-dev/esm.sh#688]
cant import deno pug module:
`https://esm.sh/v111/pug@3.0.2/deno/pug.bundle.js`

error:
`HTTP status server error (500 Internal Server Error) for url (https://esm.sh/v111/pug@3.0.2/deno/pug.bundle.js)`

**Comment by ije** [comment]
try `https://esm.sh/v111/pug@3.0.2/deno/pug.bundle.mjs` or `https://esm.sh/v111/pug@3.0.2?bundle` instead
