### ISSUE TITLE
Failed to import - rtzweb

### ISSUE THREAD

**Issue by ije** [esm-dev/esm.sh#690]
context: https://www.val.town/v/stevekrouse.rtzExample

**Comment by twitchax** [comment]
Following. :)

Let me know if I can help provide package information, or new packages.

**Comment by ije** [comment]
@twitchax thanks, just one question, does importing `.wasm` work in node.js?

```js
import * as wasm from "./rtzlib_bg.wasm";
```

**Comment by ije** [comment]
<img width="909" alt="Screenshot 2023-07-26 at 18 04 28" src="https://github.com/esm-dev/esm.sh/assets/2883484/361aa357-a83b-4042-8f7e-d5b87235215e">
seems the latest verison works for me

**Comment by twitchax** [comment]
Cool...I rebuilt with `wasm-pack --target web`.

**Comment by ije** [comment]
@twitchax thanks 🙏
