### ISSUE TITLE
Failed to import - mssql and @azure/identity

### ISSUE THREAD

**Issue by roseMix** [esm-dev/esm.sh#692]
## Failing module

- **npm**: https://www.npmjs.com/package/mssql

```js
import sql from 'https://esm.sh/mssql';

```

## Error message

After running `deno run` I got this:

```
error: Uncaught TypeError: Cannot read properties of undefined (reading 'hash')
    at https://esm.sh/v129/@azure/identity@2.1.0/denonext/identity.mjs:10:12949
```

## Additional info

- **esm.sh version**: 129
- **Deno version**: 1.35.2

**Comment by ije** [comment]
the error is located at `self.location.hash`, please try to add `--location=your.location` flag for `deno run`

**Comment by roseMix** [comment]
After setting the location flag I get this error:
`Failed to connect to <my-database>.database.windows.net:1433 - tlssock._start is not a function`

I'm using the `connect` function provided by this lib. And the same code works fine in Node

Same error occures in Deno when I import via npm specifiers directly `import sql from "npm:mssql"` (though this works without setting the location flag)

**Comment by roseMix** [comment]
I see now this is being addressed by the Deno team here:
https://github.com/denoland/deno/issues/16681

**Comment by ije** [comment]
@roseMix thanks

**Comment by ije** [comment]
try to add `globalThis.location=new URL("your.location")`

**Comment by roseMix** [comment]
I've tried manually setting `globalThis.location` it works only in Deno REPL but not when running a script locally nor on Deploy. See this [example](https://dash.deno.com/playground/dead-tuna-67).
