### ISSUE TITLE
Failed to import - `https://esm.sh/[any-module]?external=react,react-dom,react/jsx-runtime`

### ISSUE THREAD

**Issue by lino-levan** [esm-dev/esm.sh#698]
Was messing around with preact compat in fresh and ran into this. This actually just doesn't work with any module I've tested so far.

It seems to rewrite
```
https://esm.sh/[any-module]?external=react,react-dom,react/jsx-runtime
```
to
```
https://esm.sh/[any-module]@[version]/jsx-runtime?external=react,react-dom,react
```
which is blatantly wrong

**Comment by ije** [comment]
does https://esm.sh/[any-module]?external=react,react-dom work？

**Comment by lino-levan** [comment]
This works (the order matters):
```
https://esm.sh/react-paginate@8.2.0?external=react,react/jsx-runtime,react-dom
```
I'm not sure what the issue is, but it seems putting a module with a `/` at the end causes issues.

**Comment by ije** [comment]
a url ends with `/jsx-runtime` allows the search in the path, for example using dev react jsx runtime:

```jsonc
// tsconfig.json
{
  compilerOptions: {
    "jsx": "react-jsx",
    "jsxImportSource": "https://esm.sh/react@18.2.0?dev"
  }
}
```

**Comment by ije** [comment]
ideally, you dont' need the `external=react/jsx-runtime` when `external=react` set

**Comment by lino-levan** [comment]
Seems to work. Will reopen this issue if I observe anything break later. Thanks for the support X.
