### ISSUE TITLE
Failed to import - many-keys-weakmap | Dropped support for `.js` vs `mjs` extension

### ISSUE THREAD

**Issue by pankgeorg** [esm-dev/esm.sh#703]
## Failing module

- **npm**: https://www.npmjs.com/package/many-keys-weakmap/v/1.0.0

```js
import ManyKeysWeakMap from "https://cdn.esm.sh/v64/many-keys-weakmap@1.0.0/es2021/many-keys-weakmap.js"
```

## Error message

After `onload` I got this:
404

## Additional info

- **esm.sh version**: 64
- **Browser version**: Chrome 115 (latest)

--- 

So I think the problem is that at some point, support for the `.js` extension was dropped. The above link works with `.mjs`. This causes a few issues at the Pluto community where people have deployed versions of this without the `m` :(

**Comment by ije** [comment]
the path structure has been changed, please use below urls:
```js
import ManyKeysWeakMap from "https://esm.sh/v64/many-keys-weakmap@1.0.0?target=es2021"
// or
import ManyKeysWeakMap from "https://esm.sh/v64/many-keys-weakmap@1.0.0/es2021/many-keys-weakmap.mjs"
```

**Comment by pankgeorg** [comment]
Thanks for your time looking into this! We will use the new in any future work, but users of old versions of Pluto have static HTML that point to the `.js` version on version `/v64`. These HTML files are deployed already and are not controlled by us - updating these will require user action. Is it possible for version 64 to respond to the `.js` endpoints as it used to?

**Comment by pankgeorg** [comment]
We're using this style: https://github.com/fonsp/Pluto.jl/commit/8d63bde64771b4014b11034716c78c574b27c879 and https://github.com/fonsp/Pluto.jl/pull/2514 with the pin argument. Does it look ok?

**Comment by ije** [comment]
<img width="845" alt="Screenshot 2023-08-09 at 20 25 57" src="https://github.com/esm-dev/esm.sh/assets/2883484/0554ac38-d37e-4c1e-afa1-e96d5b095644">
i am adding a workaround to redirect the old url the new url.

**Comment by ije** [comment]
will deploy the patch after testing

**Comment by pankgeorg** [comment]
Thank you!

**Comment by ije** [comment]
should works now

**Comment by pankgeorg** [comment]
> should works now

Thanks a ton! I can see the response in cURL from a US server (my browser has a Greek/EU IP so is still getting the old value from cloudflare 😅, but I have faith in cache invalidation!!)

**Comment by ije** [comment]
done, would you like to try again 🙏

**Comment by pankgeorg** [comment]
yes! works like a charm, thanks!!
