### ISSUE TITLE
Failed to import -

### ISSUE THREAD

**Issue by Qsppl** [esm-dev/esm.sh#710]
## Failing module

- **GitHub**: https://github.com/vuejs
- **npm**: https://www.npmjs.com/package/vue

```js
import { createApp } from "https://esm.sh/vue@3.3.4" // not work
```

```js
import { createApp } from "https://esm.sh/vue@3.3.4/dist/vue.esm-browser.js" // work
```

example: https://jsfiddle.net/Tomooko/wt1s6ovf/7/

![image](https://github.com/esm-dev/esm.sh/assets/22717464/1aa0549e-2849-4691-a653-b7fd01e59d09)

Is it really necessary to import a separate vue/../esm assembly to use vue? CDN esm.sh already implies import of the package in esm format.

Note that importing vue.js from node looks like this:
```js
import { createApp } from "vue"
```

Therefore, the developer will try to import vue.js from the CDN in a similar way:
```js
import { createApp } from "https://esm.sh/vue@3.3.4"
```

However, the module will not work and will not return any errors. Finding the bug will be very difficult.

**Comment by ije** [comment]
the URL `https://esm.sh/vue@3.3.4` uses `./dist/vue.runtime.esm-bundler.js` based the `exports` of the package.json that doesn't support template compiling
