### ISSUE TITLE
Failed to import - @pyscript/core 

### ISSUE THREAD

**Issue by WebReflection** [esm-dev/esm.sh#711]
## Failing module

- **GitHub**: https://github.com/pyscript/pyscript/tree/next/pyscript.core
- **npm**: https://www.npmjs.com/package/@pyscript/core

```html
<script type="module" src="https://esm.sh/@pyscript/core@latest/core.js"></script>
```

## Error message

[This file](https://esm.sh/@pyscript/core@0.1.5/core.js) just works on Chrome but it miserably fails on Safari resulting into a 500 Server Error ... the amount of weird things happening here is more than concerning:

```js
/* esm.sh - error */
throw new Error("[esm.sh] " + "esbuild: Top-level await is not available in the configured target environment (\"es2021\")");
export default null;
```

You are deliberately breaking working code out of assumptions I believe made via User Agent sniffing and that breaks completely our users in Safari for stuff that instead just works otherwise.

The error is a 500 which is unrelated with the error that is thrown on the JS side.

With Chrome/ium or Firefox browser that end point just produces the expected result.

This is more than unexpected and bad in general ... you can't detect JS capabilities out of user agent sniffing but it's also none of your business to provide errors otherwise perfectly handled by browsers and devtools themselves.

Please fix this or we'll be forced to move away all our demos and docs from your otherwise lovely service, but this incident smells a bit because we work on very latest APIs and JS features and by no mean we need you to tell us what works and what doesn't ... we already test what works and what doesn't in real browsers, not user agents strings.

Thanks.

## Additional info

- **esm.sh version**:
- **Browser version**: any Safari or WebKit, including TP

**Comment by nicolo-ribaudo** [comment]
From the docs:

> ## ESBuild Options
>
> By default, esm.sh checks the User-Agent header to determine the build target. You can also specify the target by adding ?target, available targets are: es2015 - es2022, esnext, deno, and denonext.

Just use https://esm.sh/@pyscript/core@0.1.5/core.js?target=esnext

**Comment by WebReflection** [comment]
@nicolo-ribaudo not sure what you are suggesting ... this bug is about having this link:
https://esm.sh/@pyscript/core@0.1.5/core.js

showing this result in Chrome/ium
```js
/* esm.sh - @pyscript/core@0.1.5/core */
export * from "/v131/@pyscript/core@0.1.5/es2022/core.js";
```

showing this result in Firefox
```js
/* esm.sh - @pyscript/core@0.1.5/core */
export * from "/v131/@pyscript/core@0.1.5/es2022/core.js";
```

**but** showing this result in Safari
```js
/* esm.sh - error */
throw new Error("[esm.sh] " + "esbuild: Top-level await is not available in the configured target environment (\"es2021\")");
export default null;
```

we're just using the CDN and the CDN does something completely unexpected taking over browsers responsibility to tell users what works and what doesn't out of *valid JS code* that works outside your CDN service.

**Comment by WebReflection** [comment]
to clarify, this bug is about esm.sh User Agent sniffing being obtrusive ... I don't think anyone needs to know that https://esm.sh/@pyscript/core@0.1.5/core.js?target=esnext works, I think developers *might* need to know that if they are targeting a specific version of ECMAScript that shoould be opt-in, not opt-out because by default stuff breaks without reasons to do so ... User Agent sniffing has never been a Web good practice, so this bug is about underlying that's still he case in 2023.

I hope this makes sense.

**Comment by ije** [comment]
my question is does safari support top await? if so this is a bug of esm.sh, or even `target=esnext` wouldn't work in safari

**Comment by ije** [comment]
just checked, safari supports `top await` since version `15`:

<img width="492" alt="Screenshot 2023-08-29 at 09 30 11" src="https://github.com/esm-dev/esm.sh/assets/2883484/79554cae-ce76-4c1b-9f57-7cfc31089e8a">

now i think this is an issue of esm.sh, i will fix ASAP.

**Comment by ije** [comment]
i think there are two tricks that can fix this:

1. using `esnext` instead of checking use-agent, but considering this is a break change i will not take
2. adding more specific target, for example using `target=safari15` instead of  `target=es2021`

**Comment by WebReflection** [comment]
> just checked, safari supports top await since version 15:

do you agree this way forward doesn’t scale and create friction for both you, as maintainer, and users, as consumer of your service, for every single new version of a browser or every possible experimental flag, technical preview, dev or canary channel, of every possible browser?

most importantly, most modules use tools to create already their target / optimized artifact to serve via CDN or at least I do, so that whatever esm .sh does is kinda redundant but even if “smart” it should never break developers intents after build.

I hence see a third option: check a CDN field in package json and, if present, use that exact file AS IS without transforming a single char, eventually adding a comment on top, if strictly necessary.

I’ve been using unpkg field for years now to tell unpkg which file should be served out of the box if the default entry of a module is explicitly defined and I think this won’t break anything because it relies on module updates same way not specifying the version of the module in the URL points at its latest … you can keep the current logic and handle the target burden *but* you can add this feature which could be handy for every other tool / service too, if widely accepted and used by popular modules.

the target solution smells to me regardless because I might want to use something that should never change or break and might not be even in esbuild yet so please consider some escape hatch that’s not on the url for users to remember but defined in the published module for authors to explicitly describe their intent, thank you.

**Comment by WebReflection** [comment]
P.S.

> using esnext instead of checking use-agent, but considering this is a break change i will not take

if you do that for safari it’s not a breaking change because safari is broken already without explicit flags.

On top of that, responding with a 500 (a server error) to throw on browsers breaks fetch expectations too so the current state is currently very broken for Service Workers too or even crawlers or testing tools using WebKit… I’m not sure how it’s even possible nobody else filed issues around the current state … apparently nobody test in real browsers or nobody test Safari/WebKit but that’s another story and changing this can’t break more than it is now, imho.

**Comment by WebReflection** [comment]
An example of my suggestion for a generic module:

```js
{
  "name": "esm",
  "type": "module",
  "exports": {
    ".": {
      "types": "./types/index.d.ts",
      "import": "./esm/index.js",
      "default": "./cjs/index.js",
      "CDN": "./build/index.js"
    },
    "./client": {
      "types": "./types/client.d.ts",
      "import": "./esm/client.js",
      "default": "./cjs/client.js",
      "CDN": "./build/client.js"
    },
    "./server": {
      "types": "./types/server.d.ts",
      "import": "./esm/server.js",
      "default": "./cjs/server.js"
    },
    "./package.json": "./package.json"
  }
}
```

Tools already use the exports field and to me it looks logical and simple to add this as explicit opt-in for modules, and default behavior for CDN services like `esm.sh` ... note that the `server` doesn't have a CDN field so that it can always be optional but, if present, it should tell the CDN there is a file already prepared to be served *AS-IS* from the network.

What do you think? In alternative I still think your option **1** would be the best for Safari users which, in the worst case scenario, will have sites trusting this service just working instead of being broken.

**Comment by ije** [comment]
> An example of my suggestion for a generic module:
> 
> ```js
> {
>   "name": "esm",
>   "type": "module",
>   "exports": {
>     ".": {
>       "types": "./types/index.d.ts",
>       "import": "./esm/index.js",
>       "default": "./cjs/index.js",
>       "CDN": "./build/index.js"
>     },
>     "./client": {
>       "types": "./types/client.d.ts",
>       "import": "./esm/client.js",
>       "default": "./cjs/client.js",
>       "CDN": "./build/client.js"
>     },
>     "./server": {
>       "types": "./types/server.d.ts",
>       "import": "./esm/server.js",
>       "default": "./cjs/server.js"
>     },
>     "./package.json": "./package.json"
>   }
> }
> ```

Vary interesting!! however i don't want to add complexity/cdn-specification to the `package.json`, currently the `exports.import` just works, even commonjs module like React. 

> do you agree this way forward doesn’t scale and create friction for both you, as maintainer, and users, as consumer of your service, for every single new version of a browser or every possible experimental flag, technical preview, dev or canary channel, of every possible browser?

In fact if the server doesn't recognize the `User-Agent`, then the target `esnext` is used. Besides the server also serves source map for debugging.

Currently the problem is esbuild can't transform `top await` and `for await` to lower version because the wrong target was used for Safari/iOS. So my solution is adding browser target instead of esma version.

For example, https://esm.sh/@pyscript/core@0.1.5/core.js will point to https://esm.sh/v131/@pyscript/core@0.1.5/safari15.0/core.js

**Comment by WebReflection** [comment]
> however i don't want to add complexity/cdn-specification to the package.json

unpkg uses the `unpkg` field in the top level of the `package.json` file and that worked well for years ... webpack or other tools check for the `module` field so it looks like everyone else didn't have thoughts about polluting `package.json` ... here I am proposing to use the standard approach for modules imports / requires resolution, adding a field like TypeScript did for types ... it's not obtrusive, it doesn't conflict, it's based on the same standard structure that allows already extensions to it, but if that's too much to handle I don't mind your solution, as long as it happens sooner than later ... that being said:

> In fact if the server doesn't recognize the User-Agent, then the target esnext is used.

the server can't recognize runtime/bootstrap flags neither out of the UA, so this approach is once again problematic to me and it requires you to sync on features per every browser release. If you're willing to do so then good luck, but this issue already shows you can't possibly track all features of every browser with ease and you were stuck at Safari 14 (2 major versions behind) and who knows how many sites avoid this lively service because it didn't work OK in Safari Desktop/Mobile.

I hope you'll reconsider the approach in the future and make the `target` an opt-in, not an opt-out ... sane defaults mean working code as written/intended, magic transpilation/transformations should be explicit, imho.

**Comment by WebReflection** [comment]
bw, if I were you, I would at least factor out this table in a separate folder/project so that it's easier for the community to contribute with updates and features: https://github.com/esm-dev/esm.sh/blob/a37fb5604ed627f4ff289d3a74d6bc56e21b1a87/packages/esm-worker/src/compat.ts#L20-L565

this could help other services too and it could allow anyone to build a static page that verifies all fields and, accordingly with the current browser, show if stuff is indeed supported or not ... evaluating snippets too, helping automating any possible update for that huge table of details.

**Comment by ije** [comment]
> I hope you'll reconsider the approach in the future and make the target an opt-in, not an opt-out ... sane defaults mean working code as written/intended, magic transpilation/transformations should be explicit, imho.

yeah, i like this idea! just a lot of works LOL. and some edge cases should be handled as well, for example if a package has some ohter npm deps then the transpilation(resolver) is a must.

**Comment by WebReflection** [comment]
to clarify, bundling (where possible, ignoring dynamic imports, etc) after resolving modules (ESM vs CJS) and minify that code would be the minimal acceptable transpilation as long as the code is not transformed. I have seen Bun and Deno also get some special treatment, but then again these could also fetch stuff via a fake user agent (let's say curl) and just get code as is via `esnext` ... the thing is that `target=auto` might do what you do now with UA sniffing, browsers, and that table, but the default should be just esnext and let consumers opt-in for any different target only when desired.

anyway, if Safari now works, I am happy regardless and you can close this ... hopefully there won't be other issues to me for the time being.

**Comment by ije** [comment]
just pushed a patch, i think this should fix the safari builds

**Comment by ije** [comment]
> 

i agree! using `User-agent` breaks the consistency of output, i will push it more deep

**Comment by ije** [comment]
> to clarify, bundling (where possible, ignoring dynamic imports, etc) after resolving modules (ESM vs CJS) and minify that code would be the minimal acceptable transpilation as long as the code is not transformed. I have seen Bun and Deno also get some special treatment, but then again these could also fetch stuff via a fake user agent (let's say curl) and just get code as is via `esnext` ... the thing is that `target=auto` might do what you do now with UA sniffing, browsers, and that table, but the default should be just esnext and let consumers opt-in for any different target only when desired.
> 
> anyway, if Safari now works, I am happy regardless and you can close this ... hopefully there won't be other issues to me for the time being.

i agree! using `User-agent` breaks the consistency of output, i will push it more deep.

**Comment by ije** [comment]
> just pushed a patch, i think this should fix the safari builds

and i added a [testing](https://github.com/esm-dev/esm.sh/blob/main/test/issue-711/issue-711.test.ts) for it, will deploy the patch after testing pass.
