### ISSUE TITLE
Failed to import - antd?bundle&target=es2016

### ISSUE THREAD

**Issue by zjfjiayou** [esm-dev/esm.sh#723]
## Failing module

- **GitHub**: https://github.com/my/repo
- **npm**: https://npmjs.com/package/my_package

```js
import { something } from "https://esm.sh/antd@5.9.0?bundle&target=es2016"
import { something } from "https://esm.sh/antd-mobile@5.32.2?bundle&target=es2016"
```

## Error message

throw new Error("[esm.sh] " + "Big integer literals are not available in the configured target environment (\"es2016\")");

```
/* your error log here */
```

## Additional info

- **esm.sh version**:  v132
- **Browser version**: chrome69

**Comment by ije** [comment]
please use `target=es2020` or upper for bigint support
