### ISSUE TITLE
Failed to import lume

### ISSUE THREAD

**Issue by trusktr** [esm-dev/esm.sh#729]
## Failing module

- **GitHub**: https://github.com/lume/element
- **npm**: https://npmjs.com/@lume/element

```js
import('https://esm.sh/lume@0.3.0-alpha.27').then(console.log) // fails
```

## Error message

The `import()` fails with

```
Uncaught (in promise) SyntaxError: The requested module '/v132/@lume/element@0.7.1/es2022/element.mjs' does not provide an export named 'reactive' (at lume.mjs:83:20661)
```

## Additional info

- **esm.sh version**: https://github.com/esm-dev/esm.sh/releases/tag/v132 is the release I see in the repo at time of writing.
- **Browser version**: Chredge 117

## Even more info

- `es2022/element.mjs` looks like a file generated by esm.sh
- the error says `reactive` is not exported
- this is the index for lume/element: https://unpkg.com/@lume/element@0.8.1/dist/index.js
- the index exports * from https://unpkg.com/@lume/element@0.8.1/dist/variable.js
- variable.js exports * from @lume/variable
- here's the index of @lume/variable: https://unpkg.com/@lume/variable@0.8.0/dist/index.js
- lume/variable's index exports `reactive`

Looks like `reactive` is there. Why may esm.sh say it isn't?

**Comment by trusktr** [comment]
Still not working with latest `lume` package and everything is just plain ES Modules.

```js
import('https://esm.sh/lume@0.3.0-alpha.30').then(console.log)
```

Still the same error:

```
Uncaught (in promise) SyntaxError: The requested module '/v133/@lume/element@0.10.1/es2022/element.mjs' does not provide an export named 'reactive' (at lume.mjs:70:2304)
```

It works fine with JSPM:

```js
import('https://jspm.dev/lume@0.3.0-alpha.30').then(console.log)
```

**Comment by ije** [comment]
@trusktr i added a patch for it but doesn't deploy yet(will do soon). please check https://github.com/esm-dev/esm.sh/issues/750#issuecomment-1806841420

**Comment by ije** [comment]
@trusktr i just released esm.sh **v134**, lume now works for me!

<img width="664" alt="Screenshot 2023-11-14 at 22 16 05" src="https://github.com/esm-dev/esm.sh/assets/2883484/64e036d7-6344-4d5e-901b-2e76e4222dc3">

**Comment by trusktr** [comment]
the import is working for me now too! Need to try making some demos now.
