### ISSUE TITLE
Failed to import - @tiptap/extension-collaboration and @hocuspocus/provider

### ISSUE THREAD

**Issue by RicoTrevisan** [esm-dev/esm.sh#732]
## Failing module

- **GitHub**: https://github.com/ueberdosis/tiptap/tree/develop/packages/extension-collaboration
- **npm**: https://www.npmjs.com/package/@tiptap/extension-collaboration

```js
import { Editor } from "https://esm.sh/@tiptap/core";
import StarterKit from "https://esm.sh/@tiptap/starter-kit";

import Collaboration from "https://esm.sh/@tiptap/extension-collaboration"; // only works with @2.0.3?pin=v125
import { TiptapCollabProvider } from "https://esm.sh/@hocuspocus/provider"; // only works with @2.0.0?pin=v125
```

## Error message

After `onload` I got this:

```
Uncaught SyntaxError: The requested module '/v132/crypto-browserify@3.12.0/es2022/crypto-browserify.mjs' does not provide an export named 'webcrypto' (at webcrypto.node.js:1:10)
```

## Additional info

Codepen example: https://codepen.io/ricotrevisan/pen/poqambQ

I'm barely code-literate; I've been learning Javascript while building plugins for a platform called Bubble.io. Be gentle; I'm a rookie.

- **esm.sh version**: v125
- **Browser version**:

**Comment by ije** [comment]
thanks, I will look into it.

**Comment by RicoTrevisan** [comment]
I wonder if this is useful: I was trying to check if there would be any conflicts if I loaded the libraries from Skypack -- it works: https://codepen.io/ricotrevisan/pen/MWZXGXp
