### ISSUE TITLE
Typos on homepage

### ISSUE THREAD

**Issue by kevinfiol** [esm-dev/esm.sh#735]
1. Under `Supporting Nodejs/Bun` section:

> Nodejs(18+) supports http imorting

Should be:

> Nodejs(18+) supports http **importing**

2. Under `Aliasing Dependencies` section:

> The origin idea was coming from [@lucacasonato](https://github.com/lucacasonato).

Should be

> The *original* idea came from [@lucacasonato](https://github.com/lucacasonato).

**Comment by ije** [comment]
thanks 👍 @kevinfiol would you like to create pr, or i will update later

**Comment by ije** [comment]
<img width="911" alt="Screenshot 2023-09-26 at 22 14 21" src="https://github.com/esm-dev/esm.sh/assets/2883484/cfcd9d38-a926-4c4b-ae63-7fe06b0a0fa2">

why not just click the edit icon in the readme section.

**Comment by kevinfiol** [comment]
Didn't realize the homepage is based off the repo README. I'll open a PR soon.

**Comment by kevinfiol** [comment]
Created #736 which fixes the second typo I mentioned.

**Comment by kevinfiol** [comment]
Thanks for merging #736 , @ije . Just a heads up, it looks like the homepage still needs to be rebuilt. See screenshot:
![image](https://github.com/esm-dev/esm.sh/assets/4752973/9a6b485c-fd5e-4f0b-99e4-c02a3911765d)

**Comment by ije** [comment]
thanks, just deployed the changes!
