### ISSUE TITLE
pnpm should prefer npmRegistry config instead of global npm config

### ISSUE THREAD

**Issue by coolyuantao** [esm-dev/esm.sh#737]
To configure the server, I create a `config.json` file then pass it to the server bootstrap command. 
```
  "npmRegistry": "http://npm.xxxx.cn",
```

But I found that when pnpm install packages, it bypassed the npmRegistry config and directly used the global registry config. 

As a result, the packages in the private npm registry could not be loaded correctly. The solution can only be achieved by modifying the global registry config.

Is it a bug or a feature?

**Comment by ije** [comment]
i guess it's kind of a bug, the `npmRegistry` in config.json has higher priority
