### ISSUE TITLE
Failed to import `lume`

### ISSUE THREAD

**Issue by trusktr** [esm-dev/esm.sh#750]
## Failing module

- **GitHub**: https://github.com/lume/lume
- **npm**: https://npmjs.com/package/lume

```js
import('https://esm.sh/lume/dist/index.js').then(console.log)
```

## Error message

Eventually this appears in console:

```
Uncaught (in promise) SyntaxError: The requested module '/v133/@lume/element@0.5.8/es2022/element.mjs' does not provide an export named 'autorun' (at dist.js:3:959)
```

## Additional info

- **esm.sh version**: Latest at time of writing
- **Browser version**: Not a browser issue

`lume` has a fairly simple ESM layout.

**Comment by alemscoder** [comment]
Load from jspm.dev works
`import('https://jspm.dev/lume/dist/index.js').then(console.log)`

**Comment by ije** [comment]
this happens becuase @lume/element has a file like
```js
export * from '@lume/variable';
//# sourceMappingURL=variable.js.map
```
esbuild can't not handle this senarios correctly, so i added a workaround(https://github.com/esm-dev/esm.sh/commit/393bed1c4643cacc60d809b29da5310f80fe1849) to fix this, will deploy the patch later

**Comment by trusktr** [comment]
It works now. Thanks!
