### ISSUE TITLE
Failed to import - luxon@3.4.3 (Cloudflare worker is failing)

### ISSUE THREAD

**Issue by rcwestlake** [esm-dev/esm.sh#753]
## Failing module
https://esm.sh/luxon@3.4.3

I have a Deno build that is failing because the module can not be imported. It looks like there is a larger issue. Even via the browser, there is an issue.

<img width="1206" alt="image" src="https://github.com/esm-dev/esm.sh/assets/9679076/ea4fca4f-147b-4378-9250-f54a1a52ae17">

**Comment by rynomad** [comment]
same problem here in browser, the following 5 imports just started throwing 500s a few minutes ago all at the same time. esm.sh was also down for a minute with a cloudflare error page but is back now. 

## Failing modules
https://esm.sh/@dile/dile-tabs/dile-tabs.js net::ERR_ABORTED 500 (Internal Server Error)
https://esm.sh/@dile/dile-pages/dile-pages.js net::ERR_ABORTED 500 (Internal Server Error)
https://esm.sh/@rjsf/validator-ajv8?alias=lodash:lodash-es net::ERR_ABORTED 500 (Internal Server Error)
https://esm.sh/@rjsf/bootstrap-4?alias=lodash:lodash-es,deps=react@18.2.0,react-dom@18.2.0 net::ERR_ABORTED 500 
https://esm.sh/@open-wc/dedupe-mixin net::ERR_ABORTED 500 (Internal Server Error)

**Comment by rcwestlake** [comment]
Fixed as of now
