### ISSUE TITLE
Failed to import @babel/standalone@7.23.5

### ISSUE THREAD

**Issue by zuisong** [esm-dev/esm.sh#767]
## Failing module
https://esm.sh/@babel/standalone@7.23.5

```js
import * as babel from "https://esm.sh/@babel/standalone@7.23.5"
```

## Error message

After `onload` I got this:

```
/* esm.sh - error */
throw new Error("[esm.sh] " + "Post \"http://localhost:8088\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)");
export default null;
```

## Additional info

- **esm.sh version**: v135
- **Browser version**: Chromium: 119.0.6045.199 (arm64)

![image](https://github.com/esm-dev/esm.sh/assets/19145952/6ca83e04-79db-4915-9e62-45503f92b659)

**Comment by zuisong** [comment]
`https://esm.sh/@babel/standalone@7.23.5?dev` works

<img width="823" alt="image" src="https://github.com/esm-dev/esm.sh/assets/19145952/743cb4ab-99bb-4dc4-80d8-87654605823f">

**Comment by ije** [comment]
works now ( i just recovered the timeout setting for cjs lexer)
