### ISSUE TITLE
Failed to import gh/web-eid/web-eid.js

### ISSUE THREAD

**Issue by dcbr** [esm-dev/esm.sh#779]
## Failing module

- **GitHub**: https://github.com/web-eid/web-eid.js
- **npm**: The package is not on NPM, there is however a gitlab registry
- **GitLab**: https://gitlab.com/api/v4/packages/npm/@web-eid/web-eid-library

```js
import * as webeid from "https://esm.sh/gh/web-eid/web-eid.js@v2.0.2";
```

Note that when locally installed, the correct way to import this module is:
```js
import * as webeid from '@web-eid/web-eid-library/web-eid';
```

## Error message

After `onload` I got this:

No errors, just an empty module is loaded, so e.g. `webeid.getSigningCertificate` fails with the message that no such function exists.

## Additional info

- **esm.sh version**: 135
- **Deno version**: 1.37.2
- **Browser version**: Vivaldi 6.4.3160.42 (chromium 118.0.0.0)

**Comment by ije** [comment]
it returns null because the `main` field of the package.json is undefined, try https://esm.sh/gh/web-eid/web-eid.js@v2.0.2/src/web-eid.ts instead

**Comment by dcbr** [comment]
Ok, that works perfectly, thanks for your help!
