### ISSUE TITLE
Feature request - SSE for package new version

### ISSUE THREAD

**Issue by jdevega** [esm-dev/esm.sh#799]
## Feature request

It would be awesome to have an endpoint were clients can connect to SSE (Server Sent Events) and get notified whenever a new version of a package has been published to the registry ( NPM for example ).

```js
const esmshEvents = new EventSource('https://esm.sh/sse')
esmshEvents.addEventListener('update', (event) => ... );
```

I don't know if this would be something useful or not, but for me, i'll love it if it was implemented.

Thanks for the great work BTW!

**Comment by ije** [comment]
i don't this is possible. think esm.sh is not a registry, it doesn't know what is happening in the back registry unless an user is accessing a module.

**Comment by jdevega** [comment]
Yes, maybe it's out of the scope of esm.sh . Thanks anyway.
