### ISSUE TITLE
Support for building Sass

### ISSUE THREAD

**Issue by glen-84** [esm-dev/esm.sh#80]
Would it be possible to add support for building Sass files?

https://esm.sh/vuetify@next

> /* esm.sh - error */
throw new Error("[esm.sh] " + "esbuild: No loader is configured for \".sass\" files: esm-build-18733500f98f2f68be0fd12fb31cbfc2c013325f/node_modules/vuetify/lib/components/VAlert/VAlert.sass");
export default null;

Maybe with something like https://github.com/glromeo/esbuild-sass-plugin/?

**Comment by ije** [comment]
i have a plan to support this, but we can not use the plugin directly since the server is written in golang
