### ISSUE TITLE
No versions available for esm-node-services

### ISSUE THREAD

**Issue by limbic-derek** [esm-dev/esm.sh#800]
Following this guide:
https://github.com/esm-dev/esm.sh/blob/main/HOSTING.md

Error:

```
node services exit: install services: exit status 1  ERR_PNPM_NO_VERSIONS  No versions available for esm-node-services. The package may be unpublished.
```
 This is just spamming the logs repeatedly.

Config:
```
{
  "port": 8080
}
```

Dockerfile:
```
FROM ghcr.io/esm-dev/esm.sh
ADD ./config.json /etc/esmd/config.json
CMD ["esmd", "--config", "/etc/esmd/config.json"]
```

Build & Run:
```
 docker build -t esmsh . && docker run -p 8080:8080 -t esmsh
```

I'm on MacOS/arm64.

Any ideas?

**Comment by ije** [comment]
i recently removed esm-node-services package from npm which is not needed by the server of the dev  branch, the docker not update yet. however i republished the package, can you please try again? thanks

**Comment by limbic-derek** [comment]
It’s saying it looking for 0.9.1 but 0.9.2 is latest

**Comment by ije** [comment]
i updated the docker image, please try again

**Comment by ije** [comment]
<img width="738" alt="Screenshot 2024-02-28 at 09 43 29" src="https://github.com/esm-dev/esm.sh/assets/2883484/164809ea-20ac-417b-9f0d-62da40467504">

i think you may need to re-pull the image

**Comment by limbic-derek** [comment]
That’s the exact hash I have reporting the same original issue.

**Comment by ije** [comment]
wait..

**Comment by ije** [comment]
<img width="973" alt="Screenshot 2024-02-28 at 11 29 05" src="https://github.com/esm-dev/esm.sh/assets/2883484/dff77a5e-3b60-47e5-945b-3adfd61c9424">

now it should work fine
