### ISSUE TITLE
Failed to import - @mui/material

### ISSUE THREAD

**Issue by schlichtanders** [esm-dev/esm.sh#817]
## Failing module

- **GitHub**: https://github.com/mui/material-ui/
- **npm**: https://www.npmjs.com/package/@mui/material

```js
import { createTheme } from "https://esm.sh/v135/@mui/material@5.15.15?dev&external=react,react-dom&target=es2020"
```

## Error message

```
Uncaught TypeError: _interopRequireDefault is not a function
    npm colorManipulator.development.js:70
    __require2 colorManipulator.development.js:20
    <anonymous> build.js:1
```
Looking into the file, this is clearly because a call to `require("@babel/runtime/...")` got not translated to esm module.

## Additional info

- **esm.sh version**: v135
- **Browser version**: tested in recent firefox (123.0.1) and brave (v1.63.169)

**Comment by schlichtanders** [comment]
@ije can you help investigating how to fix this?

mui/material is recommended by preact for preact components. And preact is awesome to build compilation-free frontends which code works same in browser and node - ideal for esm.sh usage

**Comment by ije** [comment]
i will look into it, thanks for reporting

**Comment by schlichtanders** [comment]
@ije have you had any success?

**Comment by ije** [comment]
yeah just added patch for this, will deploy it later

**Comment by ije** [comment]
deployed, pealse try again thanks

**Comment by schlichtanders** [comment]
Thank you so much for your help and fix!

It works smoothly now :) finally I can use importmaps
