### ISSUE TITLE
Failed to import bcrypt

### ISSUE THREAD

**Issue by thesmart** [esm-dev/esm.sh#843]
## Failing module

- **GitHub**: https://github.com/kelektiv/node.bcrypt.js
- **npm**: https://www.npmjs.com/package/bcrypt

```js
import bcrypt from 'https://esm.sh/bcrypt@5.0.1';
```

## Error message

After running `deno run` I got this:

```
error: Import 'https://esm.sh/v135/@mapbox/node-pre-gyp@1.0.11/denonext/node-pre-gyp.mjs' failed: 500 Internal Server Error
    at https://esm.sh/bcrypt@5.0.1:2:8
```

## Additional info

- **esm.sh version**: not sure
- **Deno version**: 1.44.0

**Comment by thesmart** [comment]
A workaround for anyone viewing this is to use `bcryptjs` instead.

**Comment by ije** [comment]
node native module doesn't work in deno via http import, use `npm:bcrypt`
