### ISSUE TITLE
Failed to import jsx-runtime

### ISSUE THREAD

**Issue by sant123** [esm-dev/esm.sh#846]
## Failing module

```js
import { jsx, jsxs } from "https://esm.sh/react@18.3.1/jsx-runtime";
```

## Error message

I get this type-checking error:

'"https://esm.sh/react@18.3.1/jsx-runtime"' has no exported member named 'jsx'. Did you mean 'JSX'?

## Additional info

- **esm.sh version**: latest (from URL)
- **Deno version**: v1.44.4
- Also [jsx-runtime](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/react/jsx-runtime.d.ts) contains definitions for both `jsx` and `jsxs`

I know these functions have the following comment: `You should not use this function directly. Use JSX and a transpiler instead.`. However I'm aware of it and need to use them directly.

Thanks!!!

**Comment by ije** [comment]
i think it's caused by the incorrect dts, try https://esm.sh/react@18.3.1/jsx-runtime?no-dts

**Comment by sant123** [comment]
It worked but it's typing is any now. However for what I need is okay. 

![image](https://github.com/esm-dev/esm.sh/assets/7959437/089e64e3-f7ed-4a03-885d-0393f0eaaf37)


Thanks @ije
