### ISSUE TITLE
Failed to import - react@rc in development mode

### ISSUE THREAD

**Issue by nicksrandall** [esm-dev/esm.sh#847]
## Failing module

esm.sh is not properly converting the react development package (written as CJS) to ESM. It only provides the default export and nothing else. I can change my code to switch to `import * as React from 'react'` but the issue is that many of my dependencies that use react to not do that so it still breaks. 

- **GitHub**: https://github.com/facebook/react
- **npm**: https://npmjs.com/package/react
```js
import { useEffect } from "https://esm.sh/react@rc?dev"
```

## Error message

After `onload` I got this:

```
Package does not export module `useEffect`. 
```

## Additional info

- **esm.sh version**: 135
- **Browser version**: Latest Chrome

**Comment by ije** [comment]
thanks for reporting! `import { useEffect } from "https://esm.sh/react@rc"` should work good, react 19 changed the development build. i will fix asap!

**Comment by ije** [comment]
<img width="1121" alt="Screenshot 2024-06-28 at 23 56 07" src="https://github.com/esm-dev/esm.sh/assets/2883484/1a164801-93d3-4307-8c5b-fd3b07b9579d">

**Comment by nicksrandall** [comment]
@ije I'm not seeing this as fixed for the dev build (which is what this issue was specifically about).

**Comment by ije** [comment]
> Has this change be deployed to esm.sh?

nope, i will depoy soon
