### ISSUE TITLE
?external - change in minimization behaviour

### ISSUE THREAD

**Issue by 1951FDG** [esm-dev/esm.sh#868]
Hi there,

I noticed that a couple of months ago, adding parameter `external`, would **NOT** lead to files that were minimized to one line, the files generated would have multiple lines.

I was depending on this behaviour to apply patch file based on line numbers.

Is there another parameter (not documented) to avoid minimization to a single line, in order to have multiple lines file output?

**Comment by ije** [comment]
hi, can you please post the urls?

**Comment by 1951FDG** [comment]
I'm using the `/v135/` links generated from the links below
1. @xenova/transformers@2.14.2?&external=onnxruntime-web&standalone
2. @langchain/community/vectorstores/qdrant?deps=@langchain/core@0.1.18&external=@qdrant/js-client-rest&standalone
3. @langchain/community/embeddings/hf_transformers?deps=@langchain/core@0.1.18&external=@xenova/transformers&standalone

For example, for @xenova/transformers, the link to the file today is:
- /v135/@xenova/transformers@2.14.2/X-ZS9vbm54cnVudGltZS13ZWI/es2022/transformers.bundle.mjs

Some helpful context
- On January 29 and also on April 18, 2024 (file info), the /v135/ files generated would have multiple lines.
- Yesterday, I can confirm that the /v135/ files generated are minimized to one line.

One could say this was a bug to begin with, since output I believe in all other cases is always minimized to one line.

**Comment by ije** [comment]
i don't think i can do anything about this, esm.sh is powsered by esbuild, there isn't an option about minimizing code to single line. 

and esbuild uses template string for newlines in string when minimizing, check https://esbuild.github.io/faq/#minified-newlines

**Comment by ije** [comment]
> So if I understand correctly there is no way to tell esbuild to not minimize to one line?

i think so

**Comment by 1951FDG** [comment]
Thanks for confirming!
