### ISSUE TITLE
Failed to import - `s2js`

### ISSUE THREAD

**Issue by missinglink** [esm-dev/esm.sh#869]
Apologies for the issue, I've spent a bunch of time looking over the docs and the code and I couldn't figure this out on my own 🤷‍♂️ 

I'm able to import the module using `https://esm.sh/s2js/dist/index.js` but not as `https://esm.sh/s2js`.

If you could point me in the right direction of how to fix this I'd be very grateful 🙏 
Thanks for the amazing product.

## Failing module

- **GitHub**: https://github.com/missinglink/s2js
- **npm**: https://www.npmjs.com/package/s2js

```js
import { s2 } from 'https://esm.sh/s2js'
```

## Error message

`Module not found`

```bash
curl -vL 'https://esm.sh/s2js'

> GET /s2js HTTP/2
> Host: esm.sh
> User-Agent: curl/8.4.0
> Accept: */*
>
< HTTP/2 302
< date: Thu, 22 Aug 2024 12:27:49 GMT
< content-length: 0
< location: https://esm.sh/s2js@1.38.1
< access-control-allow-origin: *
< cache-control: public, max-age=600
< vary: Origin
< access-control-allow-methods: *
< server: cloudflare
< cf-ray: 8b72dbf478a9372d-FRA
< alt-svc: h3=":443"; ma=86400

< HTTP/2 404
< date: Thu, 22 Aug 2024 12:27:49 GMT
< content-type: text/plain; charset=utf-8
< content-length: 16
< access-control-allow-origin: *
< cache-control: public, max-age=31536000, immutable
< vary: Origin, User-Agent
< access-control-allow-methods: *
< server: cloudflare
< cf-ray: 8b72dbf4f940372d-FRA
< alt-svc: h3=":443"; ma=86400
<

Module not found%
```

## Additional info

Loading the module with the path specified works as expected:

```js
import { s2 } from 'https://esm.sh/s2js/dist/index.js'
```

**Comment by ije** [comment]
<img width="513" alt="Screenshot 2024-08-22 at 20 41 36" src="https://github.com/user-attachments/assets/fd7a6c4a-6616-48a1-ba7e-a9b2fba8f744">

seems the `s2.esm.js` file doesn't exist in the dist folder

**Comment by ije** [comment]
<img width="408" alt="Screenshot 2024-08-22 at 20 45 02" src="https://github.com/user-attachments/assets/60c0a05d-36e9-48f6-9fe6-87ad7b911c0f">

i only found s2js.esm.js

**Comment by missinglink** [comment]
Amazing, thanks very much :pray:
