### ISSUE TITLE
Failed to import - preact in Deno 2

### ISSUE THREAD

**Issue by marvinhagemeister** [esm-dev/esm.sh#874]
With the upcoming Deno 2 release we have dropped the `window` global. It was present in Deno 1.x, but won't be anymore in Deno 2. The transpilation code in esm.sh currently assumes that `Deno === window`, which breaks:

```js
/* esm.sh - esbuild bundle(preact@10.15.1/devtools) denonext production */
// ...snip

// This is a wrong check. The original code has `typeof window !== "undefined"`
typeof Deno<"u"&&window.__PREACT_DEVTOOLS__&& //...
```

## Failing module

- **GitHub**: https://github.com/preactjs/preact
- **npm**: https://npmjs.com/package/preact

```js
import * as devtools from "https://esm.sh/preact@10.15.1/devtools"
console.log(devtools)
```

## Error message

After running `deno run` I got this:

```sh
error: Uncaught (in promise) ReferenceError: window is not defined
    at https://esm.sh/stable/preact@10.15.1/denonext/devtools.js:2:159
```

## Additional info

- **esm.sh version**:
- **Deno version**: 2.0.0-rc.0+2533d68

**Comment by lucacasonato** [comment]
This is also relevant to Deno 1, as web workers also have no `window`

**Comment by ije** [comment]
i found some early code that replaces `typeof window` to `typeof Deno`: https://github.com/esm-dev/esm.sh/blob/v126/server/build.go#L1009-L1015

However the code has been removed since v127, but the build output is cached. and the latest build https://esm.sh/stable/preact@10.23.2/denonext/devtools.js is correct

i'm going the purge the module manually from cache.

**Comment by ije** [comment]
@marvinhagemeister i just purged the outdated modules, can you please check again? thanks

**Comment by marvinhagemeister** [comment]
Can confirm that this is resolved after running Deno with the `--reload` flag. Thanks for the quick help 👍

**Comment by zuisong** [comment]
I apologize for the interruption here
I encountered the same problem after upgrading to deno 2

```shell
> import * as ot from "https://esm.sh/openapi-typescript"
Uncaught ReferenceError: window is not defined
    at https://esm.sh/v135/node_inspector.js:1:203
```

**Comment by ije** [comment]
<img width="608" alt="Screenshot 2024-10-10 at 19 29 51" src="https://github.com/user-attachments/assets/1a42bcd4-06a3-435f-9c30-148fe56e26ff">
@zuisong i just fixed the builtin node ployfills which are using the `window` object, please retry with `--reload` flag
