### ISSUE TITLE
Failed to import -

### ISSUE THREAD

**Issue by Khalilheyrani6367** [esm-dev/esm.sh#876]
## Failing module

- **GitHub**: https://github.com/my/repo
- **npm**: https://npmjs.com/package/my_package

```js
import { something } from "https://esm.sh/my_module"
```

## Error message

After `onload` I got this:

```
/* your error log here */
```

## Additional info

- **esm.sh version**:
- **Browser version**:

**Comment by renhiyama** [comment]
@Khalilheyrani6367 kindly fix the issue content and header or close it. Incase this issue isn't fixed under 24 hours, @ije can force-close it.
