### ISSUE TITLE
Failed to import - https://esm.sh/vue-router

### ISSUE THREAD

**Issue by xiangyin1987** [esm-dev/esm.sh#882]
## Failing module
main.ts
```ts
  import { createApp } from 'https://esm.sh/vue@3.2.31';
  import { createPinia } from 'pinia';
  import App from './App.vue';
  import router from './router';
  import 'amfe-flexible';
  import './assets/styles/index.scss';
  
  const app = createApp(App);
  console.log(router)
  app.use(createPinia());
  app.use(router);
  app.mount('#app');
```
router.ts
```
import { createRouter, createWebHistory } from 'https://esm.sh/vue-router';
import AgriLoans from '@/views/AgriLoans.vue';
const router = createRouter({
  history: createWebHistory(import.meta.env.BASE_URL),
  routes: [
    {
      path: '/agri-loans',
      name: 'agriLoans',
      component: AgriLoans,
    },
  ],
});
export default router;
```
App.vue
```vue
<template>
  <div id="app">
    <div>
      <RouterView />
    </div>
  </div>
</template>
```
## Error message
The browser didn't report an error, but' < RouterView/>' didn't take effect and didn't jump to the corresponding' agri-loans' component.

## Additional info

- **esm.sh version**: v135
- **Browser version**: Version 129.0.6668.60 (official version) (64-bit)

**Comment by ije** [comment]
try https://esm.sh/vue-router?deps=vue@3.2.31, or use import maps to ensure only one vue runtime is loaded

**Comment by xiangyin1987** [comment]
> 尝试https://esm.sh/vue-router?deps=vue@3.2.31，或者使用导入映射来确保只加载一个 vue 运行时

It's working, thank you

**Comment by xiangyin1987** [comment]
> try https://esm.sh/vue-router?deps=vue@3.2.31, or use import maps to ensure only one vue runtime is loaded

It's working, thank you
