### ISSUE TITLE
No space left on device

### ISSUE THREAD

**Issue by hmd-ai** [esm-dev/esm.sh#885]
## Failing module

- Example module: https://esm.sh/*@milkdown/core@7.5.0

## Error message

```
/* esm.sh - error */
throw new Error("[esm.sh] " + "mkdir /esmd/npm/@milkdown: no space left on device");
export default null;
```

**Comment by hmd-ai** [comment]
Previously: #608 #837

**Comment by caramboleyo-no2fa** [comment]
i see it too:
https://esm.sh/tree-selector@2.1.1

**Comment by bigmistqke** [comment]
i see it too: https://esm.sh/tm-grammars@1.18.0

**Comment by ije** [comment]
back to normal now, someone ddos attacked the server!

**Comment by lishaduck** [comment]
It's down again: https://esm.sh/v135/react-markdown@9.0.1/X-ZS8q/denonext/react-markdown.mjs
