### ISSUE TITLE
Bug in the docker version when using the special search param syntax for import map trailing slash

### ISSUE THREAD

**Issue by arieussec-smartsheet** [esm-dev/esm.sh#896]
So this issue only seems to happen when I run esm.sh in Docker. The live version works fine...

Requesting http://localhost:8089/redux-first-router-link@2.1.1&deps=redux-first-router@2.1.1/ using `&` instead of `?` to work in import maps results in this response:
```
invalid package name 'redux-first-router-link@2.1.1&deps=redux-first-router'
```
But when I use `?` then it works correctly.
It seems to be caused by the second `@`

**Comment by ije** [comment]
i just bump the docker image to v135_7 thats fixs the url issue, please try again! thanks

```bash
docker pull ghcr.io/esm-dev/esm.sh:v135_7
```

**Comment by arieussec-smartsheet** [comment]
Hi @ije I don't see that version on https://github.com/esm-dev/esm.sh/pkgs/container/esm.sh

**Comment by ije** [comment]
sorry i forgot to update the tagname in the CI, will fix soon

**Comment by ije** [comment]
pushed
