### ISSUE TITLE
npmRegistries not working

### ISSUE THREAD

**Issue by de-peter** [esm-dev/esm.sh#927]
hi,

i've added a custom npm registry to config file. docker image is using this config file, but when i try to download /@myscope/component... esm tries to download from https://registry.npmjs.org/@myscope?

{
  "npmRegistries": {
    "@myscope": {
      "registry": "https://****/",
      "token": "***"
    }
  }
}

**Comment by de-peter** [comment]
do you know when? maybe you can inform here?

**Comment by ije** [comment]
please follow https://github.com/esm-dev/esm.sh/issues/892, i think it will be relased in a week
