### ISSUE TITLE
Failed to import - 429: Too many requests

### ISSUE THREAD

**Issue by lucis** [esm-dev/esm.sh#939]
For 1h30min we've been experiencing 429 errors when importing from `esm.sh`

```
error: Import 'https://esm.sh/v135/@anthropic-ai/sdk@0.28.0/denonext/_shims/registry.js' failed: 429 Too Many Requests
```

<img width="1477" alt="image" src="https://github.com/user-attachments/assets/73e46d72-92a0-46da-b7fe-31b57fd38819">

**Comment by ije** [comment]
@lucis sorry i did wrong configuration of the Cloudflare's rate limiting rule, now it should work fine!
