### ISSUE TITLE
File not found - https://esm.sh/v134/libphonenumber-js@1.11.16/metadata.max.json

### ISSUE THREAD

**Issue by Eldraed** [esm-dev/esm.sh#951]
## File not found - `https://esm.sh/v134/libphonenumber-js@1.11.16/metadata.max.json`

First, thank you for esm.sh ! It helped us making a Playground to let our devs test/debug our design system and it makes our support easier !

## Error message

The issue is a bit weird from the outside, but is probably not a big deal from the inside. I didn't deep dive your implementation to find the issue, sorry for that.

When I try to reach the external JSON file `https://esm.sh/v134/libphonenumber-js@1.11.16/metadata.max.json` with the **`/v134`**, I have a **File not found** that comes out of it. ❌

But when I try to reach `https://esm.sh/libphonenumber-js@1.11.16/metadata.max.json` without the `/v134`, It works fine ! ✅

So I believe it's probably due to something missing in the `/v134` replica.
Behavior is the same for `/v135` (so probably all `/vXXX` urls)

### Current state

- https://esm.sh/v134/libphonenumber-js@1.11.16/metadata.max.json => ❌ NOT WORKING
- https://esm.sh/libphonenumber-js@1.11.16/metadata.max.json?pin=v134 => ✅
- https://esm.sh/libphonenumber-js@1.11.16/metadata.max.json => ✅

### Additional infos

When looking at the [docs](https://esm.sh/#docs) about `Pinned versions`, I didn't found anything related to a specificity on external files when using `/v134`.

Thanks for your help on this !

PS: I have some issues anyway after to load the json file in the browser by using `import xxx from` (seems not supported yet by the browsers), so on my side I'll be using the `/metadata.max` endpoint that refer to `/metadata.max.js` that includes the JSON file.
But I still open the issue to let you be aware of this 🙂

**Comment by ije** [comment]
in next deployment, we are removing the build version refix `/v134`. and external json module will be resolved with `?module` query which returns a js module.

**Comment by Eldraed** [comment]
Good to know thanks !
I updated to `v135` the other day 🙂

As `?module` will help people with external json in the upcoming deployment, I'm closing this issue 👍
